In [1]:
from google.colab import drive
drive.mount("/content/drive", force_remount=True)

Mounted at /content/drive

In [ ]:
from pathlib import Path

drive_root = Path("/content/drive/MyDrive/research/researchdata")

print("MyDrive exists:", drive_root.exists())

for item in drive_root.iterdir():
    print(item.name)

MyDrive exists: True
ChatGPT Image May 15, 2026, 12_41_04 PM.png
ChatGPT Image May 15, 2026, 07_54_09 PM.png
ChatGPT Image May 15, 2026, 08_02_29 PM.png
Figure 4. Chronological_ Train _Calibration  Test_Split.png
ChatGPT Image May 15, 2026, 08_26_26 PM.png
Figure 5. LightGBM Classifier Flow.png
Figure 3. Data Preprocessing Pipeline.png
Figure 3. Data Preprocessing Pipeline_short.png
Figure 2. Hybrid Score Fusion Mechanism.png
Figure 1. Proposed Hybrid LightGBM–Autoencoder NIDS Architecture.png
step1_new_model_datapreparation.py
step_2_create_autoencoder_ready_dataset.py
step_3_create_chronological_train_test_split.py
step_4_train_dense_autoencoder_.py
step5_explainable_reconstruction_error_analysis.py
step6_for_quick_test_use_existing_autoencoder_model.py
suricata_manual.docx
mikrotik_netflow_raw_2026_05_18_to_21_final_window_clean.zip
D3_feature_engineered_netflow_clean.csv
D3_feature_engineered_netflow_clean.zip
D4_autoencoder_ready_unscaled_clean.zip
D3_feature_engineered_netflow_clean (1).zip
X_test_autoencoder.npy
X_train_autoencoder.npy
X_val_autoencoder.npy
dense_autoencoder_nids_model.keras
D6_autoencoder_anomaly_severity_results.csv
D5_autoencoder_test_anomaly_results.csv
paper_experimental_result_summary.txt
autoencoder_training_history.csv
result_suspicious_by_protocol.csv
result_suspicious_by_service.csv
result_top_suspicious_ports.csv
top_20_suspicious_flows_with_explanation.csv
anomaly_top_feature_frequency.csv
mean_feature_reconstruction_error_suspicious.csv
Figure 1 Proposed Explainable Hybrid NIDS Framework.png
Figure 2 netflow_data_preprocessing_pipeline_overview.png
Figure 7 top_anomaly_causing_features_by_frequency.png
Figure 4 severity_distribution_of_suspicious_test_flows.png
Figure 6 top_suspicious_destination_ports_chart.png
Figure 3 dense_autoencoder_architecture_diagram.png
Figure 5 top_suspicious_services_by_flow_count.png
Fig_9_Autoencoder_Training_Validation_Loss.pdf
Fig_9_Autoencoder_Training_Validation_Loss.png
Fig_8_Highest_Mean_Reconstruction_Error_Features.png
ChatGPT Image May 22, 2026, 11_09_06 PM.png
Fig_1_Deployment_Oriented_Explainable_Autoencoder_NIDS_Framework.png
Fig 1_Deployment_Oriented_Explainable_Autoencoder_NIDS_Framework.png
(Ver.2026.5.23) Explainable Autoencoder_IJIES_37Ref.docx
Final Manuscript of IJIES (1).docx
README_Baseline_Comparison_Experiment.txt
baseline_comparison_experiment (1).py
D5_autoencoder_test_anomaly_results.zip
baseline_comparison_experiment_v2_row_split.py
baseline_results.zip
baseline_comparison_experiment_v3_all_features.py
baseline_comparison_experiment_v4_encode_categorical.py
feature_mismatch_columns.csv
baseline_comparison_experiment_v5_bool_fix.py
baseline_comparison_experiment_v6_bool_dtype_fix.py
baseline_results_v6.zip
threshold_sensitivity_experiment.py
threshold_sensitivity_results (1).zip
threshold_sensitivity_results.zip
other_service_enrichment_experiment.py
other_service_enrichment_results_orginal.zip
f78acbaa2afe1595_NFV3DATA-A11964_A11964.zip
public_autoencoder_validation.py
public_autoencoder_validation_v3_log.py
public_validation_results_v3_fast.zip
Explainable_Autoencoder_IJIES_Clean_Submission_Copy_No6_Updated_Result_Tables_v2.docx
Explainable_Autoencoder_IJIES_Clean_Submission_Copy_No6_Updated_Result_Tables_v3_Final.docx
Explainable_Autoencoder_IJIES_Clean_Submission_Copy_No6_Abstract_Updated_Final.docx
Explainable_Autoencoder_IJIES_Clean_Submission_Copy_No6_With_Confusion_Matrix_Graphs_Final.docx
generate_no6_paper_figures_fixed.py
no6_fixed_figures.zip
generate_confusion_matrix_clear.py
Fig9_public_validation_confusion_matrix_P925_clear.pdf
Fig9_public_validation_confusion_matrix_P925_clear (1).png
Fig9_public_validation_confusion_matrix_P925_clear.png
Explainable_Autoencoder_IJIES_Clean_Submission_Copy_No6_Fixed_Figures_Final.docx
Explainable_Autoencoder_IJIES_A4_SingleColumn_Table15_Updated_CleanA4_NoLogo.docx
Explainable_Autoencoder_IJIES_A4_SingleColumn_Section42_Equation_Aligned_Final.docx
Explainable_Autoencoder_IJIES_A4_SingleColumn_Abstract_49Feature_Aligned_Final.docx
Explainable_Autoencoder_IJIES_A4_SingleColumn_Introduction_Aligned_Final.docx
Explainable_Autoencoder_IJIES_A4_SingleColumn_RelatedWork_Aligned_Final.docx
Explainable_Autoencoder_IJIES_A4_SingleColumn_Problem_Objectives_Contributions_Aligned_Final.docx
Explainable_Autoencoder_IJIES_A4_SingleColumn_Methodology_Aligned_Final.docx
Explainable_Autoencoder_IJIES_A4_SingleColumn_Section5_ExperimentalSetup_Aligned_Final.docx
Explainable_Autoencoder_IJIES_A4_SingleColumn_Section6_Results_Aligned_Final.docx
Section7_Discussion_Aligned_Final.docx
Section7_Discussion_Aligned_Final.zip
Sections8_9_Conclusion_DataCode_Aligned_Final.zip
Sections8_9_Conclusion_DataCode_Aligned_Final.docx
Explainable_Autoencoder_IJIES_A4_Citation_Serialized_Final.docx
Explainable_Autoencoder_IJIES_A4_Fig1_Framework_Aligned_Final_v2.docx
Explainable_Autoencoder_IJIES_A4_Fig1_Framework_Aligned_Final.zip
generate_fig1_simplified_clear_framework.py
generate_fig1_final_clear_no_overlap.py
Fig1_Final_Simple_Readable_Framework.zip
Fig1_EyeCatching_Framework_Final.pdf
Fig1_Eye_Catching_Like_Reference_Final.zip
Fig1_Eye_Catching_Like_Reference_Final.png
Figure. 1 Deployment oriented explainable Autoencoder based NIDS framework..png
updated_autoencoder_architecture_correct_formula.png
Explainable_Autoencoder_IJIES_draft_Final_equations_updated.docx
reproduce_final_paper_results_colab_compatible.py
README.pdf
CICIoT2023
NIDS_Research
NIDS_Research_Checkpoints

In [ ]:
from pathlib import Path

folder = Path(
    "/content/drive/MyDrive/research/researchdata/NIDS_Research/CICIDS2017"
)

print("Folder exists:", folder.exists())

if folder.exists():
    for item in folder.iterdir():
        print(item.name)

Folder exists: True
MachineLearningCSV.zip

In [ ]:
zip_files = list(folder.rglob("*.zip"))

print("ZIP files found:", len(zip_files))

for file in zip_files:
    print(file)

ZIP files found: 1
/content/drive/MyDrive/research/researchdata/NIDS_Research/CICIDS2017/MachineLearningCSV.zip

In [ ]:
import zipfile
from pathlib import Path

if not zip_files:
    raise FileNotFoundError(
        f"No ZIP file was found inside: {folder}"
    )

zip_path = zip_files[0]
extract_path = Path("/content/CICIDS2017")

extract_path.mkdir(parents=True, exist_ok=True)

print("Extracting:", zip_path)

with zipfile.ZipFile(zip_path, "r") as zip_file:
    zip_file.extractall(extract_path)

print("Extraction completed.")

Extracting: /content/drive/MyDrive/research/researchdata/NIDS_Research/CICIDS2017/MachineLearningCSV.zip
Extraction completed.

In [ ]:
files_2017 = sorted(extract_path.rglob("*.csv"))

print("CSV files found:", len(files_2017))

for file in files_2017:
    print(file.name)

CSV files found: 8
Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv
Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv
Friday-WorkingHours-Morning.pcap_ISCX.csv
Monday-WorkingHours.pcap_ISCX.csv
Thursday-WorkingHours-Afternoon-Infilteration.pcap_ISCX.csv
Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX.csv
Tuesday-WorkingHours.pcap_ISCX.csv
Wednesday-workingHours.pcap_ISCX.csv

In [ ]:
from pathlib import Path

drive_root = Path("/content/drive/MyDrive")

files_2018 = [
    file for file in drive_root.rglob("*.csv")
    if "TrafficForML" in file.name
]

files_2018 = sorted(files_2018)

print("CSE-CIC-IDS2018 CSV files:", len(files_2018))

for file in files_2018:
    print(file.name)

CSE-CIC-IDS2018 CSV files: 10
Friday-02-03-2018_TrafficForML_CICFlowMeter.csv
Friday-16-02-2018_TrafficForML_CICFlowMeter.csv
Friday-23-02-2018_TrafficForML_CICFlowMeter.csv
Thuesday-20-02-2018_TrafficForML_CICFlowMeter.csv
Thursday-01-03-2018_TrafficForML_CICFlowMeter.csv
Thursday-15-02-2018_TrafficForML_CICFlowMeter.csv
Thursday-22-02-2018_TrafficForML_CICFlowMeter.csv
Wednesday-14-02-2018_TrafficForML_CICFlowMeter.csv
Wednesday-21-02-2018_TrafficForML_CICFlowMeter.csv
Wednesday-28-02-2018_TrafficForML_CICFlowMeter.csv

In [ ]:
import pandas as pd

file_2017 = csv_files[0]
file_2018 = files_2018[0]

columns_2017 = (
    pd.read_csv(file_2017, nrows=0)
    .columns.str.strip()
    .tolist()
)

columns_2018 = (
    pd.read_csv(file_2018, nrows=0)
    .columns.str.strip()
    .tolist()
)

print("CICIDS2017 column count:", len(columns_2017))
print("CSE-CIC-IDS2018 column count:", len(columns_2018))

print("\nCICIDS2017 columns:")
print(columns_2017)

print("\nCSE-CIC-IDS2018 columns:")
print(columns_2018)

NameError: name 'csv_files' is not defined

In [ ]:
from pathlib import Path
import pandas as pd

# CICIDS2017: extracted temporarily in Colab
cic2017_folder = Path("/content/CICIDS2017")
files_2017 = sorted(cic2017_folder.rglob("*.csv"))

# CSE-CIC-IDS2018: stored in Google Drive
drive_root = Path("/content/drive/MyDrive")
files_2018 = sorted([
    file for file in drive_root.rglob("*.csv")
    if "TrafficForML" in file.name
])

print("CICIDS2017 files:", len(files_2017))
print("CSE-CIC-IDS2018 files:", len(files_2018))

if not files_2017:
    raise FileNotFoundError(
        "CICIDS2017 extracted files are missing. Extract the ZIP again."
    )

if not files_2018:
    raise FileNotFoundError(
        "CSE-CIC-IDS2018 CSV files were not found in Google Drive."
    )

# Read only column headers
columns_2017 = (
    pd.read_csv(files_2017[0], nrows=0)
    .columns.str.strip()
    .tolist()
)

columns_2018 = (
    pd.read_csv(files_2018[0], nrows=0)
    .columns.str.strip()
    .tolist()
)

# Compare columns
common_columns = sorted(set(columns_2017) & set(columns_2018))
only_2017 = sorted(set(columns_2017) - set(columns_2018))
only_2018 = sorted(set(columns_2018) - set(columns_2017))

print("\nSelected CICIDS2017 file:", files_2017[0].name)
print("Selected CSE-CIC-IDS2018 file:", files_2018[0].name)

print("\nCICIDS2017 column count:", len(columns_2017))
print("CSE-CIC-IDS2018 column count:", len(columns_2018))

print("\nExactly matching columns:", len(common_columns))
print(common_columns)

print("\nOnly in CICIDS2017:", len(only_2017))
print(only_2017)

print("\nOnly in CSE-CIC-IDS2018:", len(only_2018))
print(only_2018)

CICIDS2017 files: 8
CSE-CIC-IDS2018 files: 10

Selected CICIDS2017 file: Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv
Selected CSE-CIC-IDS2018 file: Friday-02-03-2018_TrafficForML_CICFlowMeter.csv

CICIDS2017 column count: 79
CSE-CIC-IDS2018 column count: 80

Exactly matching columns: 28
['Active Max', 'Active Mean', 'Active Min', 'Active Std', 'Bwd IAT Max', 'Bwd IAT Mean', 'Bwd IAT Min', 'Bwd IAT Std', 'Bwd PSH Flags', 'Bwd URG Flags', 'CWE Flag Count', 'Down/Up Ratio', 'Flow Duration', 'Flow IAT Max', 'Flow IAT Mean', 'Flow IAT Min', 'Flow IAT Std', 'Fwd IAT Max', 'Fwd IAT Mean', 'Fwd IAT Min', 'Fwd IAT Std', 'Fwd PSH Flags', 'Fwd URG Flags', 'Idle Max', 'Idle Mean', 'Idle Min', 'Idle Std', 'Label']

Only in CICIDS2017: 51
['ACK Flag Count', 'Average Packet Size', 'Avg Bwd Segment Size', 'Avg Fwd Segment Size', 'Bwd Avg Bulk Rate', 'Bwd Avg Bytes/Bulk', 'Bwd Avg Packets/Bulk', 'Bwd Header Length', 'Bwd IAT Total', 'Bwd Packet Length Max', 'Bwd Packet Length Mean', 'Bwd Packet Length Min', 'Bwd Packet Length Std', 'Bwd Packets/s', 'Destination Port', 'ECE Flag Count', 'FIN Flag Count', 'Flow Bytes/s', 'Flow Packets/s', 'Fwd Avg Bulk Rate', 'Fwd Avg Bytes/Bulk', 'Fwd Avg Packets/Bulk', 'Fwd Header Length', 'Fwd Header Length.1', 'Fwd IAT Total', 'Fwd Packet Length Max', 'Fwd Packet Length Mean', 'Fwd Packet Length Min', 'Fwd Packet Length Std', 'Fwd Packets/s', 'Init_Win_bytes_backward', 'Init_Win_bytes_forward', 'Max Packet Length', 'Min Packet Length', 'PSH Flag Count', 'Packet Length Mean', 'Packet Length Std', 'Packet Length Variance', 'RST Flag Count', 'SYN Flag Count', 'Subflow Bwd Bytes', 'Subflow Bwd Packets', 'Subflow Fwd Bytes', 'Subflow Fwd Packets', 'Total Backward Packets', 'Total Fwd Packets', 'Total Length of Bwd Packets', 'Total Length of Fwd Packets', 'URG Flag Count', 'act_data_pkt_fwd', 'min_seg_size_forward']

Only in CSE-CIC-IDS2018: 52
['ACK Flag Cnt', 'Bwd Blk Rate Avg', 'Bwd Byts/b Avg', 'Bwd Header Len', 'Bwd IAT Tot', 'Bwd Pkt Len Max', 'Bwd Pkt Len Mean', 'Bwd Pkt Len Min', 'Bwd Pkt Len Std', 'Bwd Pkts/b Avg', 'Bwd Pkts/s', 'Bwd Seg Size Avg', 'Dst Port', 'ECE Flag Cnt', 'FIN Flag Cnt', 'Flow Byts/s', 'Flow Pkts/s', 'Fwd Act Data Pkts', 'Fwd Blk Rate Avg', 'Fwd Byts/b Avg', 'Fwd Header Len', 'Fwd IAT Tot', 'Fwd Pkt Len Max', 'Fwd Pkt Len Mean', 'Fwd Pkt Len Min', 'Fwd Pkt Len Std', 'Fwd Pkts/b Avg', 'Fwd Pkts/s', 'Fwd Seg Size Avg', 'Fwd Seg Size Min', 'Init Bwd Win Byts', 'Init Fwd Win Byts', 'PSH Flag Cnt', 'Pkt Len Max', 'Pkt Len Mean', 'Pkt Len Min', 'Pkt Len Std', 'Pkt Len Var', 'Pkt Size Avg', 'Protocol', 'RST Flag Cnt', 'SYN Flag Cnt', 'Subflow Bwd Byts', 'Subflow Bwd Pkts', 'Subflow Fwd Byts', 'Subflow Fwd Pkts', 'Timestamp', 'Tot Bwd Pkts', 'Tot Fwd Pkts', 'TotLen Bwd Pkts', 'TotLen Fwd Pkts', 'URG Flag Cnt']

In [ ]:
# Map CSE-CIC-IDS2018 abbreviated names to CICIDS2017 names
mapping_2018_to_2017 = {
    "ACK Flag Cnt": "ACK Flag Count",
    "Bwd Blk Rate Avg": "Bwd Avg Bulk Rate",
    "Bwd Byts/b Avg": "Bwd Avg Bytes/Bulk",
    "Bwd Header Len": "Bwd Header Length",
    "Bwd IAT Tot": "Bwd IAT Total",
    "Bwd Pkt Len Max": "Bwd Packet Length Max",
    "Bwd Pkt Len Mean": "Bwd Packet Length Mean",
    "Bwd Pkt Len Min": "Bwd Packet Length Min",
    "Bwd Pkt Len Std": "Bwd Packet Length Std",
    "Bwd Pkts/b Avg": "Bwd Avg Packets/Bulk",
    "Bwd Pkts/s": "Bwd Packets/s",
    "Bwd Seg Size Avg": "Avg Bwd Segment Size",
    "Dst Port": "Destination Port",
    "ECE Flag Cnt": "ECE Flag Count",
    "FIN Flag Cnt": "FIN Flag Count",
    "Flow Byts/s": "Flow Bytes/s",
    "Flow Pkts/s": "Flow Packets/s",
    "Fwd Act Data Pkts": "act_data_pkt_fwd",
    "Fwd Blk Rate Avg": "Fwd Avg Bulk Rate",
    "Fwd Byts/b Avg": "Fwd Avg Bytes/Bulk",
    "Fwd Header Len": "Fwd Header Length",
    "Fwd IAT Tot": "Fwd IAT Total",
    "Fwd Pkt Len Max": "Fwd Packet Length Max",
    "Fwd Pkt Len Mean": "Fwd Packet Length Mean",
    "Fwd Pkt Len Min": "Fwd Packet Length Min",
    "Fwd Pkt Len Std": "Fwd Packet Length Std",
    "Fwd Pkts/b Avg": "Fwd Avg Packets/Bulk",
    "Fwd Pkts/s": "Fwd Packets/s",
    "Fwd Seg Size Avg": "Avg Fwd Segment Size",
    "Fwd Seg Size Min": "min_seg_size_forward",
    "Init Bwd Win Byts": "Init_Win_bytes_backward",
    "Init Fwd Win Byts": "Init_Win_bytes_forward",
    "PSH Flag Cnt": "PSH Flag Count",
    "Pkt Len Max": "Max Packet Length",
    "Pkt Len Mean": "Packet Length Mean",
    "Pkt Len Min": "Min Packet Length",
    "Pkt Len Std": "Packet Length Std",
    "Pkt Len Var": "Packet Length Variance",
    "Pkt Size Avg": "Average Packet Size",
    "RST Flag Cnt": "RST Flag Count",
    "SYN Flag Cnt": "SYN Flag Count",
    "Subflow Bwd Byts": "Subflow Bwd Bytes",
    "Subflow Bwd Pkts": "Subflow Bwd Packets",
    "Subflow Fwd Byts": "Subflow Fwd Bytes",
    "Subflow Fwd Pkts": "Subflow Fwd Packets",
    "Tot Bwd Pkts": "Total Backward Packets",
    "Tot Fwd Pkts": "Total Fwd Packets",
    "TotLen Bwd Pkts": "Total Length of Bwd Packets",
    "TotLen Fwd Pkts": "Total Length of Fwd Packets",
    "URG Flag Cnt": "URG Flag Count"
}

# Prepare canonical header lists
canonical_2017 = [
    column for column in columns_2017
    if column != "Fwd Header Length.1"
]

canonical_2018 = [
    mapping_2018_to_2017.get(column, column)
    for column in columns_2018
    if column not in ["Protocol", "Timestamp"]
]

common_columns = sorted(
    set(canonical_2017) & set(canonical_2018)
)

only_2017_after_mapping = sorted(
    set(canonical_2017) - set(canonical_2018)
)

only_2018_after_mapping = sorted(
    set(canonical_2018) - set(canonical_2017)
)

print("CICIDS2017 usable columns:", len(canonical_2017))
print("CSE-CIC-IDS2018 usable columns:", len(canonical_2018))
print("Aligned common columns:", len(common_columns))

print("\nUnmatched CICIDS2017 columns:")
print(only_2017_after_mapping)

print("\nUnmatched CSE-CIC-IDS2018 columns:")
print(only_2018_after_mapping)

CICIDS2017 usable columns: 78
CSE-CIC-IDS2018 usable columns: 78
Aligned common columns: 78

Unmatched CICIDS2017 columns:
[]

Unmatched CSE-CIC-IDS2018 columns:
[]

In [ ]:
import pandas as pd

def normalized_header(file, dataset):
    columns = (
        pd.read_csv(file, nrows=0)
        .columns.str.strip()
        .tolist()
    )

    if dataset == "2017":
        columns = [
            column for column in columns
            if column != "Fwd Header Length.1"
        ]

    elif dataset == "2018":
        columns = [
            mapping_2018_to_2017.get(column, column)
            for column in columns
            if column not in ["Protocol", "Timestamp"]
        ]

    return columns


reference_columns = set(common_columns)
problems = []

for file in files_2017:
    header = set(normalized_header(file, "2017"))

    if header != reference_columns:
        problems.append({
            "dataset": "CICIDS2017",
            "file": file.name,
            "missing": sorted(reference_columns - header),
            "additional": sorted(header - reference_columns)
        })

for file in files_2018:
    header = set(normalized_header(file, "2018"))

    if header != reference_columns:
        problems.append({
            "dataset": "CSE-CIC-IDS2018",
            "file": file.name,
            "missing": sorted(reference_columns - header),
            "additional": sorted(header - reference_columns)
        })

print("Files checked:", len(files_2017) + len(files_2018))
print("Schema problems:", len(problems))

for problem in problems:
    print("\n", problem)

Files checked: 18
Schema problems: 1

 {'dataset': 'CSE-CIC-IDS2018', 'file': 'Thuesday-20-02-2018_TrafficForML_CICFlowMeter.csv', 'missing': [], 'additional': ['Dst IP', 'Flow ID', 'Src IP', 'Src Port']}

In [ ]:
excluded_2018 = [
    "Protocol",
    "Timestamp",
    "Flow ID",
    "Src IP",
    "Dst IP",
    "Src Port"
]

def normalized_header(file, dataset):
    columns = (
        pd.read_csv(file, nrows=0)
        .columns.str.strip()
        .tolist()
    )

    if dataset == "2017":
        columns = [
            column for column in columns
            if column != "Fwd Header Length.1"
        ]

    elif dataset == "2018":
        columns = [
            mapping_2018_to_2017.get(column, column)
            for column in columns
            if column not in excluded_2018
        ]

    return columns

In [ ]:
reference_columns = set(common_columns)
problems = []

for file in files_2017:
    header = set(normalized_header(file, "2017"))

    if header != reference_columns:
        problems.append({
            "dataset": "CICIDS2017",
            "file": file.name,
            "missing": sorted(reference_columns - header),
            "additional": sorted(header - reference_columns)
        })

for file in files_2018:
    header = set(normalized_header(file, "2018"))

    if header != reference_columns:
        problems.append({
            "dataset": "CSE-CIC-IDS2018",
            "file": file.name,
            "missing": sorted(reference_columns - header),
            "additional": sorted(header - reference_columns)
        })

print("Files checked:", len(files_2017) + len(files_2018))
print("Schema problems:", len(problems))

for problem in problems:
    print(problem)

Files checked: 18
Schema problems: 0

In [ ]:
semantic_groups = {
    "G1_Packet_Byte_Magnitude": [
        "Total Fwd Packets",
        "Total Backward Packets",
        "Total Length of Fwd Packets",
        "Total Length of Bwd Packets",
        "Fwd Packet Length Max",
        "Fwd Packet Length Min",
        "Fwd Packet Length Mean",
        "Fwd Packet Length Std",
        "Bwd Packet Length Max",
        "Bwd Packet Length Min",
        "Bwd Packet Length Mean",
        "Bwd Packet Length Std",
        "Min Packet Length",
        "Max Packet Length",
        "Packet Length Mean",
        "Packet Length Std",
        "Packet Length Variance",
        "Average Packet Size",
        "Avg Fwd Segment Size",
        "Avg Bwd Segment Size",
        "Subflow Fwd Packets",
        "Subflow Fwd Bytes",
        "Subflow Bwd Packets",
        "Subflow Bwd Bytes",
        "Fwd Avg Bytes/Bulk",
        "Fwd Avg Packets/Bulk",
        "Fwd Avg Bulk Rate",
        "Bwd Avg Bytes/Bulk",
        "Bwd Avg Packets/Bulk",
        "Bwd Avg Bulk Rate",
        "act_data_pkt_fwd",
        "min_seg_size_forward"
    ],

    "G2_Temporal_Activity": [
        "Flow Duration",
        "Flow IAT Mean",
        "Flow IAT Std",
        "Flow IAT Max",
        "Flow IAT Min",
        "Fwd IAT Total",
        "Fwd IAT Mean",
        "Fwd IAT Std",
        "Fwd IAT Max",
        "Fwd IAT Min",
        "Bwd IAT Total",
        "Bwd IAT Mean",
        "Bwd IAT Std",
        "Bwd IAT Max",
        "Bwd IAT Min",
        "Active Mean",
        "Active Std",
        "Active Max",
        "Active Min",
        "Idle Mean",
        "Idle Std",
        "Idle Max",
        "Idle Min"
    ],

    "G3_TCP_Control_Flags": [
        "Fwd PSH Flags",
        "Bwd PSH Flags",
        "Fwd URG Flags",
        "Bwd URG Flags",
        "FIN Flag Count",
        "SYN Flag Count",
        "RST Flag Count",
        "PSH Flag Count",
        "ACK Flag Count",
        "URG Flag Count",
        "CWE Flag Count",
        "ECE Flag Count"
    ],

    "G4_Rate_Header_Flow_Context": [
        "Destination Port",
        "Flow Bytes/s",
        "Flow Packets/s",
        "Fwd Packets/s",
        "Bwd Packets/s",
        "Fwd Header Length",
        "Bwd Header Length",
        "Init_Win_bytes_forward",
        "Init_Win_bytes_backward",
        "Down/Up Ratio"
    ]
}

In [ ]:
from collections import Counter

predictors = set(common_columns) - {"Label"}

assigned_features = [
    feature
    for features in semantic_groups.values()
    for feature in features
]

counts = Counter(assigned_features)

duplicates = sorted([
    feature for feature, count in counts.items()
    if count > 1
])

missing = sorted(predictors - set(assigned_features))
unexpected = sorted(set(assigned_features) - predictors)

print("Common predictors:", len(predictors))

for group_name, features in semantic_groups.items():
    print(group_name, ":", len(features))

print("\nTotal assigned:", len(assigned_features))
print("Duplicate assignments:", duplicates)
print("Missing predictors:", missing)
print("Unexpected features:", unexpected)

Common predictors: 77
G1_Packet_Byte_Magnitude : 32
G2_Temporal_Activity : 23
G3_TCP_Control_Flags : 12
G4_Rate_Header_Flow_Context : 10

Total assigned: 77
Duplicate assignments: []
Missing predictors: []
Unexpected features: []

In [ ]:
import pandas as pd
from collections import Counter
from pathlib import Path
import time

def audit_labels(files, dataset_name, chunksize=500_000):
    dataset_counts = Counter()
    file_results = []

    print(f"\nAuditing {dataset_name}")
    print("=" * 70)

    for number, file in enumerate(files, start=1):
        start_time = time.time()

        # Find the real label-column name, including possible whitespace
        raw_columns = pd.read_csv(file, nrows=0).columns.tolist()

        label_candidates = [
            column for column in raw_columns
            if str(column).strip().lower() == "label"
        ]

        if not label_candidates:
            print(f"Label column not found: {file.name}")
            continue

        actual_label_column = label_candidates[0]
        file_counts = Counter()
        total_rows = 0

        for chunk in pd.read_csv(
            file,
            usecols=[actual_label_column],
            chunksize=chunksize,
            keep_default_na=False
        ):
            labels = (
                chunk[actual_label_column]
                .astype(str)
                .str.strip()
            )

            file_counts.update(labels)
            total_rows += len(chunk)

        dataset_counts.update(file_counts)
        elapsed = time.time() - start_time

        file_results.append({
            "dataset": dataset_name,
            "file": file.name,
            "rows": total_rows,
            "labels": dict(file_counts)
        })

        print(
            f"[{number}/{len(files)}] {file.name}\n"
            f"Rows: {total_rows:,} | "
            f"Labels: {dict(file_counts)} | "
            f"Time: {elapsed:.1f} seconds\n"
        )

    print(f"\n{dataset_name} TOTAL")
    print("Total rows:", f"{sum(dataset_counts.values()):,}")

    for label, count in dataset_counts.most_common():
        print(f"{label}: {count:,}")

    return dataset_counts, file_results

In [ ]:
counts_2017, results_2017 = audit_labels(
    files_2017,
    "CICIDS2017"
)

Auditing CICIDS2017
======================================================================
[1/8] Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv
Rows: 225,745 | Labels: {'BENIGN': 97718, 'DDoS': 128027} | Time: 1.1 seconds

[2/8] Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv
Rows: 286,467 | Labels: {'BENIGN': 127537, 'PortScan': 158930} | Time: 1.1 seconds

[3/8] Friday-WorkingHours-Morning.pcap_ISCX.csv
Rows: 191,033 | Labels: {'BENIGN': 189067, 'Bot': 1966} | Time: 0.9 seconds

[4/8] Monday-WorkingHours.pcap_ISCX.csv
Rows: 529,918 | Labels: {'BENIGN': 529918} | Time: 3.1 seconds

[5/8] Thursday-WorkingHours-Afternoon-Infilteration.pcap_ISCX.csv
Rows: 288,602 | Labels: {'BENIGN': 288566, 'Infiltration': 36} | Time: 2.1 seconds

[6/8] Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX.csv
Rows: 170,366 | Labels: {'BENIGN': 168186, 'Web Attack � Brute Force': 1507, 'Web Attack � XSS': 652, 'Web Attack � Sql Injection': 21} | Time: 1.3 seconds

[7/8] Tuesday-WorkingHours.pcap_ISCX.csv
Rows: 445,909 | Labels: {'BENIGN': 432074, 'FTP-Patator': 7938, 'SSH-Patator': 5897} | Time: 2.6 seconds

[8/8] Wednesday-workingHours.pcap_ISCX.csv
Rows: 692,703 | Labels: {'BENIGN': 440031, 'DoS slowloris': 5796, 'DoS Slowhttptest': 5499, 'DoS Hulk': 231073, 'DoS GoldenEye': 10293, 'Heartbleed': 11} | Time: 3.2 seconds


CICIDS2017 TOTAL
Total rows: 2,830,743
BENIGN: 2,273,097
DoS Hulk: 231,073
PortScan: 158,930
DDoS: 128,027
DoS GoldenEye: 10,293
FTP-Patator: 7,938
SSH-Patator: 5,897
DoS slowloris: 5,796
DoS Slowhttptest: 5,499
Bot: 1,966
Web Attack � Brute Force: 1,507
Web Attack � XSS: 652
Infiltration: 36
Web Attack � Sql Injection: 21
Heartbleed: 11

In [ ]:
counts_2018, results_2018 = audit_labels(
    files_2018,
    "CSE-CIC-IDS2018"
)

Auditing CSE-CIC-IDS2018
======================================================================
[1/10] Friday-02-03-2018_TrafficForML_CICFlowMeter.csv
Rows: 1,048,575 | Labels: {'Benign': 762384, 'Bot': 286191} | Time: 10.0 seconds

[2/10] Friday-16-02-2018_TrafficForML_CICFlowMeter.csv
Rows: 1,048,575 | Labels: {'Benign': 446772, 'DoS attacks-SlowHTTPTest': 139890, 'DoS attacks-Hulk': 461912, 'Label': 1} | Time: 9.8 seconds

[3/10] Friday-23-02-2018_TrafficForML_CICFlowMeter.csv
Rows: 1,048,575 | Labels: {'Benign': 1048009, 'Brute Force -Web': 362, 'Brute Force -XSS': 151, 'SQL Injection': 53} | Time: 20.6 seconds

[4/10] Thuesday-20-02-2018_TrafficForML_CICFlowMeter.csv
Rows: 7,948,748 | Labels: {'Benign': 7372557, 'DDoS attacks-LOIC-HTTP': 576191} | Time: 98.0 seconds

[5/10] Thursday-01-03-2018_TrafficForML_CICFlowMeter.csv
Rows: 331,125 | Labels: {'Benign': 238037, 'Label': 25, 'Infilteration': 93063} | Time: 2.7 seconds

[6/10] Thursday-15-02-2018_TrafficForML_CICFlowMeter.csv
Rows: 1,048,575 | Labels: {'Benign': 996077, 'DoS attacks-GoldenEye': 41508, 'DoS attacks-Slowloris': 10990} | Time: 8.5 seconds

[7/10] Thursday-22-02-2018_TrafficForML_CICFlowMeter.csv
Rows: 1,048,575 | Labels: {'Benign': 1048213, 'Brute Force -Web': 249, 'Brute Force -XSS': 79, 'SQL Injection': 34} | Time: 7.5 seconds

[8/10] Wednesday-14-02-2018_TrafficForML_CICFlowMeter.csv
Rows: 1,048,575 | Labels: {'Benign': 667626, 'FTP-BruteForce': 193360, 'SSH-Bruteforce': 187589} | Time: 8.3 seconds

[9/10] Wednesday-21-02-2018_TrafficForML_CICFlowMeter.csv
Rows: 1,048,575 | Labels: {'Benign': 360833, 'DDOS attack-LOIC-UDP': 1730, 'DDOS attack-HOIC': 686012} | Time: 6.4 seconds

[10/10] Wednesday-28-02-2018_TrafficForML_CICFlowMeter.csv
Rows: 613,104 | Labels: {'Benign': 544200, 'Label': 33, 'Infilteration': 68871} | Time: 4.4 seconds


CSE-CIC-IDS2018 TOTAL
Total rows: 16,233,002
Benign: 13,484,708
DDOS attack-HOIC: 686,012
DDoS attacks-LOIC-HTTP: 576,191
DoS attacks-Hulk: 461,912
Bot: 286,191
FTP-BruteForce: 193,360
SSH-Bruteforce: 187,589
Infilteration: 161,934
DoS attacks-SlowHTTPTest: 139,890
DoS attacks-GoldenEye: 41,508
DoS attacks-Slowloris: 10,990
DDOS attack-LOIC-UDP: 1,730
Brute Force -Web: 611
Brute Force -XSS: 230
SQL Injection: 87
Label: 59

In [ ]:
import pandas as pd

def normalize_binary_label(series):
    cleaned = (
        series.astype(str)
        .str.strip()
    )

    # Repeated header rows and blank labels become invalid
    invalid = (
        cleaned.str.lower().isin(["label", "", "nan"])
    )

    binary = pd.Series(pd.NA, index=series.index, dtype="Int8")

    # Benign spelling differs only by capitalization
    binary.loc[cleaned.str.lower() == "benign"] = 0

    # Every valid non-benign label is an attack
    binary.loc[~invalid & (cleaned.str.lower() != "benign")] = 1

    return binary

In [ ]:
def summarize_binary_counts(label_counts):
    benign = sum(
        count for label, count in label_counts.items()
        if label.strip().lower() == "benign"
    )

    invalid = sum(
        count for label, count in label_counts.items()
        if label.strip().lower() in ["label", "", "nan"]
    )

    total = sum(label_counts.values())
    valid = total - invalid
    attack = valid - benign

    return {
        "original_rows": total,
        "invalid_rows": invalid,
        "valid_rows": valid,
        "benign": benign,
        "attack": attack,
        "attack_percentage": round(attack / valid * 100, 2)
    }

print("CICIDS2017:")
print(summarize_binary_counts(counts_2017))

print("\nCSE-CIC-IDS2018:")
print(summarize_binary_counts(counts_2018))

CICIDS2017:
{'original_rows': 2830743, 'invalid_rows': 0, 'valid_rows': 2830743, 'benign': 2273097, 'attack': 557646, 'attack_percentage': 19.7}

CSE-CIC-IDS2018:
{'original_rows': 16233002, 'invalid_rows': 59, 'valid_rows': 16232943, 'benign': 13484708, 'attack': 2748235, 'attack_percentage': 16.93}

In [ ]:
import pandas as pd
import numpy as np
import time

predictor_columns = sorted(set(common_columns) - {"Label"})

def standardize_chunk(chunk, dataset):
    # Remove whitespace from column names
    chunk.columns = [
        str(column).strip()
        for column in chunk.columns
    ]

    if dataset == "2017":
        chunk = chunk.drop(
            columns=["Fwd Header Length.1"],
            errors="ignore"
        )

    elif dataset == "2018":
        chunk = chunk.drop(
            columns=[
                "Protocol",
                "Timestamp",
                "Flow ID",
                "Src IP",
                "Dst IP",
                "Src Port"
            ],
            errors="ignore"
        )

        chunk = chunk.rename(
            columns=mapping_2018_to_2017
        )

    return chunk


def audit_predictors(files, dataset, chunksize=100_000):
    missing_counts = pd.Series(
        0, index=predictor_columns, dtype="int64"
    )
    nonnumeric_counts = missing_counts.copy()
    positive_inf_counts = missing_counts.copy()
    negative_inf_counts = missing_counts.copy()

    total_original = 0
    total_valid = 0
    total_invalid_labels = 0

    print(f"\nAuditing predictors: {dataset}")
    print("=" * 70)

    for file_number, file in enumerate(files, start=1):
        start_time = time.time()
        file_original = 0
        file_valid = 0
        file_invalid = 0

        for chunk in pd.read_csv(
            file,
            chunksize=chunksize,
            low_memory=False,
            encoding_errors="replace"
        ):
            chunk = standardize_chunk(chunk, dataset)

            labels = (
                chunk["Label"]
                .astype(str)
                .str.strip()
                .str.lower()
            )

            invalid_label = labels.isin(
                ["label", "", "nan"]
            )

            file_original += len(chunk)
            file_invalid += int(invalid_label.sum())

            # Remove invalid/repeated-header rows
            chunk = chunk.loc[
                ~invalid_label,
                predictor_columns
            ]

            file_valid += len(chunk)

            raw_missing = chunk.isna()

            numeric = chunk.apply(
                pd.to_numeric,
                errors="coerce"
            )

            converted_missing = numeric.isna()

            missing_counts += raw_missing.sum().astype("int64")

            # Values present originally but not convertible to numbers
            nonnumeric_counts += (
                converted_missing & ~raw_missing
            ).sum().astype("int64")

            positive_inf_counts += (
                numeric == np.inf
            ).sum().astype("int64")

            negative_inf_counts += (
                numeric == -np.inf
            ).sum().astype("int64")

            del chunk, numeric, raw_missing, converted_missing

        total_original += file_original
        total_valid += file_valid
        total_invalid_labels += file_invalid

        elapsed = time.time() - start_time

        print(
            f"[{file_number}/{len(files)}] {file.name}\n"
            f"Original: {file_original:,} | "
            f"Valid: {file_valid:,} | "
            f"Invalid labels: {file_invalid:,} | "
            f"Time: {elapsed:.1f} seconds\n"
        )

    report = pd.DataFrame({
        "missing": missing_counts,
        "nonnumeric": nonnumeric_counts,
        "positive_infinity": positive_inf_counts,
        "negative_infinity": negative_inf_counts
    })

    report["total_issues"] = report.sum(axis=1)
    report = report.sort_values(
        "total_issues",
        ascending=False
    )

    print("\nSummary")
    print("Original rows:", f"{total_original:,}")
    print("Invalid-label rows:", f"{total_invalid_labels:,}")
    print("Valid rows:", f"{total_valid:,}")
    print(
        "Features containing issues:",
        int((report["total_issues"] > 0).sum())
    )

    print("\nFeatures with detected issues:")
    display(report[report["total_issues"] > 0])

    return report

In [ ]:
quality_2017 = audit_predictors(
    files_2017,
    "2017"
)

Auditing predictors: 2017
======================================================================
[1/8] Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv
Original: 225,745 | Valid: 225,745 | Invalid labels: 0 | Time: 7.4 seconds

[2/8] Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv
Original: 286,467 | Valid: 286,467 | Invalid labels: 0 | Time: 6.2 seconds

[3/8] Friday-WorkingHours-Morning.pcap_ISCX.csv
Original: 191,033 | Valid: 191,033 | Invalid labels: 0 | Time: 5.8 seconds

[4/8] Monday-WorkingHours.pcap_ISCX.csv
Original: 529,918 | Valid: 529,918 | Invalid labels: 0 | Time: 14.0 seconds

[5/8] Thursday-WorkingHours-Afternoon-Infilteration.pcap_ISCX.csv
Original: 288,602 | Valid: 288,602 | Invalid labels: 0 | Time: 6.3 seconds

[6/8] Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX.csv
Original: 170,366 | Valid: 170,366 | Invalid labels: 0 | Time: 3.9 seconds

[7/8] Tuesday-WorkingHours.pcap_ISCX.csv
Original: 445,909 | Valid: 445,909 | Invalid labels: 0 | Time: 11.5 seconds

[8/8] Wednesday-workingHours.pcap_ISCX.csv
Original: 692,703 | Valid: 692,703 | Invalid labels: 0 | Time: 17.3 seconds


Summary
Original rows: 2,830,743
Invalid-label rows: 0
Valid rows: 2,830,743
Features containing issues: 2

Features with detected issues:

,missing,nonnumeric,positive_infinity,negative_infinity,total_issues
Flow Packets/s,0,0,2867,0,2867
Flow Bytes/s,1358,0,1509,0,2867

In [ ]:
quality_2018 = audit_predictors(
    files_2018,
    "2018"
)

Auditing predictors: 2018
======================================================================
[1/10] Friday-02-03-2018_TrafficForML_CICFlowMeter.csv
Original: 1,048,575 | Valid: 1,048,575 | Invalid labels: 0 | Time: 29.7 seconds

[2/10] Friday-16-02-2018_TrafficForML_CICFlowMeter.csv
Original: 1,048,575 | Valid: 1,048,574 | Invalid labels: 1 | Time: 38.9 seconds

[3/10] Friday-23-02-2018_TrafficForML_CICFlowMeter.csv
Original: 1,048,575 | Valid: 1,048,575 | Invalid labels: 0 | Time: 30.7 seconds

[4/10] Thuesday-20-02-2018_TrafficForML_CICFlowMeter.csv
Original: 7,948,748 | Valid: 7,948,748 | Invalid labels: 0 | Time: 290.1 seconds

[5/10] Thursday-01-03-2018_TrafficForML_CICFlowMeter.csv
Original: 331,125 | Valid: 331,100 | Invalid labels: 25 | Time: 17.9 seconds

[6/10] Thursday-15-02-2018_TrafficForML_CICFlowMeter.csv
Original: 1,048,575 | Valid: 1,048,575 | Invalid labels: 0 | Time: 26.8 seconds

[7/10] Thursday-22-02-2018_TrafficForML_CICFlowMeter.csv
Original: 1,048,575 | Valid: 1,048,575 | Invalid labels: 0 | Time: 25.2 seconds

[8/10] Wednesday-14-02-2018_TrafficForML_CICFlowMeter.csv
Original: 1,048,575 | Valid: 1,048,575 | Invalid labels: 0 | Time: 26.3 seconds

[9/10] Wednesday-21-02-2018_TrafficForML_CICFlowMeter.csv
Original: 1,048,575 | Valid: 1,048,575 | Invalid labels: 0 | Time: 24.8 seconds

[10/10] Wednesday-28-02-2018_TrafficForML_CICFlowMeter.csv
Original: 613,104 | Valid: 613,071 | Invalid labels: 33 | Time: 62.3 seconds


Summary
Original rows: 16,233,002
Invalid-label rows: 59
Valid rows: 16,232,943
Features containing issues: 2

Features with detected issues:

,missing,nonnumeric,positive_infinity,negative_infinity,total_issues
Flow Packets/s,0,0,95760,0,95760
Flow Bytes/s,59721,0,36039,0,95760

In [ ]:
from collections import Counter
import pandas as pd
import numpy as np

def audit_invalid_rate_labels(files, dataset, chunksize=250_000):
    affected_labels = Counter()
    valid_rows = 0
    affected_rows = 0

    for number, file in enumerate(files, start=1):
        raw_header = pd.read_csv(file, nrows=0).columns.tolist()
        header_lookup = {
            str(column).strip(): column
            for column in raw_header
        }

        if dataset == "2017":
            byte_column = header_lookup["Flow Bytes/s"]
            packet_column = header_lookup["Flow Packets/s"]
        else:
            byte_column = header_lookup["Flow Byts/s"]
            packet_column = header_lookup["Flow Pkts/s"]

        label_column = header_lookup["Label"]

        for chunk in pd.read_csv(
            file,
            usecols=[byte_column, packet_column, label_column],
            chunksize=chunksize,
            low_memory=False
        ):
            labels = (
                chunk[label_column]
                .astype(str)
                .str.strip()
            )

            valid_label = ~labels.str.lower().isin(
                ["label", "", "nan"]
            )

            flow_bytes = pd.to_numeric(
                chunk[byte_column],
                errors="coerce"
            )

            flow_packets = pd.to_numeric(
                chunk[packet_column],
                errors="coerce"
            )

            affected = valid_label & (
                ~np.isfinite(flow_bytes) |
                ~np.isfinite(flow_packets)
            )

            valid_rows += int(valid_label.sum())
            affected_rows += int(affected.sum())
            affected_labels.update(labels[affected])

        print(f"[{number}/{len(files)}] {file.name}")

    benign_affected = sum(
        count for label, count in affected_labels.items()
        if label.lower() == "benign"
    )

    attack_affected = affected_rows - benign_affected

    print(f"\nDataset: {dataset}")
    print(f"Valid rows: {valid_rows:,}")
    print(f"Affected rows: {affected_rows:,}")
    print(f"Affected percentage: {affected_rows / valid_rows * 100:.4f}%")
    print(f"Affected benign: {benign_affected:,}")
    print(f"Affected attacks: {attack_affected:,}")

    print("\nAffected rows by original label:")
    for label, count in affected_labels.most_common():
        print(f"{label}: {count:,}")

    return affected_labels

In [ ]:
affected_2017 = audit_invalid_rate_labels(
    files_2017, "2017"
)

[1/8] Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv
[2/8] Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv
[3/8] Friday-WorkingHours-Morning.pcap_ISCX.csv
[4/8] Monday-WorkingHours.pcap_ISCX.csv
[5/8] Thursday-WorkingHours-Afternoon-Infilteration.pcap_ISCX.csv
[6/8] Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX.csv
[7/8] Tuesday-WorkingHours.pcap_ISCX.csv
[8/8] Wednesday-workingHours.pcap_ISCX.csv

Dataset: 2017
Valid rows: 2,830,743
Affected rows: 2,867
Affected percentage: 0.1013%
Affected benign: 1,777
Affected attacks: 1,090

Affected rows by original label:
BENIGN: 1,777
DoS Hulk: 949
PortScan: 126
Bot: 10
FTP-Patator: 3
DDoS: 2

In [ ]:
affected_2018 = audit_invalid_rate_labels(
    files_2018, "2018"
)

[1/10] Friday-02-03-2018_TrafficForML_CICFlowMeter.csv
[2/10] Friday-16-02-2018_TrafficForML_CICFlowMeter.csv
[3/10] Friday-23-02-2018_TrafficForML_CICFlowMeter.csv
[4/10] Thuesday-20-02-2018_TrafficForML_CICFlowMeter.csv
[5/10] Thursday-01-03-2018_TrafficForML_CICFlowMeter.csv
[6/10] Thursday-15-02-2018_TrafficForML_CICFlowMeter.csv
[7/10] Thursday-22-02-2018_TrafficForML_CICFlowMeter.csv
[8/10] Wednesday-14-02-2018_TrafficForML_CICFlowMeter.csv
[9/10] Wednesday-21-02-2018_TrafficForML_CICFlowMeter.csv
[10/10] Wednesday-28-02-2018_TrafficForML_CICFlowMeter.csv

Dataset: 2018
Valid rows: 16,232,943
Affected rows: 95,760
Affected percentage: 0.5899%
Affected benign: 94,459
Affected attacks: 1,301

Affected rows by original label:
Benign: 94,459
Infilteration: 1,295
FTP-BruteForce: 6

In [ ]:
import pandas as pd
import numpy as np

def clean_chunk(chunk, dataset):
    chunk = standardize_chunk(chunk, dataset)

    labels = (
        chunk["Label"]
        .astype(str)
        .str.strip()
    )

    valid_label = ~labels.str.lower().isin(
        ["label", "", "nan"]
    )

    chunk = chunk.loc[valid_label].copy()
    labels = labels.loc[valid_label]

    # Binary target
    chunk["target"] = (
        labels.str.lower() != "benign"
    ).astype("int8")

    # Convert all predictors to numeric
    chunk[predictor_columns] = chunk[
        predictor_columns
    ].apply(pd.to_numeric, errors="coerce")

    # Undefined rates become missing—not zero
    chunk[predictor_columns] = chunk[
        predictor_columns
    ].replace([np.inf, -np.inf], np.nan)

    return chunk[predictor_columns + ["target"]]

In [ ]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy="median")

X_train_imputed = imputer.fit_transform(X_train)

X_validation_imputed = imputer.transform(X_validation)
X_calibration_imputed = imputer.transform(X_calibration)
X_source_test_imputed = imputer.transform(X_source_test)
X_target_imputed = imputer.transform(X_target)

NameError: name 'X_train' is not defined

In [ ]:
import pandas as pd
import numpy as np
import time

def create_uniform_sample(
    files,
    dataset,
    valid_population,
    desired_rows=1_000_000,
    seed=2026,
    chunksize=100_000
):
    sampling_probability = min(
        1.0,
        desired_rows / valid_population
    )

    rng = np.random.default_rng(seed)
    samples = []

    print(f"\nSampling {dataset}")
    print("Sampling probability:", sampling_probability)

    for file_number, file in enumerate(files, start=1):
        start = time.time()
        selected_from_file = 0

        for raw_chunk in pd.read_csv(
            file,
            chunksize=chunksize,
            low_memory=False,
            encoding_errors="replace"
        ):
            cleaned = clean_chunk(raw_chunk, dataset)

            selection = (
                rng.random(len(cleaned))
                < sampling_probability
            )

            selected = cleaned.loc[selection].copy()

            selected[predictor_columns] = selected[
                predictor_columns
            ].astype("float32")

            selected["target"] = selected[
                "target"
            ].astype("int8")

            samples.append(selected)
            selected_from_file += len(selected)

        print(
            f"[{file_number}/{len(files)}] {file.name} | "
            f"Selected: {selected_from_file:,} | "
            f"Time: {time.time() - start:.1f}s"
        )

    sample = pd.concat(
        samples,
        ignore_index=True
    )

    del samples

    print("\nFinal sampled rows:", f"{len(sample):,}")
    print("Benign:", f"{(sample['target'] == 0).sum():,}")
    print("Attack:", f"{(sample['target'] == 1).sum():,}")
    print(
        "Attack rate:",
        f"{sample['target'].mean() * 100:.2f}%"
    )

    return sample

In [ ]:
source_sample = create_uniform_sample(
    files=files_2017,
    dataset="2017",
    valid_population=2_830_743,
    desired_rows=1_000_000,
    seed=2026
)

Sampling 2017
Sampling probability: 0.3532641430182818
[1/8] Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv | Selected: 80,331 | Time: 8.4s
[2/8] Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv | Selected: 101,346 | Time: 7.5s
[3/8] Friday-WorkingHours-Morning.pcap_ISCX.csv | Selected: 67,081 | Time: 5.3s
[4/8] Monday-WorkingHours.pcap_ISCX.csv | Selected: 187,132 | Time: 14.2s
[5/8] Thursday-WorkingHours-Afternoon-Infilteration.pcap_ISCX.csv | Selected: 102,064 | Time: 7.7s
[6/8] Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX.csv | Selected: 60,012 | Time: 3.9s
[7/8] Tuesday-WorkingHours.pcap_ISCX.csv | Selected: 157,021 | Time: 11.5s
[8/8] Wednesday-workingHours.pcap_ISCX.csv | Selected: 245,282 | Time: 17.8s

Final sampled rows: 1,000,269
Benign: 802,974
Attack: 197,295
Attack rate: 19.72%

In [ ]:
target_sample = create_uniform_sample(
    files=files_2018,
    dataset="2018",
    valid_population=16_232_943,
    desired_rows=1_000_000,
    seed=2027
)

Sampling 2018
Sampling probability: 0.06160312396834018
[1/10] Friday-02-03-2018_TrafficForML_CICFlowMeter.csv | Selected: 64,369 | Time: 31.2s
[2/10] Friday-16-02-2018_TrafficForML_CICFlowMeter.csv | Selected: 64,318 | Time: 35.7s
[3/10] Friday-23-02-2018_TrafficForML_CICFlowMeter.csv | Selected: 64,419 | Time: 31.3s
[4/10] Thuesday-20-02-2018_TrafficForML_CICFlowMeter.csv | Selected: 489,403 | Time: 290.3s
[5/10] Thursday-01-03-2018_TrafficForML_CICFlowMeter.csv | Selected: 20,387 | Time: 27.3s
[6/10] Thursday-15-02-2018_TrafficForML_CICFlowMeter.csv | Selected: 64,967 | Time: 31.9s
[7/10] Thursday-22-02-2018_TrafficForML_CICFlowMeter.csv | Selected: 64,530 | Time: 30.7s
[8/10] Wednesday-14-02-2018_TrafficForML_CICFlowMeter.csv | Selected: 64,605 | Time: 28.4s
[9/10] Wednesday-21-02-2018_TrafficForML_CICFlowMeter.csv | Selected: 64,382 | Time: 26.4s
[10/10] Wednesday-28-02-2018_TrafficForML_CICFlowMeter.csv | Selected: 37,763 | Time: 60.5s

Final sampled rows: 999,143
Benign: 830,073
Attack: 169,070
Attack rate: 16.92%

In [ ]:
feature_hash = pd.util.hash_pandas_object(
    source_sample[predictor_columns],
    index=False
).to_numpy(dtype="uint64")

split_bucket = feature_hash % 100

train_df = source_sample.loc[split_bucket < 60].copy()

validation_df = source_sample.loc[
    (split_bucket >= 60) &
    (split_bucket < 75)
].copy()

calibration_df = source_sample.loc[
    (split_bucket >= 75) &
    (split_bucket < 85)
].copy()

source_test_df = source_sample.loc[
    split_bucket >= 85
].copy()

In [ ]:
def show_partition(name, dataframe):
    print(
        f"{name}: {len(dataframe):,} rows | "
        f"Attack rate: {dataframe['target'].mean() * 100:.2f}%"
    )

show_partition("Training", train_df)
show_partition("Validation", validation_df)
show_partition("Calibration", calibration_df)
show_partition("Source test", source_test_df)
show_partition("Target test", target_sample)

Training: 598,043 rows | Attack rate: 19.50%
Validation: 152,964 rows | Attack rate: 20.93%
Calibration: 99,084 rows | Attack rate: 18.32%
Source test: 150,178 rows | Attack rate: 20.33%
Target test: 999,143 rows | Attack rate: 16.92%

In [ ]:
X_train = train_df[predictor_columns]
y_train = train_df["target"]

X_validation = validation_df[predictor_columns]
y_validation = validation_df["target"]

X_calibration = calibration_df[predictor_columns]
y_calibration = calibration_df["target"]

X_source_test = source_test_df[predictor_columns]
y_source_test = source_test_df["target"]

X_target = target_sample[predictor_columns]
y_target = target_sample["target"]

In [ ]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy="median")

X_train_imputed = imputer.fit_transform(X_train)

X_validation_imputed = imputer.transform(X_validation)
X_calibration_imputed = imputer.transform(X_calibration)
X_source_test_imputed = imputer.transform(X_source_test)
X_target_imputed = imputer.transform(X_target)

print("Training shape:", X_train_imputed.shape)
print("Validation shape:", X_validation_imputed.shape)
print("Calibration shape:", X_calibration_imputed.shape)
print("Source-test shape:", X_source_test_imputed.shape)
print("Target-test shape:", X_target_imputed.shape)

print(
    "Remaining missing values:",
    np.isnan(X_train_imputed).sum()
    + np.isnan(X_validation_imputed).sum()
    + np.isnan(X_calibration_imputed).sum()
    + np.isnan(X_source_test_imputed).sum()
    + np.isnan(X_target_imputed).sum()
)

Training shape: (598043, 77)
Validation shape: (152964, 77)
Calibration shape: (99084, 77)
Source-test shape: (150178, 77)
Target-test shape: (999143, 77)
Remaining missing values: 0

In [ ]:
from pathlib import Path
import joblib
import json

checkpoint_dir = Path(
    "/content/drive/MyDrive/research/researchdata/NIDS_Research/NIDS_Research_Checkpoints"
)
checkpoint_dir.mkdir(parents=True, exist_ok=True)

# Save source partitions before imputation
train_df.to_parquet(
    checkpoint_dir / "source_train.parquet",
    compression="zstd",
    index=False
)

validation_df.to_parquet(
    checkpoint_dir / "source_validation.parquet",
    compression="zstd",
    index=False
)

calibration_df.to_parquet(
    checkpoint_dir / "source_calibration.parquet",
    compression="zstd",
    index=False
)

source_test_df.to_parquet(
    checkpoint_dir / "source_test.parquet",
    compression="zstd",
    index=False
)

# Target labels must remain unused until final evaluation
target_sample.to_parquet(
    checkpoint_dir / "target_test_sealed.parquet",
    compression="zstd",
    index=False
)

# Save source-trained imputer
joblib.dump(
    imputer,
    checkpoint_dir / "source_median_imputer.joblib"
)

metadata = {
    "source_dataset": "CICIDS2017",
    "target_dataset": "CSE-CIC-IDS2018",
    "source_sampling_seed": 2026,
    "target_sampling_seed": 2027,
    "predictor_count": len(predictor_columns),
    "predictors": predictor_columns,
    "semantic_groups": semantic_groups,
    "partition_rows": {
        "training": len(train_df),
        "validation": len(validation_df),
        "calibration": len(calibration_df),
        "source_test": len(source_test_df),
        "target_test": len(target_sample)
    }
}

with open(
    checkpoint_dir / "experiment_metadata.json",
    "w"
) as file:
    json.dump(metadata, file, indent=2)

print("Checkpoint saved:", checkpoint_dir)

for file in checkpoint_dir.iterdir():
    size_mb = file.stat().st_size / (1024 ** 2)
    print(f"{file.name}: {size_mb:.2f} MiB")

Checkpoint saved: /content/drive/MyDrive/research/researchdata/NIDS_Research/NIDS_Research_Checkpoints
source_train.parquet: 49.08 MiB
source_validation.parquet: 12.98 MiB
source_calibration.parquet: 8.65 MiB
source_test.parquet: 12.83 MiB
target_test_sealed.parquet: 82.33 MiB
source_median_imputer.joblib: 0.00 MiB
experiment_metadata.json: 0.00 MiB

Next, train the complete-feature source baseline. The target dataset must remain sealed.

1. Train XGBoost

In [ ]:
import xgboost as xgb
import torch
import time

device = "cuda" if torch.cuda.is_available() else "cpu"

print("XGBoost version:", xgb.__version__)
print("Training device:", device)

baseline_model = xgb.XGBClassifier(
    objective="binary:logistic",
    n_estimators=1200,
    learning_rate=0.05,
    max_depth=6,
    min_child_weight=5,
    subsample=0.80,
    colsample_bytree=0.80,
    reg_alpha=0.01,
    reg_lambda=1.0,
    tree_method="hist",
    device=device,
    eval_metric="logloss",
    early_stopping_rounds=50,
    random_state=2026,
    n_jobs=-1
)

start_time = time.time()

baseline_model.fit(
    X_train_imputed,
    y_train,
    eval_set=[
        (X_validation_imputed, y_validation)
    ],
    verbose=50
)

training_time = time.time() - start_time

print("\nTraining completed")
print("Training time:", round(training_time, 2), "seconds")
print("Best iteration:", baseline_model.best_iteration)
print("Best validation score:", baseline_model.best_score)

XGBoost version: 3.3.0
Training device: cpu
[0]	validation_0-logloss:0.47198
[50]	validation_0-logloss:0.04195
[100]	validation_0-logloss:0.01422
[150]	validation_0-logloss:0.00766
[200]	validation_0-logloss:0.00461
[250]	validation_0-logloss:0.00357
[300]	validation_0-logloss:0.00300
[350]	validation_0-logloss:0.00272
[400]	validation_0-logloss:0.00257
[450]	validation_0-logloss:0.00248
[500]	validation_0-logloss:0.00241
[550]	validation_0-logloss:0.00236
[600]	validation_0-logloss:0.00233
[650]	validation_0-logloss:0.00230
[700]	validation_0-logloss:0.00228
[750]	validation_0-logloss:0.00226
[800]	validation_0-logloss:0.00224
[850]	validation_0-logloss:0.00223
[900]	validation_0-logloss:0.00222
[950]	validation_0-logloss:0.00222
[1000]	validation_0-logloss:0.00221
[1050]	validation_0-logloss:0.00221
[1100]	validation_0-logloss:0.00220
[1150]	validation_0-logloss:0.00221
[1158]	validation_0-logloss:0.00221

Training completed
Training time: 268.31 seconds
Best iteration: 1108
Best validation score: 0.00220237771351473

2. Select the classification threshold using validation only

In [ ]:
import numpy as np
from sklearn.metrics import precision_recall_curve

validation_probability = baseline_model.predict_proba(
    X_validation_imputed
)[:, 1]

precision_values, recall_values, thresholds = (
    precision_recall_curve(
        y_validation,
        validation_probability
    )
)

f1_values = (
    2 * precision_values[:-1] * recall_values[:-1]
    / (
        precision_values[:-1]
        + recall_values[:-1]
        + 1e-12
    )
)

best_position = np.argmax(f1_values)
selected_threshold = float(thresholds[best_position])

print("Selected threshold:", selected_threshold)
print("Validation F1:", f1_values[best_position])

Selected threshold: 0.5136529207229614
Validation F1: 0.9985956371121298

3. Evaluate validation and source-test partitions

In [ ]:
from sklearn.metrics import (
    accuracy_score,
    balanced_accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    average_precision_score,
    matthews_corrcoef,
    confusion_matrix
)
import pandas as pd

def evaluate_binary_model(model, X, y, threshold):
    probability = model.predict_proba(X)[:, 1]
    prediction = (probability >= threshold).astype("int8")

    tn, fp, fn, tp = confusion_matrix(
        y,
        prediction,
        labels=[0, 1]
    ).ravel()

    return {
        "rows": len(y),
        "accuracy": accuracy_score(y, prediction),
        "balanced_accuracy": balanced_accuracy_score(y, prediction),
        "precision": precision_score(
            y, prediction, zero_division=0
        ),
        "recall": recall_score(
            y, prediction, zero_division=0
        ),
        "f1": f1_score(
            y, prediction, zero_division=0
        ),
        "roc_auc": roc_auc_score(y, probability),
        "pr_auc": average_precision_score(y, probability),
        "mcc": matthews_corrcoef(y, prediction),
        "false_positive_rate": fp / (fp + tn),
        "false_negative_rate": fn / (fn + tp),
        "tn": int(tn),
        "fp": int(fp),
        "fn": int(fn),
        "tp": int(tp)
    }

baseline_results = pd.DataFrame({
    "Validation": evaluate_binary_model(
        baseline_model,
        X_validation_imputed,
        y_validation,
        selected_threshold
    ),
    "Source_Test": evaluate_binary_model(
        baseline_model,
        X_source_test_imputed,
        y_source_test,
        selected_threshold
    )
}).T

display(
    baseline_results.round(6)
)

,rows,accuracy,balanced_accuracy,precision,recall,f1,roc_auc,pr_auc,mcc,false_positive_rate,false_negative_rate,tn,fp,fn,tp
Validation,152964.0,0.999412,0.999364,0.99791,0.999282,0.998596,0.999988,0.999954,0.998224,0.000554,0.000718,120876.0,67.0,23.0,31998.0
Source_Test,150178.0,0.999221,0.999121,0.99722,0.998952,0.998085,0.999976,0.999903,0.997597,0.000710,0.001048,119567.0,85.0,32.0,30494.0

4. Save the baseline

In [ ]:
baseline_model.save_model(
    checkpoint_dir / "complete_feature_baseline_xgboost.json"
)

with open(
    checkpoint_dir / "baseline_threshold.json",
    "w"
) as file:
    json.dump(
        {
            "selected_threshold": selected_threshold,
            "selection_partition": "source_validation",
            "selection_metric": "F1",
            "best_iteration": int(
                baseline_model.best_iteration
            ),
            "training_time_seconds": training_time
        },
        file,
        indent=2
    )

baseline_results.to_csv(
    checkpoint_dir / "baseline_source_results.csv"
)

print("Baseline model and results saved.")

Baseline model and results saved.

The baseline is behaving normally and is extremely strong in-domain:

Source-test F1: 99.81%
Recall: 99.90%
Precision: 99.72%
False-positive rate: 0.071%
False-negative rate: 0.105%

However, this does not prove generalization or novelty. CICIDS2017 often produces very high within-dataset results. The important question is whether performance survives structured feature-group loss and cross-dataset shift.

Next, stress-test the baseline on the source test set without touching the target dataset.

In [ ]:
from itertools import combinations
import pandas as pd
import numpy as np
import time

feature_index = {
    feature: position
    for position, feature in enumerate(predictor_columns)
}

group_indices = {
    group: [
        feature_index[feature]
        for feature in features
    ]
    for group, features in semantic_groups.items()
}

training_medians = np.asarray(
    imputer.statistics_,
    dtype=np.float32
)

Create masked versions:

In [ ]:
def apply_group_loss(
    X,
    missing_groups,
    replacement
):
    X_masked = np.array(
        X,
        dtype=np.float32,
        copy=True
    )

    columns_to_mask = []

    for group in missing_groups:
        columns_to_mask.extend(
            group_indices[group]
        )

    columns_to_mask = sorted(
        set(columns_to_mask)
    )

    if replacement == "zero":
        X_masked[:, columns_to_mask] = 0.0

    elif replacement == "median":
        X_masked[:, columns_to_mask] = (
            training_medians[columns_to_mask]
        )

    else:
        raise ValueError(
            "Replacement must be zero or median."
        )

    return X_masked

Run complete, single-group and unseen pairwise-group tests:

In [ ]:
stress_results = []

# Complete-feature reference
complete_result = evaluate_binary_model(
    baseline_model,
    X_source_test_imputed,
    y_source_test,
    selected_threshold
)

complete_result.update({
    "scenario": "Complete",
    "loss_type": "none",
    "missing_groups": "None",
    "replacement": "none",
    "features_removed": 0
})

stress_results.append(complete_result)

group_names = list(semantic_groups.keys())

scenarios = []

# Single-group loss
for group in group_names:
    scenarios.append(
        ("single", (group,))
    )

# Pairwise feature-group loss
for pair in combinations(group_names, 2):
    scenarios.append(
        ("pairwise_unseen", pair)
    )

for loss_type, missing_groups in scenarios:
    number_removed = sum(
        len(semantic_groups[group])
        for group in missing_groups
    )

    for replacement in ["zero", "median"]:
        start = time.time()

        X_masked = apply_group_loss(
            X_source_test_imputed,
            missing_groups,
            replacement
        )

        result = evaluate_binary_model(
            baseline_model,
            X_masked,
            y_source_test,
            selected_threshold
        )

        result.update({
            "scenario": "+".join(missing_groups),
            "loss_type": loss_type,
            "missing_groups": "+".join(missing_groups),
            "replacement": replacement,
            "features_removed": number_removed
        })

        stress_results.append(result)

        print(
            loss_type,
            "|",
            "+".join(missing_groups),
            "|",
            replacement,
            "| F1:",
            round(result["f1"], 4),
            "| Time:",
            round(time.time() - start, 1),
            "seconds"
        )

        del X_masked

single | G1_Packet_Byte_Magnitude | zero | F1: 0.74 | Time: 5.8 seconds
single | G1_Packet_Byte_Magnitude | median | F1: 0.5969 | Time: 3.7 seconds
single | G2_Temporal_Activity | zero | F1: 0.9838 | Time: 4.4 seconds
single | G2_Temporal_Activity | median | F1: 0.9443 | Time: 5.7 seconds
single | G3_TCP_Control_Flags | zero | F1: 0.9963 | Time: 3.7 seconds
single | G3_TCP_Control_Flags | median | F1: 0.9963 | Time: 3.7 seconds
single | G4_Rate_Header_Flow_Context | zero | F1: 0.607 | Time: 5.6 seconds
single | G4_Rate_Header_Flow_Context | median | F1: 0.7915 | Time: 4.5 seconds
pairwise_unseen | G1_Packet_Byte_Magnitude+G2_Temporal_Activity | zero | F1: 0.6774 | Time: 3.7 seconds
pairwise_unseen | G1_Packet_Byte_Magnitude+G2_Temporal_Activity | median | F1: 0.4985 | Time: 3.9 seconds
pairwise_unseen | G1_Packet_Byte_Magnitude+G3_TCP_Control_Flags | zero | F1: 0.7197 | Time: 6.4 seconds
pairwise_unseen | G1_Packet_Byte_Magnitude+G3_TCP_Control_Flags | median | F1: 0.5692 | Time: 4.4 seconds
pairwise_unseen | G1_Packet_Byte_Magnitude+G4_Rate_Header_Flow_Context | zero | F1: 0.0083 | Time: 3.7 seconds
pairwise_unseen | G1_Packet_Byte_Magnitude+G4_Rate_Header_Flow_Context | median | F1: 0.1096 | Time: 5.1 seconds
pairwise_unseen | G2_Temporal_Activity+G3_TCP_Control_Flags | zero | F1: 0.9857 | Time: 5.1 seconds
pairwise_unseen | G2_Temporal_Activity+G3_TCP_Control_Flags | median | F1: 0.9028 | Time: 3.9 seconds
pairwise_unseen | G2_Temporal_Activity+G4_Rate_Header_Flow_Context | zero | F1: 0.5076 | Time: 3.7 seconds
pairwise_unseen | G2_Temporal_Activity+G4_Rate_Header_Flow_Context | median | F1: 0.8101 | Time: 6.2 seconds
pairwise_unseen | G3_TCP_Control_Flags+G4_Rate_Header_Flow_Context | zero | F1: 0.6095 | Time: 4.0 seconds
pairwise_unseen | G3_TCP_Control_Flags+G4_Rate_Header_Flow_Context | median | F1: 0.7958 | Time: 3.8 seconds

Create and save the results table:

In [ ]:
baseline_stress_results = pd.DataFrame(
    stress_results
)

display_columns = [
    "loss_type",
    "missing_groups",
    "replacement",
    "features_removed",
    "accuracy",
    "precision",
    "recall",
    "f1",
    "false_positive_rate",
    "false_negative_rate",
    "roc_auc",
    "pr_auc"
]

display(
    baseline_stress_results[
        display_columns
    ].round(6)
)

baseline_stress_results.to_csv(
    checkpoint_dir /
    "baseline_source_feature_group_stress.csv",
    index=False
)

print("Stress-test results saved.")

,loss_type,missing_groups,replacement,features_removed,accuracy,precision,recall,f1,false_positive_rate,false_negative_rate,roc_auc,pr_auc
0,none,None,none,0,0.999221,0.997220,0.998952,0.998085,0.000710,0.001048,0.999976,0.999903
1,single,G1_Packet_Byte_Magnitude,zero,32,0.916106,0.999610,0.587499,0.740050,0.000059,0.412501,0.988412,0.957847
2,single,G1_Packet_Byte_Magnitude,median,32,0.883179,0.999461,0.425506,0.596894,0.000059,0.574494,0.996083,0.984330
3,single,G2_Temporal_Activity,zero,23,0.993335,0.971841,0.996069,0.983806,0.007363,0.003931,0.999660,0.998600
4,single,G2_Temporal_Activity,median,23,0.978292,0.986858,0.905261,0.944300,0.003076,0.094739,0.999401,0.997517
5,single,G3_TCP_Control_Flags,zero,12,0.998482,0.997733,0.994791,0.996260,0.000577,0.005209,0.999968,0.999868
6,single,G3_TCP_Control_Flags,median,12,0.998482,0.997733,0.994791,0.996260,0.000577,0.005209,0.999968,0.999868
7,single,G4_Rate_Header_Flow_Context,zero,10,0.871193,0.799144,0.489288,0.606957,0.031374,0.510712,0.920621,0.773401
8,single,G4_Rate_Header_Flow_Context,median,10,0.894325,0.660786,0.986569,0.791464,0.129208,0.013431,0.981266,0.925612
9,pairwise_unseen,G1_Packet_Byte_Magnitude+G2_Temporal_Activity,zero,55,0.900212,0.987881,0.515397,0.677387,0.001613,0.484603,0.973589,0.912743
10,pairwise_unseen,G1_Packet_Byte_Magnitude+G2_Temporal_Activity,median,55,0.864101,0.997443,0.332274,0.498489,0.000217,0.667726,0.962948,0.881221
11,pairwise_unseen,G1_Packet_Byte_Magnitude+G3_TCP_Control_Flags,zero,44,0.910979,0.999825,0.562144,0.719663,0.000025,0.437856,0.975618,0.927291
12,pairwise_unseen,G1_Packet_Byte_Magnitude+G3_TCP_Control_Flags,median,44,0.877579,0.999589,0.397890,0.569206,0.000042,0.602110,0.992321,0.971825
13,pairwise_unseen,G1_Packet_Byte_Magnitude+G4_Rate_Header_Flow_C...,zero,42,0.797454,0.869863,0.004160,0.008281,0.000159,0.995840,0.779703,0.438441
14,pairwise_unseen,G1_Packet_Byte_Magnitude+G4_Rate_Header_Flow_C...,median,42,0.805491,0.788251,0.058901,0.109611,0.004037,0.941099,0.861773,0.596988
15,pairwise_unseen,G2_Temporal_Activity+G3_TCP_Control_Flags,zero,35,0.994154,0.980207,0.991253,0.985699,0.005106,0.008747,0.999518,0.997973
16,pairwise_unseen,G2_Temporal_Activity+G3_TCP_Control_Flags,median,35,0.963650,0.988578,0.830767,0.902828,0.002449,0.169233,0.999269,0.996981
17,pairwise_unseen,G2_Temporal_Activity+G4_Rate_Header_Flow_Context,zero,33,0.854613,0.814654,0.368604,0.507556,0.021395,0.631396,0.910919,0.748850
18,pairwise_unseen,G2_Temporal_Activity+G4_Rate_Header_Flow_Context,median,33,0.907743,0.696504,0.967863,0.810062,0.107595,0.032137,0.980705,0.931041
19,pairwise_unseen,G3_TCP_Control_Flags+G4_Rate_Header_Flow_Context,zero,22,0.874542,0.829656,0.481688,0.609505,0.025232,0.518312,0.916559,0.766784
20,pairwise_unseen,G3_TCP_Control_Flags+G4_Rate_Header_Flow_Context,median,22,0.897462,0.668531,0.982867,0.795783,0.124327,0.017133,0.978726,0.916689

Stress-test results saved.

The stress-test confirms that the research problem is real and significant.

Main findings
Complete-feature baseline: F1 = 0.9981
Losing G1 packet/byte features: F1 falls to 0.5969–0.7401
Losing G4 rate/context features: F1 falls to 0.6070–0.7915
Losing G1 and G4 together is catastrophic:
Zero replacement: F1 = 0.0083, recall only 0.42%
Median replacement: F1 = 0.1096, recall only 5.89%
G3 flag loss causes little degradation because most flag-feature training medians are probably zero.
Results depend strongly on zero versus median replacement.
Accuracy becomes misleading: under G1+G4 zero replacement, accuracy remains 79.75%, while the model misses 99.58% of attacks.

This empirically justifies developing a group-aware selective NIDS. However, it is not yet evidence that the proposed solution works.

Next: train the group-aware model

The model will see:

Complete flows
Single-group loss during training
Four group-availability indicators
Median replacement learned only from source training
No pairwise group loss during training
No target data

In [ ]:
group_names = list(semantic_groups.keys())

availability_names = [
    f"available__{group}"
    for group in group_names
]

group_aware_feature_names = (
    predictor_columns + availability_names
)

print("Group-aware predictors:", len(group_aware_feature_names))

Group-aware predictors: 81

Create complete plus randomly assigned single-group-loss training examples:

In [ ]:
def create_group_aware_training_data(
    X,
    y,
    seed=2026
):
    X = np.asarray(X, dtype=np.float32)
    y = np.asarray(y, dtype=np.int8)

    number_rows = len(X)
    number_groups = len(group_names)

    rng = np.random.default_rng(seed)

    # Every row gets one randomly selected missing group
    assigned_groups = rng.integers(
        0,
        number_groups,
        size=number_rows
    )

    X_masked = X.copy()

    masked_availability = np.ones(
        (number_rows, number_groups),
        dtype=np.float32
    )

    for group_number, group in enumerate(group_names):
        rows = np.where(
            assigned_groups == group_number
        )[0]

        columns = group_indices[group]

        X_masked[np.ix_(rows, columns)] = (
            training_medians[columns]
        )

        masked_availability[
            rows,
            group_number
        ] = 0.0

        print(
            group,
            "masked training rows:",
            f"{len(rows):,}"
        )

    complete_availability = np.ones(
        (number_rows, number_groups),
        dtype=np.float32
    )

    X_complete_augmented = np.hstack([
        X,
        complete_availability
    ])

    X_masked_augmented = np.hstack([
        X_masked,
        masked_availability
    ])

    X_augmented = np.vstack([
        X_complete_augmented,
        X_masked_augmented
    ])

    y_augmented = np.concatenate([
        y,
        y
    ])

    return X_augmented, y_augmented

Create validation data containing complete and all four known single-loss conditions:

In [ ]:
def create_known_condition_validation_data(X, y):
    X = np.asarray(X, dtype=np.float32)
    y = np.asarray(y, dtype=np.int8)

    number_rows = len(X)
    number_groups = len(group_names)

    X_versions = []
    y_versions = []

    # Complete condition
    complete_indicators = np.ones(
        (number_rows, number_groups),
        dtype=np.float32
    )

    X_versions.append(
        np.hstack([X, complete_indicators])
    )
    y_versions.append(y)

    # Four single-group-loss conditions
    for group_number, group in enumerate(group_names):
        X_masked = X.copy()

        columns = group_indices[group]
        X_masked[:, columns] = training_medians[columns]

        indicators = np.ones(
            (number_rows, number_groups),
            dtype=np.float32
        )
        indicators[:, group_number] = 0.0

        X_versions.append(
            np.hstack([X_masked, indicators])
        )
        y_versions.append(y)

    return (
        np.vstack(X_versions),
        np.concatenate(y_versions)
    )

Build the augmented arrays:

In [ ]:
X_train_group_aware, y_train_group_aware = (
    create_group_aware_training_data(
        X_train_imputed,
        y_train,
        seed=2026
    )
)

X_validation_group_aware, y_validation_group_aware = (
    create_known_condition_validation_data(
        X_validation_imputed,
        y_validation
    )
)

print(
    "Augmented training shape:",
    X_train_group_aware.shape
)

print(
    "Known-condition validation shape:",
    X_validation_group_aware.shape
)

G1_Packet_Byte_Magnitude masked training rows: 149,876
G2_Temporal_Activity masked training rows: 149,368
G3_TCP_Control_Flags masked training rows: 149,497
G4_Rate_Header_Flow_Context masked training rows: 149,302
Augmented training shape: (1196086, 81)
Known-condition validation shape: (764820, 81)

Train using the same main hyperparameters as the baseline:

In [ ]:
group_aware_model = xgb.XGBClassifier(
    objective="binary:logistic",
    n_estimators=1200,
    learning_rate=0.05,
    max_depth=6,
    min_child_weight=5,
    subsample=0.80,
    colsample_bytree=0.80,
    reg_alpha=0.01,
    reg_lambda=1.0,
    tree_method="hist",
    device=device,
    eval_metric="logloss",
    early_stopping_rounds=50,
    random_state=2026,
    n_jobs=-1
)

start_time = time.time()

group_aware_model.fit(
    X_train_group_aware,
    y_train_group_aware,
    eval_set=[
        (
            X_validation_group_aware,
            y_validation_group_aware
        )
    ],
    verbose=50
)

group_aware_training_time = (
    time.time() - start_time
)

print("\nTraining completed")
print(
    "Training time:",
    round(group_aware_training_time, 2),
    "seconds"
)
print(
    "Best iteration:",
    group_aware_model.best_iteration
)
print(
    "Best validation logloss:",
    group_aware_model.best_score
)

[0]	validation_0-logloss:0.47884
[50]	validation_0-logloss:0.08127
[100]	validation_0-logloss:0.04448
[150]	validation_0-logloss:0.02980
[200]	validation_0-logloss:0.02392
[250]	validation_0-logloss:0.02056
[300]	validation_0-logloss:0.01930
[350]	validation_0-logloss:0.01917
[372]	validation_0-logloss:0.01890

Training completed
Training time: 215.86 seconds
Best iteration: 322
Best validation logloss: 0.01869023743711215

Training completed successfully. The higher validation log-loss compared with the ordinary baseline is expected because this validation set includes complete data plus four feature-loss conditions. The model stopped at iteration 322, so early stopping worked.

Next, calibrate it using source data only. To avoid using the same rows for both calibration fitting and policy selection, divide the calibration partition into two deterministic halves.
1. Save the model

1. Save the model

In [ ]:
group_aware_model.save_model(
    checkpoint_dir /
    "group_aware_single_mask_xgboost.json"
)

print("Group-aware model saved.")

Group-aware model saved.

2. Divide the source calibration partition

In [ ]:
calibration_hash = pd.util.hash_pandas_object(
    calibration_df[predictor_columns],
    index=False
).to_numpy(dtype="uint64")

calibrator_mask = (
    calibration_hash % 2 == 0
)

policy_mask = ~calibrator_mask

X_calibrator_base = X_calibration_imputed[
    calibrator_mask
]
y_calibrator_base = np.asarray(
    y_calibration
)[calibrator_mask]

X_policy_base = X_calibration_imputed[
    policy_mask
]
y_policy_base = np.asarray(
    y_calibration
)[policy_mask]

print(
    "Calibrator-fit rows:",
    len(y_calibrator_base)
)

print(
    "Policy-selection rows:",
    len(y_policy_base)
)

Calibrator-fit rows: 48889
Policy-selection rows: 50195

3. Add only known conditions
These include complete and single-group losses—not pairwise losses.

In [ ]:
X_calibrator_known, y_calibrator_known = (
    create_known_condition_validation_data(
        X_calibrator_base,
        y_calibrator_base
    )
)

X_policy_known, y_policy_known = (
    create_known_condition_validation_data(
        X_policy_base,
        y_policy_base
    )
)

print(
    "Calibrator known-condition shape:",
    X_calibrator_known.shape
)

print(
    "Policy known-condition shape:",
    X_policy_known.shape
)

Calibrator known-condition shape: (244445, 81)
Policy known-condition shape: (250975, 81)

4. Fit Platt calibration

In [ ]:
from sklearn.linear_model import LogisticRegression

def probability_to_logit(probability):
    probability = np.clip(
        probability,
        1e-7,
        1 - 1e-7
    )

    return np.log(
        probability / (1 - probability)
    ).reshape(-1, 1)


raw_calibrator_probability = (
    group_aware_model.predict_proba(
        X_calibrator_known
    )[:, 1]
)

platt_calibrator = LogisticRegression(
    C=1_000_000,
    solver="lbfgs",
    max_iter=1000,
    random_state=2026
)

platt_calibrator.fit(
    probability_to_logit(
        raw_calibrator_probability
    ),
    y_calibrator_known
)

print(
    "Platt coefficient:",
    platt_calibrator.coef_[0, 0]
)

print(
    "Platt intercept:",
    platt_calibrator.intercept_[0]
)

Platt coefficient: 1.3274914259160584
Platt intercept: -0.15553719369492877

5. Compare raw and calibrated probabilities

In [ ]:
from sklearn.metrics import (
    brier_score_loss,
    log_loss
)

def expected_calibration_error(
    y_true,
    probability,
    bins=15
):
    edges = np.linspace(0, 1, bins + 1)
    total = len(y_true)
    ece = 0.0

    for lower, upper in zip(
        edges[:-1],
        edges[1:]
    ):
        if upper == 1:
            selected = (
                (probability >= lower) &
                (probability <= upper)
            )
        else:
            selected = (
                (probability >= lower) &
                (probability < upper)
            )

        count = selected.sum()

        if count == 0:
            continue

        accuracy = np.mean(
            np.asarray(y_true)[selected]
        )

        confidence = np.mean(
            probability[selected]
        )

        ece += (
            count / total
        ) * abs(accuracy - confidence)

    return ece


raw_policy_probability = (
    group_aware_model.predict_proba(
        X_policy_known
    )[:, 1]
)

calibrated_policy_probability = (
    platt_calibrator.predict_proba(
        probability_to_logit(
            raw_policy_probability
        )
    )[:, 1]
)

calibration_results = pd.DataFrame({
    "Raw": {
        "Brier": brier_score_loss(
            y_policy_known,
            raw_policy_probability
        ),
        "LogLoss": log_loss(
            y_policy_known,
            raw_policy_probability
        ),
        "ECE": expected_calibration_error(
            y_policy_known,
            raw_policy_probability
        )
    },
    "Platt_Calibrated": {
        "Brier": brier_score_loss(
            y_policy_known,
            calibrated_policy_probability
        ),
        "LogLoss": log_loss(
            y_policy_known,
            calibrated_policy_probability
        ),
        "ECE": expected_calibration_error(
            y_policy_known,
            calibrated_policy_probability
        )
    }
}).T

display(calibration_results.round(8))

                     Brier   LogLoss       ECE
Raw               0.002378  0.010733  0.002967
Platt_Calibrated  0.002321  0.009731  0.000891

6. Select the classification threshold

In [ ]:
precision_values, recall_values, thresholds = (
    precision_recall_curve(
        y_policy_known,
        calibrated_policy_probability
    )
)

f1_values = (
    2 * precision_values[:-1] * recall_values[:-1]
    / (
        precision_values[:-1]
        + recall_values[:-1]
        + 1e-12
    )
)

best_position = np.argmax(f1_values)

group_aware_threshold = float(
    thresholds[best_position]
)

print(
    "Group-aware threshold:",
    group_aware_threshold
)

print(
    "Known-condition policy F1:",
    f1_values[best_position]
)

Group-aware threshold: 0.5916309408505653
Known-condition policy F1: 0.9926640843084307

Save the calibrator:

In [ ]:
joblib.dump(
    platt_calibrator,
    checkpoint_dir /
    "group_aware_platt_calibrator.joblib"
)

print("Calibration saved.")

Calibration saved.

To continue the analysis, do not upload all those files.

The two outputs needed now are not yet visible in your folder:

group_aware_calibration_results.csv
group_aware_policy.json

Create them with:

In [ ]:
calibration_results.to_csv(
    checkpoint_dir /
    "group_aware_calibration_results.csv"
)

with open(
    checkpoint_dir /
    "group_aware_policy.json",
    "w"
) as file:
    json.dump(
        {
            "classification_threshold":
                group_aware_threshold,
            "threshold_metric": "F1",
            "threshold_partition":
                "source_policy",
            "calibration_method":
                "Platt scaling",
            "calibration_training_conditions": [
                "complete",
                "G1 single loss",
                "G2 single loss",
                "G3 single loss",
                "G4 single loss"
            ],
            "pairwise_loss_used": False,
            "target_data_used": False
        },
        file,
        indent=2
    )

print("Files saved.")

Files saved.

Calibration is successful:

Metric	Raw	Platt calibrated	Improvement
Brier score	0.002378	0.002321	2.4% lower
Log-loss	0.010733	0.009731	9.3% lower
ECE	0.002967	0.000891	approximately 70% lower

The source-only classification threshold is 0.591631. No pairwise-loss or target data was used, so the experimental separation remains valid.

Now evaluate the genuinely unseen pairwise losses on the source test partition.

1. Create group-aware test conditions

In [ ]:
from itertools import combinations

def create_group_aware_condition(
    X,
    missing_groups
):
    X_condition = np.asarray(
        X,
        dtype=np.float32
    ).copy()

    availability = np.ones(
        (len(X_condition), len(group_names)),
        dtype=np.float32
    )

    for group in missing_groups:
        group_number = group_names.index(group)
        columns = group_indices[group]

        # Source-training medians only
        X_condition[:, columns] = (
            training_medians[columns]
        )

        availability[:, group_number] = 0.0

    return np.hstack([
        X_condition,
        availability
    ])

2. Evaluation function

In [ ]:
from sklearn.metrics import (
    accuracy_score,
    balanced_accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    average_precision_score,
    matthews_corrcoef,
    confusion_matrix,
    brier_score_loss,
    log_loss
)

def evaluate_calibrated_probability(
    y_true,
    probability,
    threshold
):
    y_true = np.asarray(y_true)
    prediction = (
        probability >= threshold
    ).astype("int8")

    tn, fp, fn, tp = confusion_matrix(
        y_true,
        prediction,
        labels=[0, 1]
    ).ravel()

    return {
        "rows": len(y_true),
        "accuracy": accuracy_score(
            y_true, prediction
        ),
        "balanced_accuracy": balanced_accuracy_score(
            y_true, prediction
        ),
        "precision": precision_score(
            y_true, prediction,
            zero_division=0
        ),
        "recall": recall_score(
            y_true, prediction,
            zero_division=0
        ),
        "f1": f1_score(
            y_true, prediction,
            zero_division=0
        ),
        "roc_auc": roc_auc_score(
            y_true, probability
        ),
        "pr_auc": average_precision_score(
            y_true, probability
        ),
        "mcc": matthews_corrcoef(
            y_true, prediction
        ),
        "false_positive_rate": fp / (fp + tn),
        "false_negative_rate": fn / (fn + tp),
        "brier": brier_score_loss(
            y_true, probability
        ),
        "logloss": log_loss(
            y_true, probability
        ),
        "ece": expected_calibration_error(
            y_true, probability
        ),
        "tn": int(tn),
        "fp": int(fp),
        "fn": int(fn),
        "tp": int(tp)
    }

3. Run complete, single and unseen pairwise tests

In [ ]:
group_aware_source_results = []

conditions = [
    ("complete", tuple())
]

conditions.extend([
    ("single", (group,))
    for group in group_names
])

conditions.extend([
    ("pairwise_unseen", pair)
    for pair in combinations(group_names, 2)
])

for condition_type, missing_groups in conditions:
    X_condition = create_group_aware_condition(
        X_source_test_imputed,
        missing_groups
    )

    raw_probability = (
        group_aware_model.predict_proba(
            X_condition
        )[:, 1]
    )

    calibrated_probability = (
        platt_calibrator.predict_proba(
            probability_to_logit(
                raw_probability
            )
        )[:, 1]
    )

    result = evaluate_calibrated_probability(
        y_source_test,
        calibrated_probability,
        group_aware_threshold
    )

    result.update({
        "condition_type": condition_type,
        "missing_groups": (
            "+".join(missing_groups)
            if missing_groups
            else "None"
        ),
        "features_removed": sum(
            len(semantic_groups[group])
            for group in missing_groups
        )
    })

    group_aware_source_results.append(result)

    print(
        condition_type,
        "|",
        result["missing_groups"],
        "| F1:",
        round(result["f1"], 4),
        "| Recall:",
        round(result["recall"], 4),
        "| ECE:",
        round(result["ece"], 5)
    )

    del X_condition

complete | None | F1: 0.998 | Recall: 0.9983 | ECE: 0.00018
single | G1_Packet_Byte_Magnitude | F1: 0.997 | Recall: 0.9973 | ECE: 0.00171
single | G2_Temporal_Activity | F1: 0.9955 | Recall: 0.9939 | ECE: 0.00071
single | G3_TCP_Control_Flags | F1: 0.998 | Recall: 0.9984 | ECE: 0.00033
single | G4_Rate_Header_Flow_Context | F1: 0.9208 | Recall: 0.8617 | ECE: 0.02398
pairwise_unseen | G1_Packet_Byte_Magnitude+G2_Temporal_Activity | F1: 0.99 | Recall: 0.9889 | ECE: 0.01106
pairwise_unseen | G1_Packet_Byte_Magnitude+G3_TCP_Control_Flags | F1: 0.9921 | Recall: 0.9877 | ECE: 0.00547
pairwise_unseen | G1_Packet_Byte_Magnitude+G4_Rate_Header_Flow_Context | F1: 0.6317 | Recall: 0.4764 | ECE: 0.06477
pairwise_unseen | G2_Temporal_Activity+G3_TCP_Control_Flags | F1: 0.9954 | Recall: 0.9936 | ECE: 0.00094
pairwise_unseen | G2_Temporal_Activity+G4_Rate_Header_Flow_Context | F1: 0.8788 | Recall: 0.7899 | ECE: 0.0281
pairwise_unseen | G3_TCP_Control_Flags+G4_Rate_Header_Flow_Context | F1: 0.9194 | Recall: 0.86 | ECE: 0.02528

4. Create and save the results

In [ ]:
group_aware_source_results = pd.DataFrame(
    group_aware_source_results
)

display_columns = [
    "condition_type",
    "missing_groups",
    "features_removed",
    "accuracy",
    "precision",
    "recall",
    "f1",
    "false_positive_rate",
    "false_negative_rate",
    "roc_auc",
    "pr_auc",
    "brier",
    "ece"
]

display(
    group_aware_source_results[
        display_columns
    ].round(6)
)

group_aware_source_results.to_csv(
    checkpoint_dir /
    "group_aware_source_results.csv",
    index=False
)

,condition_type,missing_groups,features_removed,accuracy,precision,recall,f1,false_positive_rate,false_negative_rate,roc_auc,pr_auc,brier,ece
0,complete,None,0,0.999194,0.997741,0.998297,0.998019,0.000577,0.001703,0.999921,0.999665,0.000724,0.000176
1,single,G1_Packet_Byte_Magnitude,32,0.998781,0.996693,0.997314,0.997003,0.000844,0.002686,0.999894,0.999562,0.001053,0.001710
2,single,G2_Temporal_Activity,23,0.998162,0.997042,0.993907,0.995472,0.000752,0.006093,0.999924,0.999675,0.001493,0.000705
3,single,G3_TCP_Control_Flags,12,0.999194,0.997676,0.998362,0.998019,0.000593,0.001638,0.999925,0.999685,0.000750,0.000332
4,single,G4_Rate_Header_Flow_Context,10,0.969869,0.988649,0.861659,0.920796,0.002524,0.138341,0.995961,0.985109,0.026853,0.023985
5,pairwise_unseen,G1_Packet_Byte_Magnitude+G2_Temporal_Activity,55,0.995945,0.991135,0.988895,0.990014,0.002257,0.011105,0.999399,0.997394,0.004488,0.011063
6,pairwise_unseen,G1_Packet_Byte_Magnitude+G3_TCP_Control_Flags,44,0.996804,0.996530,0.987715,0.992103,0.000878,0.012285,0.999921,0.999690,0.001941,0.005465
7,pairwise_unseen,G1_Packet_Byte_Magnitude+G4_Rate_Header_Flow_C...,42,0.887081,0.937113,0.476446,0.631716,0.008157,0.523554,0.911232,0.854893,0.065993,0.064770
8,pairwise_unseen,G2_Temporal_Activity+G3_TCP_Control_Flags,35,0.998122,0.997107,0.993645,0.995373,0.000735,0.006355,0.999921,0.999659,0.001561,0.000936
9,pairwise_unseen,G2_Temporal_Activity+G4_Rate_Header_Flow_Context,33,0.955726,0.990308,0.789917,0.878834,0.001972,0.210083,0.995111,0.977251,0.028769,0.028101
10,pairwise_unseen,G3_TCP_Control_Flags+G4_Rate_Header_Flow_Context,22,0.969370,0.987734,0.859988,0.919445,0.002725,0.140012,0.992420,0.975056,0.027397,0.025276

5. Compare against the ordinary baseline

In [ ]:
baseline_stress_results = pd.read_csv(
    checkpoint_dir /
    "baseline_source_feature_group_stress.csv"
)

baseline_pairwise = (
    baseline_stress_results[
        (baseline_stress_results["loss_type"]
         == "pairwise_unseen")
        &
        (baseline_stress_results["replacement"]
         == "median")
    ][[
        "missing_groups",
        "f1",
        "recall",
        "false_positive_rate"
    ]]
    .rename(columns={
        "f1": "baseline_f1",
        "recall": "baseline_recall",
        "false_positive_rate": "baseline_fpr"
    })
)

aware_pairwise = (
    group_aware_source_results[
        group_aware_source_results[
            "condition_type"
        ] == "pairwise_unseen"
    ][[
        "missing_groups",
        "f1",
        "recall",
        "false_positive_rate",
        "ece"
    ]]
    .rename(columns={
        "f1": "group_aware_f1",
        "recall": "group_aware_recall",
        "false_positive_rate": "group_aware_fpr"
    })
)

pairwise_comparison = baseline_pairwise.merge(
    aware_pairwise,
    on="missing_groups",
    how="inner"
)

pairwise_comparison["f1_improvement"] = (
    pairwise_comparison["group_aware_f1"]
    - pairwise_comparison["baseline_f1"]
)

pairwise_comparison["recall_improvement"] = (
    pairwise_comparison["group_aware_recall"]
    - pairwise_comparison["baseline_recall"]
)

display(pairwise_comparison.round(6))

pairwise_comparison.to_csv(
    checkpoint_dir /
    "pairwise_baseline_vs_group_aware.csv",
    index=False
)

,missing_groups,baseline_f1,baseline_recall,baseline_fpr,group_aware_f1,group_aware_recall,group_aware_fpr,ece,f1_improvement,recall_improvement
0,G1_Packet_Byte_Magnitude+G2_Temporal_Activity,0.498489,0.332274,0.000217,0.990014,0.988895,0.002257,0.011063,0.491525,0.656621
1,G1_Packet_Byte_Magnitude+G3_TCP_Control_Flags,0.569206,0.397890,0.000042,0.992103,0.987715,0.000878,0.005465,0.422897,0.589825
2,G1_Packet_Byte_Magnitude+G4_Rate_Header_Flow_C...,0.109611,0.058901,0.004037,0.631716,0.476446,0.008157,0.064770,0.522105,0.417546
3,G2_Temporal_Activity+G3_TCP_Control_Flags,0.902828,0.830767,0.002449,0.995373,0.993645,0.000735,0.000936,0.092544,0.162878
4,G2_Temporal_Activity+G4_Rate_Header_Flow_Context,0.810062,0.967863,0.107595,0.878834,0.789917,0.001972,0.028101,0.068771,-0.177947
5,G3_TCP_Control_Flags+G4_Rate_Header_Flow_Context,0.795783,0.982867,0.124327,0.919445,0.859988,0.002725,0.025276,0.123662,-0.122879

The group-aware model passed the source-domain robustness test.

Key decision

Across the six unseen pairwise-loss conditions:

Average baseline F1: 0.6143
Average group-aware F1: 0.9012
Average absolute improvement: +0.2869
Group-aware F1 improved in all six conditions.
Complete-data F1 remained virtually unchanged: 0.9980

The strongest improvement is:

G1 + G4:
Baseline F1      = 0.1096
Group-aware F1   = 0.6317
Improvement      = +0.5221

However, G1+G4 remains difficult:

Recall: 47.64%
False-negative rate: 52.36%
ECE: 6.48%

Therefore, the group-aware model alone is insufficient. This result directly supports the selective/abstention part of the proposed method.

Do not unseal the target dataset yet. First fix the source-only abstention policy.

1. Derive confidence cutoffs from known conditions only

In [ ]:
policy_confidence = np.maximum(
    calibrated_policy_probability,
    1 - calibrated_policy_probability
)

desired_coverages = [
    0.80,
    0.90,
    0.95
]

confidence_cutoffs = {
    coverage: float(
        np.quantile(
            policy_confidence,
            1 - coverage
        )
    )
    for coverage in desired_coverages
}

print("Source-only confidence policy:")

for coverage, cutoff in confidence_cutoffs.items():
    print(
        f"Desired coverage {coverage:.0%}: "
        f"confidence cutoff = {cutoff:.6f}"
    )

Source-only confidence policy:
Desired coverage 80%: confidence cutoff = 0.999802
Desired coverage 90%: confidence cutoff = 0.998549
Desired coverage 95%: confidence cutoff = 0.993818

2. Define selective metrics

In [ ]:
def calculate_aurc(
    y_true,
    probability,
    classification_threshold
):
    y_true = np.asarray(y_true)

    prediction = (
        probability >= classification_threshold
    ).astype("int8")

    confidence = np.maximum(
        probability,
        1 - probability
    )

    errors = (
        prediction != y_true
    ).astype("float64")

    order = np.argsort(-confidence)
    ordered_errors = errors[order]

    cumulative_errors = np.cumsum(
        ordered_errors
    )

    coverage_count = np.arange(
        1,
        len(y_true) + 1
    )

    selective_risk = (
        cumulative_errors / coverage_count
    )

    return float(np.mean(selective_risk))


def evaluate_selective_policy(
    y_true,
    probability,
    classification_threshold,
    confidence_cutoff
):
    y_true = np.asarray(y_true)

    prediction = (
        probability >= classification_threshold
    ).astype("int8")

    confidence = np.maximum(
        probability,
        1 - probability
    )

    accepted = (
        confidence >= confidence_cutoff
    )

    accepted_y = y_true[accepted]
    accepted_prediction = prediction[accepted]

    total_attacks = int(
        (y_true == 1).sum()
    )

    abstained_attacks = int(
        ((~accepted) & (y_true == 1)).sum()
    )

    accepted_false_negatives = int(
        (
            accepted &
            (y_true == 1) &
            (prediction == 0)
        ).sum()
    )

    if accepted.sum() == 0:
        return {
            "actual_coverage": 0.0,
            "selective_risk": np.nan,
            "accepted_accuracy": np.nan,
            "accepted_precision": np.nan,
            "accepted_recall": np.nan,
            "accepted_f1": np.nan
        }

    accepted_error = (
        accepted_prediction != accepted_y
    )

    return {
        "actual_coverage": float(
            accepted.mean()
        ),
        "accepted_rows": int(
            accepted.sum()
        ),
        "abstained_rows": int(
            (~accepted).sum()
        ),
        "selective_risk": float(
            accepted_error.mean()
        ),
        "accepted_accuracy": accuracy_score(
            accepted_y,
            accepted_prediction
        ),
        "accepted_precision": precision_score(
            accepted_y,
            accepted_prediction,
            zero_division=0
        ),
        "accepted_recall": recall_score(
            accepted_y,
            accepted_prediction,
            zero_division=0
        ),
        "accepted_f1": f1_score(
            accepted_y,
            accepted_prediction,
            zero_division=0
        ),
        "attack_abstention_rate": (
            abstained_attacks / total_attacks
        ),
        "accepted_false_negative_rate": (
            accepted_false_negatives /
            total_attacks
        )
    }

3. Evaluate unseen pairwise losses

In [ ]:
source_selective_results = []

for missing_groups in combinations(
    group_names,
    2
):
    X_condition = create_group_aware_condition(
        X_source_test_imputed,
        missing_groups
    )

    raw_probability = (
        group_aware_model.predict_proba(
            X_condition
        )[:, 1]
    )

    calibrated_probability = (
        platt_calibrator.predict_proba(
            probability_to_logit(
                raw_probability
            )
        )[:, 1]
    )

    aurc = calculate_aurc(
        y_source_test,
        calibrated_probability,
        group_aware_threshold
    )

    for desired_coverage, cutoff in (
        confidence_cutoffs.items()
    ):
        result = evaluate_selective_policy(
            y_source_test,
            calibrated_probability,
            group_aware_threshold,
            cutoff
        )

        result.update({
            "missing_groups":
                "+".join(missing_groups),
            "desired_policy_coverage":
                desired_coverage,
            "source_confidence_cutoff":
                cutoff,
            "aurc": aurc
        })

        source_selective_results.append(
            result
        )

    del X_condition

4. Save the fixed policy and results

In [ ]:
source_selective_results = pd.DataFrame(
    source_selective_results
)

display(
    source_selective_results.round(6)
)

source_selective_results.to_csv(
    checkpoint_dir /
    "source_selective_pairwise_results.csv",
    index=False
)

selective_policy = {
    "classification_threshold":
        group_aware_threshold,
    "confidence_definition":
        "max(p_attack, 1-p_attack)",
    "confidence_cutoffs": {
        str(coverage): cutoff
        for coverage, cutoff
        in confidence_cutoffs.items()
    },
    "policy_selection_data":
        "source policy partition with complete and single losses",
    "pairwise_loss_used_for_policy":
        False,
    "target_data_used":
        False
}

with open(
    checkpoint_dir /
    "selective_policy.json",
    "w"
) as file:
    json.dump(
        selective_policy,
        file,
        indent=2
    )

print("Selective source results and fixed policy saved.")

,actual_coverage,accepted_rows,abstained_rows,selective_risk,accepted_accuracy,accepted_precision,accepted_recall,accepted_f1,attack_abstention_rate,accepted_false_negative_rate,missing_groups,desired_policy_coverage,source_confidence_cutoff,aurc
0,0.567633,85246.0,64932.0,0.000012,0.999988,0.000000,0.000000,0.000000,0.999967,0.000033,G1_Packet_Byte_Magnitude+G2_Temporal_Activity,0.80,0.999802,0.000180
1,0.732098,109945.0,40233.0,0.000018,0.999982,1.000000,0.999701,0.999850,0.781006,0.000066,G1_Packet_Byte_Magnitude+G2_Temporal_Activity,0.90,0.998549,0.000180
2,0.790555,118724.0,31454.0,0.000051,0.999949,1.000000,0.999515,0.999757,0.594837,0.000197,G1_Packet_Byte_Magnitude+G2_Temporal_Activity,0.95,0.993818,0.000180
3,0.700369,105180.0,44998.0,0.000000,1.000000,1.000000,1.000000,1.000000,0.726201,0.000000,G1_Packet_Byte_Magnitude+G3_TCP_Control_Flags,0.80,0.999802,0.000028
4,0.809719,121602.0,28576.0,0.000049,0.999951,1.000000,0.999433,0.999716,0.653476,0.000197,G1_Packet_Byte_Magnitude+G3_TCP_Control_Flags,0.90,0.998549,0.000028
5,0.860312,129200.0,20978.0,0.000046,0.999954,1.000000,0.999565,0.999782,0.548516,0.000197,G1_Packet_Byte_Magnitude+G3_TCP_Control_Flags,0.95,0.993818,0.000028
6,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,G1_Packet_Byte_Magnitude+G4_Rate_Header_Flow_C...,0.80,0.999802,0.034352
7,0.007218,1084.0,149094.0,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,G1_Packet_Byte_Magnitude+G4_Rate_Header_Flow_C...,0.90,0.998549,0.034352
8,0.047843,7185.0,142993.0,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,G1_Packet_Byte_Magnitude+G4_Rate_Header_Flow_C...,0.95,0.993818,0.034352
9,0.792366,118996.0,31182.0,0.000017,0.999983,0.999927,0.999927,0.999927,0.548352,0.000033,G2_Temporal_Activity+G3_TCP_Control_Flags,0.80,0.999802,0.000023
10,0.898241,134896.0,15282.0,0.000015,0.999985,0.999949,0.999949,0.999949,0.360709,0.000033,G2_Temporal_Activity+G3_TCP_Control_Flags,0.90,0.998549,0.000023
11,0.946723,142177.0,8001.0,0.000077,0.999923,0.999756,0.999797,0.999777,0.193802,0.000164,G2_Temporal_Activity+G3_TCP_Control_Flags,0.95,0.993818,0.000023
12,0.391083,58732.0,91446.0,0.000000,1.000000,1.000000,1.000000,1.000000,0.903525,0.000000,G2_Temporal_Activity+G4_Rate_Header_Flow_Context,0.80,0.999802,0.002212
13,0.621596,93350.0,56828.0,0.000032,0.999968,1.000000,0.999715,0.999858,0.655114,0.000098,G2_Temporal_Activity+G4_Rate_Header_Flow_Context,0.90,0.998549,0.002212
14,0.764533,114816.0,35362.0,0.000557,0.999443,0.999918,0.994864,0.997385,0.598146,0.002064,G2_Temporal_Activity+G4_Rate_Header_Flow_Context,0.95,0.993818,0.002212
15,0.564330,84750.0,65428.0,0.000012,0.999988,1.000000,0.999911,0.999955,0.632150,0.000033,G3_TCP_Control_Flags+G4_Rate_Header_Flow_Context,0.80,0.999802,0.002115
16,0.728069,109340.0,40838.0,0.000046,0.999954,1.000000,0.999620,0.999810,0.569515,0.000164,G3_TCP_Control_Flags+G4_Rate_Header_Flow_Context,0.90,0.998549,0.002115
17,0.844744,126862.0,23316.0,0.000441,0.999559,0.999946,0.997041,0.998492,0.391044,0.001802,G3_TCP_Control_Flags+G4_Rate_Header_Flow_Context,0.95,0.993818,0.002115

Selective source results and fixed policy saved.

Nextday Start19/07/2026 time:11:35 AM :Start by restoring only the files needed for the ordinary selective-baseline comparison. The sealed target dataset will not be loaded yet.

Step 1: Mount Google Drive

In [ ]:
from google.colab import drive
drive.mount("/content/drive")

Step 2: Restore the experiment state

In [ ]:
from pathlib import Path
import pandas as pd
import numpy as np
import json
import joblib
import xgboost as xgb

checkpoint_dir = Path(
    "/content/drive/MyDrive/research/researchdata/"
    "NIDS_Research/NIDS_Research_Checkpoints"
)

print("Checkpoint folder exists:", checkpoint_dir.exists())

required_files = [
    "experiment_metadata.json",
    "source_calibration.parquet",
    "source_test.parquet",
    "source_median_imputer.joblib",
    "complete_feature_baseline_xgboost.json",
    "source_selective_pairwise_results.csv"
]

for filename in required_files:
    file_path = checkpoint_dir / filename
    print(
        filename,
        "FOUND" if file_path.exists() else "MISSING"
    )

Checkpoint folder exists: True
experiment_metadata.json FOUND
source_calibration.parquet FOUND
source_test.parquet FOUND
source_median_imputer.joblib FOUND
complete_feature_baseline_xgboost.json FOUND
source_selective_pairwise_results.csv FOUND

Step 3: Load metadata, data and models

In [ ]:
with open(
    checkpoint_dir / "experiment_metadata.json"
) as file:
    metadata = json.load(file)

predictor_columns = metadata["predictors"]
semantic_groups = metadata["semantic_groups"]
group_names = list(semantic_groups.keys())

feature_index = {
    feature: position
    for position, feature in enumerate(predictor_columns)
}

group_indices = {
    group: [
        feature_index[feature]
        for feature in features
    ]
    for group, features in semantic_groups.items()
}

calibration_df = pd.read_parquet(
    checkpoint_dir / "source_calibration.parquet"
)

source_test_df = pd.read_parquet(
    checkpoint_dir / "source_test.parquet"
)

source_selective_results = pd.read_csv(
    checkpoint_dir /
    "source_selective_pairwise_results.csv"
)

imputer = joblib.load(
    checkpoint_dir /
    "source_median_imputer.joblib"
)

training_medians = np.asarray(
    imputer.statistics_,
    dtype=np.float32
)

baseline_model = xgb.XGBClassifier()

baseline_model.load_model(
    checkpoint_dir /
    "complete_feature_baseline_xgboost.json"
)

Step 4: Recreate the required arrays

In [ ]:
X_calibration_imputed = imputer.transform(
    calibration_df[predictor_columns]
)

y_calibration = (
    calibration_df["target"]
    .to_numpy(dtype="int8")
)

X_source_test_imputed = imputer.transform(
    source_test_df[predictor_columns]
)

y_source_test = (
    source_test_df["target"]
    .to_numpy(dtype="int8")
)

calibration_hash = pd.util.hash_pandas_object(
    calibration_df[predictor_columns],
    index=False
).to_numpy(dtype="uint64")

calibrator_mask = (
    calibration_hash % 2 == 0
)

policy_mask = ~calibrator_mask

X_calibrator_base = X_calibration_imputed[
    calibrator_mask
]

y_calibrator_base = y_calibration[
    calibrator_mask
]

X_policy_base = X_calibration_imputed[
    policy_mask
]

y_policy_base = y_calibration[
    policy_mask
]

Step 5: Verify restoration

In [ ]:
print("\nRestoration summary")
print("Predictors:", len(predictor_columns))
print("Semantic groups:", len(semantic_groups))
print("Calibration rows:", len(calibration_df))
print("Calibrator-fit rows:", len(y_calibrator_base))
print("Policy-selection rows:", len(y_policy_base))
print("Source-test rows:", len(y_source_test))
print(
    "Previous group-aware selective rows:",
    len(source_selective_results)
)
print(
    "Baseline model features:",
    baseline_model.n_features_in_
)

Restoration summary
Predictors: 77
Semantic groups: 4
Calibration rows: 99084
Calibrator-fit rows: 48889
Policy-selection rows: 50195
Source-test rows: 150178
Previous group-aware selective rows: 18
Baseline model features: 77

Restoration is correct. Now run the ordinary selective-baseline comparison. It should take approximately 5–15 minutes on CPU.

1. Define the required functions

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    precision_recall_curve,
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)
from itertools import combinations
import numpy as np
import pandas as pd
import joblib
import json

desired_coverages = [0.80, 0.90, 0.95]

def probability_to_logit(probability):
    probability = np.clip(
        probability,
        1e-7,
        1 - 1e-7
    )

    return np.log(
        probability / (1 - probability)
    ).reshape(-1, 1)


def apply_group_loss(
    X,
    missing_groups,
    replacement="median"
):
    X_masked = np.asarray(
        X,
        dtype=np.float32
    ).copy()

    columns_to_mask = []

    for group in missing_groups:
        columns_to_mask.extend(
            group_indices[group]
        )

    columns_to_mask = sorted(
        set(columns_to_mask)
    )

    if replacement == "median":
        X_masked[:, columns_to_mask] = (
            training_medians[columns_to_mask]
        )
    elif replacement == "zero":
        X_masked[:, columns_to_mask] = 0.0
    else:
        raise ValueError(
            "Use 'median' or 'zero'."
        )

    return X_masked


def calculate_aurc(
    y_true,
    probability,
    classification_threshold
):
    y_true = np.asarray(y_true)

    prediction = (
        probability >= classification_threshold
    ).astype("int8")

    confidence = np.maximum(
        probability,
        1 - probability
    )

    errors = (
        prediction != y_true
    ).astype("float64")

    order = np.argsort(-confidence)
    ordered_errors = errors[order]

    cumulative_errors = np.cumsum(
        ordered_errors
    )

    accepted_count = np.arange(
        1,
        len(y_true) + 1
    )

    risks = cumulative_errors / accepted_count

    return float(np.mean(risks))


def evaluate_selective_policy(
    y_true,
    probability,
    classification_threshold,
    confidence_cutoff
):
    y_true = np.asarray(y_true)

    prediction = (
        probability >= classification_threshold
    ).astype("int8")

    confidence = np.maximum(
        probability,
        1 - probability
    )

    accepted = confidence >= confidence_cutoff

    accepted_rows = int(accepted.sum())
    abstained_rows = int((~accepted).sum())

    total_attacks = int((y_true == 1).sum())

    attack_abstentions = int(
        ((~accepted) & (y_true == 1)).sum()
    )

    accepted_false_negatives = int(
        (
            accepted &
            (y_true == 1) &
            (prediction == 0)
        ).sum()
    )

    result = {
        "actual_coverage": float(accepted.mean()),
        "accepted_rows": accepted_rows,
        "abstained_rows": abstained_rows,
        "selective_risk": np.nan,
        "accepted_accuracy": np.nan,
        "accepted_precision": np.nan,
        "accepted_recall": np.nan,
        "accepted_f1": np.nan,
        "attack_abstention_rate":
            attack_abstentions / total_attacks,
        "accepted_false_negative_rate":
            accepted_false_negatives / total_attacks
    }

    if accepted_rows > 0:
        accepted_y = y_true[accepted]
        accepted_prediction = prediction[accepted]

        result.update({
            "selective_risk": float(
                np.mean(
                    accepted_prediction != accepted_y
                )
            ),
            "accepted_accuracy": accuracy_score(
                accepted_y,
                accepted_prediction
            ),
            "accepted_precision": precision_score(
                accepted_y,
                accepted_prediction,
                zero_division=0
            ),
            "accepted_recall": recall_score(
                accepted_y,
                accepted_prediction,
                zero_division=0
            ),
            "accepted_f1": f1_score(
                accepted_y,
                accepted_prediction,
                zero_division=0
            )
        })

    return result

2. Calibrate the ordinary baseline

In [ ]:
baseline_raw_calibrator = (
    baseline_model.predict_proba(
        X_calibrator_base
    )[:, 1]
)

baseline_platt_calibrator = LogisticRegression(
    C=1_000_000,
    solver="lbfgs",
    max_iter=1000,
    random_state=2026
)

baseline_platt_calibrator.fit(
    probability_to_logit(
        baseline_raw_calibrator
    ),
    y_calibrator_base
)

baseline_raw_policy = (
    baseline_model.predict_proba(
        X_policy_base
    )[:, 1]
)

baseline_calibrated_policy = (
    baseline_platt_calibrator.predict_proba(
        probability_to_logit(
            baseline_raw_policy
        )
    )[:, 1]
)

3. Fix the baseline classification and confidence thresholds

In [ ]:
precision_values, recall_values, thresholds = (
    precision_recall_curve(
        y_policy_base,
        baseline_calibrated_policy
    )
)

f1_values = (
    2 * precision_values[:-1] * recall_values[:-1]
    /
    (
        precision_values[:-1]
        + recall_values[:-1]
        + 1e-12
    )
)

best_position = np.argmax(f1_values)

baseline_selective_threshold = float(
    thresholds[best_position]
)

baseline_policy_confidence = np.maximum(
    baseline_calibrated_policy,
    1 - baseline_calibrated_policy
)

baseline_confidence_cutoffs = {
    coverage: float(
        np.quantile(
            baseline_policy_confidence,
            1 - coverage
        )
    )
    for coverage in desired_coverages
}

print(
    "Baseline classification threshold:",
    baseline_selective_threshold
)

for coverage, cutoff in (
    baseline_confidence_cutoffs.items()
):
    print(
        f"{coverage:.0%} policy cutoff:",
        cutoff
    )

Baseline classification threshold: 0.34849086958207653
80% policy cutoff: 0.9999932917712001
90% policy cutoff: 0.9999570640064098
95% policy cutoff: 0.9996796643169196

4. Run the six pairwise-loss conditions

In [ ]:
baseline_selective_results = []

for missing_groups in combinations(
    group_names,
    2
):
    print(
        "Testing:",
        "+".join(missing_groups)
    )

    X_masked = apply_group_loss(
        X_source_test_imputed,
        missing_groups,
        replacement="median"
    )

    raw_probability = (
        baseline_model.predict_proba(
            X_masked
        )[:, 1]
    )

    calibrated_probability = (
        baseline_platt_calibrator.predict_proba(
            probability_to_logit(
                raw_probability
            )
        )[:, 1]
    )

    aurc = calculate_aurc(
        y_source_test,
        calibrated_probability,
        baseline_selective_threshold
    )

    for desired_coverage, cutoff in (
        baseline_confidence_cutoffs.items()
    ):
        result = evaluate_selective_policy(
            y_source_test,
            calibrated_probability,
            baseline_selective_threshold,
            cutoff
        )

        result.update({
            "missing_groups":
                "+".join(missing_groups),
            "desired_policy_coverage":
                desired_coverage,
            "source_confidence_cutoff":
                cutoff,
            "aurc": aurc
        })

        baseline_selective_results.append(
            result
        )

    del X_masked

baseline_selective_results = pd.DataFrame(
    baseline_selective_results
)

display(
    baseline_selective_results.round(6)
)

Testing: G1_Packet_Byte_Magnitude+G2_Temporal_Activity
Testing: G1_Packet_Byte_Magnitude+G3_TCP_Control_Flags
Testing: G1_Packet_Byte_Magnitude+G4_Rate_Header_Flow_Context
Testing: G2_Temporal_Activity+G3_TCP_Control_Flags
Testing: G2_Temporal_Activity+G4_Rate_Header_Flow_Context
Testing: G3_TCP_Control_Flags+G4_Rate_Header_Flow_Context

,actual_coverage,accepted_rows,abstained_rows,selective_risk,accepted_accuracy,accepted_precision,accepted_recall,accepted_f1,attack_abstention_rate,accepted_false_negative_rate,missing_groups,desired_policy_coverage,source_confidence_cutoff,aurc
0,0.432753,64990,85188,0.001631,0.998369,0.000000,0.000000,0.000000,0.996528,0.003472,G1_Packet_Byte_Magnitude+G2_Temporal_Activity,0.80,0.999993,0.026582
1,0.735108,110397,39781,0.035128,0.964872,0.000000,0.000000,0.000000,0.872961,0.127039,G1_Packet_Byte_Magnitude+G2_Temporal_Activity,0.90,0.999957,0.026582
2,0.789716,118598,31580,0.070010,0.929990,0.000000,0.000000,0.000000,0.728002,0.271998,G1_Packet_Byte_Magnitude+G2_Temporal_Activity,0.95,0.999680,0.026582
3,0.566161,85025,65153,0.000129,0.999871,0.000000,0.000000,0.000000,0.999640,0.000360,G1_Packet_Byte_Magnitude+G3_TCP_Control_Flags,0.80,0.999993,0.015541
4,0.742712,111539,38639,0.003407,0.996593,0.000000,0.000000,0.000000,0.987552,0.012448,G1_Packet_Byte_Magnitude+G3_TCP_Control_Flags,0.90,0.999957,0.015541
5,0.802834,120568,29610,0.030265,0.969735,0.000000,0.000000,0.000000,0.880463,0.119537,G1_Packet_Byte_Magnitude+G3_TCP_Control_Flags,0.95,0.999680,0.015541
6,0.000000,0,150178,NaN,NaN,NaN,NaN,NaN,1.000000,0.000000,G1_Packet_Byte_Magnitude+G4_Rate_Header_Flow_C...,0.80,0.999993,0.056648
7,0.000020,3,150175,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,G1_Packet_Byte_Magnitude+G4_Rate_Header_Flow_C...,0.90,0.999957,0.056648
8,0.135133,20294,129884,0.000936,0.999064,0.000000,0.000000,0.000000,0.999378,0.000622,G1_Packet_Byte_Magnitude+G4_Rate_Header_Flow_C...,0.95,0.999680,0.056648
9,0.720991,108277,41901,0.000000,1.000000,1.000000,1.000000,1.000000,0.907128,0.000000,G2_Temporal_Activity+G3_TCP_Control_Flags,0.80,0.999993,0.001293
10,0.784256,117778,32400,0.000025,0.999975,1.000000,0.999548,0.999774,0.782382,0.000098,G2_Temporal_Activity+G3_TCP_Control_Flags,0.90,0.999957,0.001293
11,0.850138,127672,22506,0.000313,0.999687,0.999919,0.996840,0.998377,0.595722,0.001278,G2_Temporal_Activity+G3_TCP_Control_Flags,0.95,0.999680,0.001293
12,0.000000,0,150178,NaN,NaN,NaN,NaN,NaN,1.000000,0.000000,G2_Temporal_Activity+G4_Rate_Header_Flow_Context,0.80,0.999993,0.010185
13,0.000000,0,150178,NaN,NaN,NaN,NaN,NaN,1.000000,0.000000,G2_Temporal_Activity+G4_Rate_Header_Flow_Context,0.90,0.999957,0.010185
14,0.070317,10560,139618,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,G2_Temporal_Activity+G4_Rate_Header_Flow_Context,0.95,0.999680,0.010185
15,0.022873,3435,146743,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,G3_TCP_Control_Flags+G4_Rate_Header_Flow_Context,0.80,0.999993,0.022182
16,0.110555,16603,133575,0.000000,1.000000,1.000000,1.000000,1.000000,0.999607,0.000000,G3_TCP_Control_Flags+G4_Rate_Header_Flow_Context,0.90,0.999957,0.022182
17,0.216616,32531,117647,0.000092,0.999908,0.995253,1.000000,0.997621,0.979395,0.000000,G3_TCP_Control_Flags+G4_Rate_Header_Flow_Context,0.95,0.999680,0.022182

5. Compare baseline against group-aware selection

In [ ]:
comparison_fields = [
    "missing_groups",
    "desired_policy_coverage",
    "actual_coverage",
    "selective_risk",
    "accepted_f1",
    "attack_abstention_rate",
    "accepted_false_negative_rate",
    "aurc"
]

selective_comparison = (
    baseline_selective_results[
        comparison_fields
    ]
    .merge(
        source_selective_results[
            comparison_fields
        ],
        on=[
            "missing_groups",
            "desired_policy_coverage"
        ],
        suffixes=(
            "_baseline",
            "_group_aware"
        )
    )
)

selective_comparison[
    "risk_reduction"
] = (
    selective_comparison[
        "selective_risk_baseline"
    ]
    -
    selective_comparison[
        "selective_risk_group_aware"
    ]
)

selective_comparison[
    "aurc_improvement"
] = (
    selective_comparison[
        "aurc_baseline"
    ]
    -
    selective_comparison[
        "aurc_group_aware"
    ]
)

display(
    selective_comparison.round(6)
)

,missing_groups,desired_policy_coverage,actual_coverage_baseline,selective_risk_baseline,accepted_f1_baseline,attack_abstention_rate_baseline,accepted_false_negative_rate_baseline,aurc_baseline,actual_coverage_group_aware,selective_risk_group_aware,accepted_f1_group_aware,attack_abstention_rate_group_aware,accepted_false_negative_rate_group_aware,aurc_group_aware,risk_reduction,aurc_improvement
0,G1_Packet_Byte_Magnitude+G2_Temporal_Activity,0.80,0.432753,0.001631,0.000000,0.996528,0.003472,0.026582,0.567633,0.000012,0.000000,0.999967,0.000033,0.000180,0.001619,0.026402
1,G1_Packet_Byte_Magnitude+G2_Temporal_Activity,0.90,0.735108,0.035128,0.000000,0.872961,0.127039,0.026582,0.732098,0.000018,0.999850,0.781006,0.000066,0.000180,0.035110,0.026402
2,G1_Packet_Byte_Magnitude+G2_Temporal_Activity,0.95,0.789716,0.070010,0.000000,0.728002,0.271998,0.026582,0.790555,0.000051,0.999757,0.594837,0.000197,0.000180,0.069959,0.026402
3,G1_Packet_Byte_Magnitude+G3_TCP_Control_Flags,0.80,0.566161,0.000129,0.000000,0.999640,0.000360,0.015541,0.700369,0.000000,1.000000,0.726201,0.000000,0.000028,0.000129,0.015513
4,G1_Packet_Byte_Magnitude+G3_TCP_Control_Flags,0.90,0.742712,0.003407,0.000000,0.987552,0.012448,0.015541,0.809719,0.000049,0.999716,0.653476,0.000197,0.000028,0.003358,0.015513
5,G1_Packet_Byte_Magnitude+G3_TCP_Control_Flags,0.95,0.802834,0.030265,0.000000,0.880463,0.119537,0.015541,0.860312,0.000046,0.999782,0.548516,0.000197,0.000028,0.030219,0.015513
6,G1_Packet_Byte_Magnitude+G4_Rate_Header_Flow_C...,0.80,0.000000,NaN,NaN,1.000000,0.000000,0.056648,0.000000,NaN,NaN,NaN,NaN,0.034352,NaN,0.022296
7,G1_Packet_Byte_Magnitude+G4_Rate_Header_Flow_C...,0.90,0.000020,0.000000,0.000000,1.000000,0.000000,0.056648,0.007218,0.000000,0.000000,1.000000,0.000000,0.034352,0.000000,0.022296
8,G1_Packet_Byte_Magnitude+G4_Rate_Header_Flow_C...,0.95,0.135133,0.000936,0.000000,0.999378,0.000622,0.056648,0.047843,0.000000,0.000000,1.000000,0.000000,0.034352,0.000936,0.022296
9,G2_Temporal_Activity+G3_TCP_Control_Flags,0.80,0.720991,0.000000,1.000000,0.907128,0.000000,0.001293,0.792366,0.000017,0.999927,0.548352,0.000033,0.000023,-0.000017,0.001270
10,G2_Temporal_Activity+G3_TCP_Control_Flags,0.90,0.784256,0.000025,0.999774,0.782382,0.000098,0.001293,0.898241,0.000015,0.999949,0.360709,0.000033,0.000023,0.000011,0.001270
11,G2_Temporal_Activity+G3_TCP_Control_Flags,0.95,0.850138,0.000313,0.998377,0.595722,0.001278,0.001293,0.946723,0.000077,0.999777,0.193802,0.000164,0.000023,0.000236,0.001270
12,G2_Temporal_Activity+G4_Rate_Header_Flow_Context,0.80,0.000000,NaN,NaN,1.000000,0.000000,0.010185,0.391083,0.000000,1.000000,0.903525,0.000000,0.002212,NaN,0.007973
13,G2_Temporal_Activity+G4_Rate_Header_Flow_Context,0.90,0.000000,NaN,NaN,1.000000,0.000000,0.010185,0.621596,0.000032,0.999858,0.655114,0.000098,0.002212,NaN,0.007973
14,G2_Temporal_Activity+G4_Rate_Header_Flow_Context,0.95,0.070317,0.000000,0.000000,1.000000,0.000000,0.010185,0.764533,0.000557,0.997385,0.598146,0.002064,0.002212,-0.000557,0.007973
15,G3_TCP_Control_Flags+G4_Rate_Header_Flow_Context,0.80,0.022873,0.000000,0.000000,1.000000,0.000000,0.022182,0.564330,0.000012,0.999955,0.632150,0.000033,0.002115,-0.000012,0.020067
16,G3_TCP_Control_Flags+G4_Rate_Header_Flow_Context,0.90,0.110555,0.000000,1.000000,0.999607,0.000000,0.022182,0.728069,0.000046,0.999810,0.569515,0.000164,0.002115,-0.000046,0.020067
17,G3_TCP_Control_Flags+G4_Rate_Header_Flow_Context,0.95,0.216616,0.000092,0.997621,0.979395,0.000000,0.022182,0.844744,0.000441,0.998492,0.391044,0.001802,0.002115,-0.000349,0.020067

6. Save everything

In [ ]:
joblib.dump(
    baseline_platt_calibrator,
    checkpoint_dir /
    "baseline_platt_calibrator.joblib"
)

baseline_selective_results.to_csv(
    checkpoint_dir /
    "baseline_source_selective_pairwise_results.csv",
    index=False
)

selective_comparison.to_csv(
    checkpoint_dir /
    "selective_baseline_vs_group_aware.csv",
    index=False
)

baseline_selective_policy = {
    "classification_threshold":
        baseline_selective_threshold,
    "confidence_cutoffs": {
        str(coverage): cutoff
        for coverage, cutoff
        in baseline_confidence_cutoffs.items()
    },
    "calibration_data":
        "source complete-condition calibration subset",
    "target_data_used": False
}

with open(
    checkpoint_dir /
    "baseline_selective_policy.json",
    "w"
) as file:
    json.dump(
        baseline_selective_policy,
        file,
        indent=2
    )

print("Ordinary selective-baseline experiment saved.")

Ordinary selective-baseline experiment saved.

The source-domain gate has passed.

At the same nominal policies, the group-aware model achieved:

Policy	Baseline coverage	Group-aware coverage	Baseline risk	Group-aware risk
80%	29.05%	50.26%	0.0440%	0.0008%
90%	39.54%	63.28%	0.7712%	0.0027%
95%	47.75%	70.91%	1.6936%	0.0196%

Average AURC decreased from 0.02207 to 0.00649, an improvement of approximately 70.6%. AURC is the strongest comparison here because actual coverage changes under unseen conditions.

We can now unseal the target dataset for the final zero-target evaluation. Nothing may be retrained or retuned after viewing these results.

1. Load the sealed target and fixed models

In [ ]:
import gc
import time

target_df = pd.read_parquet(
    checkpoint_dir /
    "target_test_sealed.parquet"
)

X_target_imputed = imputer.transform(
    target_df[predictor_columns]
)

y_target = (
    target_df["target"]
    .to_numpy(dtype="int8")
)

group_aware_model = xgb.XGBClassifier()
group_aware_model.load_model(
    checkpoint_dir /
    "group_aware_single_mask_xgboost.json"
)

group_aware_platt = joblib.load(
    checkpoint_dir /
    "group_aware_platt_calibrator.joblib"
)

baseline_platt = joblib.load(
    checkpoint_dir /
    "baseline_platt_calibrator.joblib"
)

with open(
    checkpoint_dir /
    "selective_policy.json"
) as file:
    group_policy = json.load(file)

with open(
    checkpoint_dir /
    "baseline_selective_policy.json"
) as file:
    baseline_policy = json.load(file)

group_threshold = float(
    group_policy["classification_threshold"]
)

baseline_threshold = float(
    baseline_policy["classification_threshold"]
)

group_cutoffs = {
    float(coverage): float(cutoff)
    for coverage, cutoff
    in group_policy["confidence_cutoffs"].items()
}

baseline_cutoffs = {
    float(coverage): float(cutoff)
    for coverage, cutoff
    in baseline_policy["confidence_cutoffs"].items()
}

print("Target rows:", len(y_target))
print("Target predictors:", X_target_imputed.shape[1])
print("Baseline features:", baseline_model.n_features_in_)
print("Group-aware features:", group_aware_model.n_features_in_)

Target rows: 999143
Target predictors: 77
Baseline features: 77
Group-aware features: 81

2. Define group-aware inputs and non-selective metrics

In [ ]:
from sklearn.metrics import (
    balanced_accuracy_score,
    roc_auc_score,
    average_precision_score,
    matthews_corrcoef,
    confusion_matrix,
    brier_score_loss,
    log_loss
)

def create_group_aware_condition(
    X,
    missing_groups
):
    X_condition = np.asarray(
        X,
        dtype=np.float32
    ).copy()

    availability = np.ones(
        (len(X_condition), len(group_names)),
        dtype=np.float32
    )

    for group in missing_groups:
        group_number = group_names.index(group)
        columns = group_indices[group]

        X_condition[:, columns] = (
            training_medians[columns]
        )

        availability[:, group_number] = 0.0

    return np.hstack([
        X_condition,
        availability
    ])


def expected_calibration_error(
    y_true,
    probability,
    bins=15
):
    edges = np.linspace(0, 1, bins + 1)
    ece = 0.0

    for lower, upper in zip(
        edges[:-1],
        edges[1:]
    ):
        if upper == 1:
            selected = (
                (probability >= lower) &
                (probability <= upper)
            )
        else:
            selected = (
                (probability >= lower) &
                (probability < upper)
            )

        count = selected.sum()

        if count == 0:
            continue

        ece += (
            count / len(y_true)
        ) * abs(
            np.mean(y_true[selected])
            - np.mean(probability[selected])
        )

    return float(ece)


def evaluate_nonselective(
    y_true,
    probability,
    threshold
):
    prediction = (
        probability >= threshold
    ).astype("int8")

    tn, fp, fn, tp = confusion_matrix(
        y_true,
        prediction,
        labels=[0, 1]
    ).ravel()

    return {
        "accuracy": accuracy_score(
            y_true, prediction
        ),
        "balanced_accuracy": balanced_accuracy_score(
            y_true, prediction
        ),
        "precision": precision_score(
            y_true, prediction,
            zero_division=0
        ),
        "recall": recall_score(
            y_true, prediction,
            zero_division=0
        ),
        "f1": f1_score(
            y_true, prediction,
            zero_division=0
        ),
        "roc_auc": roc_auc_score(
            y_true, probability
        ),
        "pr_auc": average_precision_score(
            y_true, probability
        ),
        "mcc": matthews_corrcoef(
            y_true, prediction
        ),
        "false_positive_rate":
            fp / (fp + tn),
        "false_negative_rate":
            fn / (fn + tp),
        "brier": brier_score_loss(
            y_true, probability
        ),
        "logloss": log_loss(
            y_true, probability
        ),
        "ece": expected_calibration_error(
            y_true, probability
        ),
        "tn": int(tn),
        "fp": int(fp),
        "fn": int(fn),
        "tp": int(tp)
    }

3. Run complete, single and unseen pairwise target tests

In [ ]:
target_nonselective_results = []
target_selective_results = []

conditions = [("complete", tuple())]

conditions.extend([
    ("single", (group,))
    for group in group_names
])

conditions.extend([
    ("pairwise_unseen", pair)
    for pair in combinations(group_names, 2)
])

for condition_type, missing_groups in conditions:
    condition_name = (
        "+".join(missing_groups)
        if missing_groups
        else "None"
    )

    print("\nTesting:", condition_type, condition_name)
    start = time.time()

    # Ordinary baseline
    X_baseline_condition = apply_group_loss(
        X_target_imputed,
        missing_groups,
        replacement="median"
    )

    baseline_raw_probability = (
        baseline_model.predict_proba(
            X_baseline_condition
        )[:, 1]
    )

    baseline_probability = (
        baseline_platt.predict_proba(
            probability_to_logit(
                baseline_raw_probability
            )
        )[:, 1]
    )

    baseline_result = evaluate_nonselective(
        y_target,
        baseline_probability,
        baseline_threshold
    )

    baseline_result.update({
        "model": "ordinary_baseline",
        "condition_type": condition_type,
        "missing_groups": condition_name
    })

    target_nonselective_results.append(
        baseline_result
    )

    baseline_aurc = calculate_aurc(
        y_target,
        baseline_probability,
        baseline_threshold
    )

    for desired_coverage, cutoff in (
        baseline_cutoffs.items()
    ):
        result = evaluate_selective_policy(
            y_target,
            baseline_probability,
            baseline_threshold,
            cutoff
        )

        result.update({
            "model": "ordinary_baseline",
            "condition_type": condition_type,
            "missing_groups": condition_name,
            "desired_policy_coverage":
                desired_coverage,
            "source_confidence_cutoff":
                cutoff,
            "aurc": baseline_aurc
        })

        target_selective_results.append(result)

    del X_baseline_condition
    del baseline_raw_probability
    del baseline_probability
    gc.collect()

    # Group-aware model
    X_group_condition = create_group_aware_condition(
        X_target_imputed,
        missing_groups
    )

    group_raw_probability = (
        group_aware_model.predict_proba(
            X_group_condition
        )[:, 1]
    )

    group_probability = (
        group_aware_platt.predict_proba(
            probability_to_logit(
                group_raw_probability
            )
        )[:, 1]
    )

    group_result = evaluate_nonselective(
        y_target,
        group_probability,
        group_threshold
    )

    group_result.update({
        "model": "group_aware",
        "condition_type": condition_type,
        "missing_groups": condition_name
    })

    target_nonselective_results.append(
        group_result
    )

    group_aurc = calculate_aurc(
        y_target,
        group_probability,
        group_threshold
    )

    for desired_coverage, cutoff in (
        group_cutoffs.items()
    ):
        result = evaluate_selective_policy(
            y_target,
            group_probability,
            group_threshold,
            cutoff
        )

        result.update({
            "model": "group_aware",
            "condition_type": condition_type,
            "missing_groups": condition_name,
            "desired_policy_coverage":
                desired_coverage,
            "source_confidence_cutoff":
                cutoff,
            "aurc": group_aurc
        })

        target_selective_results.append(result)

    del X_group_condition
    del group_raw_probability
    del group_probability
    gc.collect()

    print(
        "Completed in",
        round(time.time() - start, 1),
        "seconds"
    )

Testing: complete None
Completed in 39.6 seconds

Testing: single G1_Packet_Byte_Magnitude
Completed in 43.3 seconds

Testing: single G2_Temporal_Activity
Completed in 38.1 seconds

Testing: single G3_TCP_Control_Flags
Completed in 41.1 seconds

Testing: single G4_Rate_Header_Flow_Context
Completed in 37.2 seconds

Testing: pairwise_unseen G1_Packet_Byte_Magnitude+G2_Temporal_Activity
Completed in 40.9 seconds

Testing: pairwise_unseen G1_Packet_Byte_Magnitude+G3_TCP_Control_Flags
Completed in 39.0 seconds

Testing: pairwise_unseen G1_Packet_Byte_Magnitude+G4_Rate_Header_Flow_Context
Completed in 40.7 seconds

Testing: pairwise_unseen G2_Temporal_Activity+G3_TCP_Control_Flags
Completed in 38.5 seconds

Testing: pairwise_unseen G2_Temporal_Activity+G4_Rate_Header_Flow_Context
Completed in 40.4 seconds

Testing: pairwise_unseen G3_TCP_Control_Flags+G4_Rate_Header_Flow_Context
Completed in 37.8 seconds

4. Save the final target results

In [ ]:
target_nonselective_results = pd.DataFrame(
    target_nonselective_results
)

target_selective_results = pd.DataFrame(
    target_selective_results
)

target_nonselective_results.to_csv(
    checkpoint_dir /
    "target_nonselective_results.csv",
    index=False
)

target_selective_results.to_csv(
    checkpoint_dir /
    "target_selective_results.csv",
    index=False
)

print(
    "Non-selective rows:",
    len(target_nonselective_results)
)

print(
    "Selective rows:",
    len(target_selective_results)
)

print("Final target evaluation saved.")

Non-selective rows: 22
Selective rows: 66
Final target evaluation saved.

We will treat the existing seed 2026 as the exploratory pilot. For stronger evidence, the primary replication will use five new, predefined seeds:

2027, 2028, 2029, 2030, 2031

The target results will not influence configurations, thresholds or model selection. First, freeze the replication protocol before running anything.

Step 1: Create the replication protocol

Run this in the restored Colab session:

In [ ]:
from pathlib import Path
import pandas as pd
import numpy as np
import json
import joblib
import xgboost as xgb

checkpoint_dir = Path(
    "/content/drive/MyDrive/research/researchdata/"
    "NIDS_Research/NIDS_Research_Checkpoints"
)

print("Checkpoint folder exists:", checkpoint_dir.exists())

required_files = [
    "experiment_metadata.json",
    "source_calibration.parquet",
    "source_test.parquet",
    "source_median_imputer.joblib",
    "complete_feature_baseline_xgboost.json",
    "source_selective_pairwise_results.csv"
]

for filename in required_files:
    file_path = checkpoint_dir / filename
    print(
        filename,
        "FOUND" if file_path.exists() else "MISSING"
    )

Checkpoint folder exists: True
experiment_metadata.json FOUND
source_calibration.parquet FOUND
source_test.parquet FOUND
source_median_imputer.joblib FOUND
complete_feature_baseline_xgboost.json FOUND
source_selective_pairwise_results.csv FOUND

In [ ]:
from pathlib import Path
import hashlib
import json
from datetime import datetime

replication_dir = (
    checkpoint_dir /
    "five_seed_confirmatory_replication"
)

replication_dir.mkdir(
    parents=True,
    exist_ok=True
)

confirmatory_seeds = [
    2027,
    2028,
    2029,
    2030,
    2031
]

files_to_freeze = [
    "source_train.parquet",
    "source_validation.parquet",
    "source_calibration.parquet",
    "source_test.parquet",
    "target_test_sealed.parquet",
    "experiment_metadata.json",
    "source_median_imputer.joblib"
]

def calculate_sha256(file_path):
    sha256 = hashlib.sha256()

    with open(file_path, "rb") as file:
        while True:
            block = file.read(1024 * 1024)

            if not block:
                break

            sha256.update(block)

    return sha256.hexdigest()

frozen_files = {}

for filename in files_to_freeze:
    file_path = checkpoint_dir / filename

    if not file_path.exists():
        raise FileNotFoundError(
            f"Missing required file: {filename}"
        )

    frozen_files[filename] = {
        "size_bytes": file_path.stat().st_size,
        "sha256": calculate_sha256(file_path)
    }

    print("Frozen:", filename)

Frozen: source_train.parquet
Frozen: source_validation.parquet
Frozen: source_calibration.parquet
Frozen: source_test.parquet
Frozen: target_test_sealed.parquet
Frozen: experiment_metadata.json
Frozen: source_median_imputer.joblib

Step 2: Define the fixed model configuration

In [ ]:
fixed_model_configuration = {
    "objective": "binary:logistic",
    "n_estimators": 1200,
    "learning_rate": 0.05,
    "max_depth": 6,
    "min_child_weight": 5,
    "subsample": 0.80,
    "colsample_bytree": 0.80,
    "reg_alpha": 0.01,
    "reg_lambda": 1.0,
    "tree_method": "hist",
    "device": "cpu",
    "eval_metric": "logloss",
    "early_stopping_rounds": 50,
    "n_jobs": -1
}

Step 3: Save the frozen protocol

In [ ]:
replication_protocol = {
    "protocol_name":
        "Five-seed confirmatory replication",
    "protocol_version": "1.0",
    "frozen_on": datetime.now().isoformat(),
    "exploratory_pilot_seed": 2026,
    "pilot_included_in_primary_summary": False,
    "confirmatory_seeds": confirmatory_seeds,

    "source_dataset": "CICIDS2017",
    "external_target_dataset":
        "CSE-CIC-IDS2018",

    "source_train_rows": 598043,
    "source_validation_rows": 152964,
    "source_calibration_rows": 99084,
    "source_test_rows": 150178,
    "target_test_rows": 999143,

    "predictor_count": 77,
    "semantic_group_count": 4,

    "fixed_model_configuration":
        fixed_model_configuration,

    "ordinary_baseline_training":
        "Complete source training data only",

    "group_aware_training": {
        "complete_copy_per_training_row": 1,
        "random_single_group_mask_copy_per_row": 1,
        "group_availability_indicators": 4,
        "pairwise_masks_used_during_training": False
    },

    "calibration": {
        "method": "Platt scaling",
        "calibrator_data":
            "Fixed source calibrator subset",
        "policy_data":
            "Fixed source policy subset",
        "target_labels_used": False
    },

    "classification_threshold":
        "Source-policy F1 maximization",

    "selective_coverages": [
        0.80,
        0.90,
        0.95
    ],

    "primary_endpoints": [
        "Mean source unseen-pairwise F1",
        "Mean target unseen-pairwise F1",
        "Mean source unseen-pairwise AURC",
        "Mean target unseen-pairwise AURC"
    ],

    "secondary_endpoints": [
        "Recall",
        "Precision",
        "False-positive rate",
        "False-negative rate",
        "ECE",
        "Brier score",
        "Selective risk",
        "Actual coverage",
        "Class-conditional coverage"
    ],

    "target_result_rules": [
        "No target-label training",
        "No target-label calibration",
        "No target-dependent threshold selection",
        "No removal of unfavorable conditions",
        "All five confirmatory seeds will be reported"
    ],

    "frozen_files": frozen_files
}

protocol_path = (
    replication_dir /
    "replication_protocol_frozen.json"
)

with open(protocol_path, "w") as file:
    json.dump(
        replication_protocol,
        file,
        indent=2
    )

print("\nProtocol saved:", protocol_path)
print("Confirmatory seeds:", confirmatory_seeds)
print(
    "Frozen files:",
    len(frozen_files)
)

Protocol saved: /content/drive/MyDrive/research/researchdata/NIDS_Research/NIDS_Research_Checkpoints/five_seed_confirmatory_replication/replication_protocol_frozen.json
Confirmatory seeds: [2027, 2028, 2029, 2030, 2031]
Frozen files: 7

The protocol is now frozen correctly. Next, prepare the fixed source data used by every confirmatory seed. The target dataset will not be loaded during training.

Step 1: Free unnecessary target objects from memory

In [ ]:
import gc

for variable_name in [
    "target_df",
    "X_target_imputed",
    "y_target",
    "target_nonselective_results",
    "target_selective_results"
]:
    globals().pop(variable_name, None)

gc.collect()

print("Unused target objects cleared.")

Unused target objects cleared.

This only removes temporary memory objects. The sealed Parquet file remains safely in Google Drive.

Step 2: Load the fixed source partitions

In [ ]:
import json

with open(
    checkpoint_dir /
    "experiment_metadata.json"
) as file:
    metadata = json.load(file)

predictor_columns = metadata["predictors"]
semantic_groups = metadata["semantic_groups"]

group_names = list(
    semantic_groups.keys()
)

feature_index = {
    feature: position
    for position, feature
    in enumerate(predictor_columns)
}

group_indices = {
    group: [
        feature_index[feature]
        for feature
        in semantic_groups[group]
    ]
    for group in group_names
}

availability_names = [
    f"available__{group}"
    for group in group_names
]

print("Predictors loaded:", len(predictor_columns))
print("Semantic groups loaded:", len(group_names))

Predictors loaded: 77
Semantic groups loaded: 4

In [ ]:
import pandas as pd
import numpy as np
import joblib
import json
import xgboost as xgb
import time

train_df = pd.read_parquet(
    checkpoint_dir / "source_train.parquet"
)

validation_df = pd.read_parquet(
    checkpoint_dir / "source_validation.parquet"
)

calibration_df = pd.read_parquet(
    checkpoint_dir / "source_calibration.parquet"
)

imputer = joblib.load(
    checkpoint_dir /
    "source_median_imputer.joblib"
)

X_train_fixed = imputer.transform(
    train_df[predictor_columns]
).astype("float32")

y_train_fixed = (
    train_df["target"]
    .to_numpy(dtype="int8")
)

X_validation_fixed = imputer.transform(
    validation_df[predictor_columns]
).astype("float32")

y_validation_fixed = (
    validation_df["target"]
    .to_numpy(dtype="int8")
)

X_calibration_fixed = imputer.transform(
    calibration_df[predictor_columns]
).astype("float32")

y_calibration_fixed = (
    calibration_df["target"]
    .to_numpy(dtype="int8")
)

training_medians = np.asarray(
    imputer.statistics_,
    dtype=np.float32
)

Step 3: Recreate the fixed calibration split

In [ ]:
calibration_hash = pd.util.hash_pandas_object(
    calibration_df[predictor_columns],
    index=False
).to_numpy(dtype="uint64")

calibrator_mask = (
    calibration_hash % 2 == 0
)

policy_mask = ~calibrator_mask

X_calibrator_base = X_calibration_fixed[
    calibrator_mask
]

y_calibrator_base = y_calibration_fixed[
    calibrator_mask
]

X_policy_base = X_calibration_fixed[
    policy_mask
]

y_policy_base = y_calibration_fixed[
    policy_mask
]

Step 4: Recreate semantic-group indices

In [ ]:
with open(
    checkpoint_dir /
    "experiment_metadata.json"
) as file:
    metadata = json.load(file)

predictor_columns = metadata["predictors"]
semantic_groups = metadata["semantic_groups"]

group_names = list(
    semantic_groups.keys()
)

feature_index = {
    feature: position
    for position, feature
    in enumerate(predictor_columns)
}

group_indices = {
    group: [
        feature_index[feature]
        for feature
        in semantic_groups[group]
    ]
    for group in group_names
}

availability_names = [
    f"available__{group}"
    for group in group_names
]

Step 5: Define fixed augmentation functions

In [ ]:
def create_confirmatory_training_data(
    X,
    y,
    seed
):
    X = np.asarray(X, dtype=np.float32)
    y = np.asarray(y, dtype=np.int8)

    number_rows = len(X)
    number_groups = len(group_names)

    rng = np.random.default_rng(seed)

    assigned_groups = rng.integers(
        0,
        number_groups,
        size=number_rows
    )

    X_masked = X.copy()

    masked_availability = np.ones(
        (number_rows, number_groups),
        dtype=np.float32
    )

    assignment_counts = {}

    for group_number, group in enumerate(
        group_names
    ):
        rows = np.where(
            assigned_groups == group_number
        )[0]

        columns = group_indices[group]

        X_masked[np.ix_(rows, columns)] = (
            training_medians[columns]
        )

        masked_availability[
            rows,
            group_number
        ] = 0.0

        assignment_counts[group] = int(
            len(rows)
        )

    complete_availability = np.ones(
        (number_rows, number_groups),
        dtype=np.float32
    )

    X_augmented = np.vstack([
        np.hstack([
            X,
            complete_availability
        ]),
        np.hstack([
            X_masked,
            masked_availability
        ])
    ])

    y_augmented = np.concatenate([
        y,
        y
    ])

    return (
        X_augmented,
        y_augmented,
        assignment_counts
    )


def create_all_known_conditions(X, y):
    X = np.asarray(X, dtype=np.float32)
    y = np.asarray(y, dtype=np.int8)

    X_versions = []
    y_versions = []

    complete_indicators = np.ones(
        (len(X), len(group_names)),
        dtype=np.float32
    )

    X_versions.append(
        np.hstack([
            X,
            complete_indicators
        ])
    )

    y_versions.append(y)

    for group_number, group in enumerate(
        group_names
    ):
        X_masked = X.copy()
        columns = group_indices[group]

        X_masked[:, columns] = (
            training_medians[columns]
        )

        indicators = np.ones(
            (len(X), len(group_names)),
            dtype=np.float32
        )

        indicators[:, group_number] = 0.0

        X_versions.append(
            np.hstack([
                X_masked,
                indicators
            ])
        )

        y_versions.append(y)

    return (
        np.vstack(X_versions),
        np.concatenate(y_versions)
    )

Step 6: Create fixed group-aware validation and calibration arrays
These conditions remain identical across all five seeds.

In [ ]:
X_group_validation, y_group_validation = (
    create_all_known_conditions(
        X_validation_fixed,
        y_validation_fixed
    )
)

X_group_calibrator, y_group_calibrator = (
    create_all_known_conditions(
        X_calibrator_base,
        y_calibrator_base
    )
)

X_group_policy, y_group_policy = (
    create_all_known_conditions(
        X_policy_base,
        y_policy_base
    )
)

In [ ]:
X_train_fixed = imputer.transform(
    train_df[predictor_columns]
).astype("float32")

y_train_fixed = (
    train_df["target"]
    .to_numpy(dtype="int8")
)

X_validation_fixed = imputer.transform(
    validation_df[predictor_columns]
).astype("float32")

y_validation_fixed = (
    validation_df["target"]
    .to_numpy(dtype="int8")
)

X_calibration_fixed = imputer.transform(
    calibration_df[predictor_columns]
).astype("float32")

y_calibration_fixed = (
    calibration_df["target"]
    .to_numpy(dtype="int8")
)

training_medians = np.asarray(
    imputer.statistics_,
    dtype=np.float32
)

calibration_hash = pd.util.hash_pandas_object(
    calibration_df[predictor_columns],
    index=False
).to_numpy(dtype="uint64")

calibrator_mask = (
    calibration_hash % 2 == 0
)

policy_mask = ~calibrator_mask

X_calibrator_base = X_calibration_fixed[
    calibrator_mask
]

y_calibrator_base = y_calibration_fixed[
    calibrator_mask
]

X_policy_base = X_calibration_fixed[
    policy_mask
]

y_policy_base = y_calibration_fixed[
    policy_mask
]

print("Fixed training:", X_train_fixed.shape)
print("Fixed validation:", X_validation_fixed.shape)
print("Fixed calibration:", X_calibration_fixed.shape)
print("Calibrator subset:", X_calibrator_base.shape)
print("Policy subset:", X_policy_base.shape)

Step 7: Verify preparation

In [ ]:
print("Fixed training:", X_train_fixed.shape)
print("Fixed validation:", X_validation_fixed.shape)
print("Fixed calibration:", X_calibration_fixed.shape)

print(
    "Group validation:",
    X_group_validation.shape
)

print(
    "Group calibrator:",
    X_group_calibrator.shape
)

print(
    "Group policy:",
    X_group_policy.shape
)

print("Semantic groups:", len(group_names))
print("Training medians:", len(training_medians))

Fixed training: (598043, 77)
Fixed validation: (152964, 77)
Fixed calibration: (99084, 77)
Group validation: (764820, 81)
Group calibrator: (244445, 81)
Group policy: (250975, 81)
Semantic groups: 4
Training medians: 77

Fixed training: (598043, 77)
Fixed validation: (152964, 77)
Fixed calibration: (99084, 77)
Calibrator subset: (48889, 77)
Policy subset: (50195, 77)

Preparation is correct. We can now define the restartable training function and run the first confirmatory seed, 2027. This stage does not load or evaluate the target dataset.

1. Define calibration and policy helpers

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    precision_recall_curve,
    brier_score_loss,
    log_loss
)
import numpy as np
import pandas as pd
import joblib
import json
import time
import gc

def probability_to_logit(probability):
    probability = np.clip(
        probability,
        1e-7,
        1 - 1e-7
    )

    return np.log(
        probability / (1 - probability)
    ).reshape(-1, 1)


def expected_calibration_error(
    y_true,
    probability,
    bins=15
):
    y_true = np.asarray(y_true)
    edges = np.linspace(0, 1, bins + 1)
    ece = 0.0

    for lower, upper in zip(
        edges[:-1],
        edges[1:]
    ):
        if upper == 1:
            selected = (
                (probability >= lower) &
                (probability <= upper)
            )
        else:
            selected = (
                (probability >= lower) &
                (probability < upper)
            )

        count = selected.sum()

        if count == 0:
            continue

        ece += (
            count / len(y_true)
        ) * abs(
            np.mean(y_true[selected])
            - np.mean(probability[selected])
        )

    return float(ece)


def fit_platt_and_policy(
    model,
    X_calibrator,
    y_calibrator,
    X_policy,
    y_policy,
    seed
):
    raw_calibrator_probability = (
        model.predict_proba(
            X_calibrator
        )[:, 1]
    )

    calibrator = LogisticRegression(
        C=1_000_000,
        solver="lbfgs",
        max_iter=1000,
        random_state=seed
    )

    calibrator.fit(
        probability_to_logit(
            raw_calibrator_probability
        ),
        y_calibrator
    )

    raw_policy_probability = (
        model.predict_proba(
            X_policy
        )[:, 1]
    )

    calibrated_policy_probability = (
        calibrator.predict_proba(
            probability_to_logit(
                raw_policy_probability
            )
        )[:, 1]
    )

    precision_values, recall_values, thresholds = (
        precision_recall_curve(
            y_policy,
            calibrated_policy_probability
        )
    )

    f1_values = (
        2
        * precision_values[:-1]
        * recall_values[:-1]
        /
        (
            precision_values[:-1]
            + recall_values[:-1]
            + 1e-12
        )
    )

    best_position = int(
        np.argmax(f1_values)
    )

    classification_threshold = float(
        thresholds[best_position]
    )

    policy_confidence = np.maximum(
        calibrated_policy_probability,
        1 - calibrated_policy_probability
    )

    confidence_cutoffs = {
        str(coverage): float(
            np.quantile(
                policy_confidence,
                1 - coverage
            )
        )
        for coverage in [
            0.80,
            0.90,
            0.95
        ]
    }

    calibration_metrics = {
        "raw": {
            "brier": float(
                brier_score_loss(
                    y_policy,
                    raw_policy_probability
                )
            ),
            "logloss": float(
                log_loss(
                    y_policy,
                    raw_policy_probability
                )
            ),
            "ece": expected_calibration_error(
                y_policy,
                raw_policy_probability
            )
        },
        "platt_calibrated": {
            "brier": float(
                brier_score_loss(
                    y_policy,
                    calibrated_policy_probability
                )
            ),
            "logloss": float(
                log_loss(
                    y_policy,
                    calibrated_policy_probability
                )
            ),
            "ece": expected_calibration_error(
                y_policy,
                calibrated_policy_probability
            )
        }
    }

    policy = {
        "classification_threshold":
            classification_threshold,
        "policy_f1": float(
            f1_values[best_position]
        ),
        "confidence_cutoffs":
            confidence_cutoffs,
        "calibration_method":
            "Platt scaling",
        "seed": seed,
        "target_data_used": False
    }

    return (
        calibrator,
        policy,
        calibration_metrics
    )

2. Define the fixed XGBoost configuration

In [ ]:
def create_fixed_xgboost(seed):
    return xgb.XGBClassifier(
        objective="binary:logistic",
        n_estimators=1200,
        learning_rate=0.05,
        max_depth=6,
        min_child_weight=5,
        subsample=0.80,
        colsample_bytree=0.80,
        reg_alpha=0.01,
        reg_lambda=1.0,
        tree_method="hist",
        device="cpu",
        eval_metric="logloss",
        early_stopping_rounds=50,
        random_state=seed,
        n_jobs=-1
    )

3. Define the restartable seed-training function

In [ ]:
def train_confirmatory_seed(seed):
    seed_dir = (
        replication_dir /
        f"seed_{seed}"
    )

    seed_dir.mkdir(
        parents=True,
        exist_ok=True
    )

    completion_file = (
        seed_dir /
        "TRAINING_COMPLETE.json"
    )

    if completion_file.exists():
        print(
            f"Seed {seed} is already complete."
        )
        return

    summary = {
        "seed": seed,
        "target_data_used": False
    }

    print("\n" + "=" * 70)
    print("CONFIRMATORY SEED:", seed)
    print("=" * 70)

    # ------------------------------------------------
    # Ordinary baseline
    # ------------------------------------------------
    print("\nTraining ordinary baseline")

    baseline_start = time.time()

    baseline_model_seed = (
        create_fixed_xgboost(seed)
    )

    baseline_model_seed.fit(
        X_train_fixed,
        y_train_fixed,
        eval_set=[
            (
                X_validation_fixed,
                y_validation_fixed
            )
        ],
        verbose=50
    )

    baseline_time = (
        time.time() - baseline_start
    )

    baseline_model_seed.save_model(
        str(
            seed_dir /
            "ordinary_baseline_xgboost.json"
        )
    )

    (
        baseline_calibrator_seed,
        baseline_policy_seed,
        baseline_calibration_metrics
    ) = fit_platt_and_policy(
        model=baseline_model_seed,
        X_calibrator=X_calibrator_base,
        y_calibrator=y_calibrator_base,
        X_policy=X_policy_base,
        y_policy=y_policy_base,
        seed=seed
    )

    joblib.dump(
        baseline_calibrator_seed,
        seed_dir /
        "ordinary_baseline_platt.joblib"
    )

    with open(
        seed_dir /
        "ordinary_baseline_policy.json",
        "w"
    ) as file:
        json.dump(
            baseline_policy_seed,
            file,
            indent=2
        )

    with open(
        seed_dir /
        "ordinary_baseline_calibration.json",
        "w"
    ) as file:
        json.dump(
            baseline_calibration_metrics,
            file,
            indent=2
        )

    summary["ordinary_baseline"] = {
        "training_time_seconds":
            baseline_time,
        "best_iteration": int(
            baseline_model_seed.best_iteration
        ),
        "best_validation_logloss": float(
            baseline_model_seed.best_score
        ),
        "classification_threshold":
            baseline_policy_seed[
                "classification_threshold"
            ],
        "policy_f1":
            baseline_policy_seed[
                "policy_f1"
            ]
    }

    print(
        "Baseline completed in",
        round(baseline_time, 1),
        "seconds"
    )

    # ------------------------------------------------
    # Group-aware model
    # ------------------------------------------------
    print("\nCreating group-aware training data")

    (
        X_group_train,
        y_group_train,
        assignment_counts
    ) = create_confirmatory_training_data(
        X_train_fixed,
        y_train_fixed,
        seed
    )

    print(
        "Group-aware training shape:",
        X_group_train.shape
    )

    print(
        "Mask assignment counts:",
        assignment_counts
    )

    print("\nTraining group-aware model")

    group_start = time.time()

    group_model_seed = (
        create_fixed_xgboost(seed)
    )

    group_model_seed.fit(
        X_group_train,
        y_group_train,
        eval_set=[
            (
                X_group_validation,
                y_group_validation
            )
        ],
        verbose=50
    )

    group_time = (
        time.time() - group_start
    )

    group_model_seed.save_model(
        str(
            seed_dir /
            "group_aware_xgboost.json"
        )
    )

    del X_group_train
    del y_group_train
    gc.collect()

    (
        group_calibrator_seed,
        group_policy_seed,
        group_calibration_metrics
    ) = fit_platt_and_policy(
        model=group_model_seed,
        X_calibrator=X_group_calibrator,
        y_calibrator=y_group_calibrator,
        X_policy=X_group_policy,
        y_policy=y_group_policy,
        seed=seed
    )

    joblib.dump(
        group_calibrator_seed,
        seed_dir /
        "group_aware_platt.joblib"
    )

    with open(
        seed_dir /
        "group_aware_policy.json",
        "w"
    ) as file:
        json.dump(
            group_policy_seed,
            file,
            indent=2
        )

    with open(
        seed_dir /
        "group_aware_calibration.json",
        "w"
    ) as file:
        json.dump(
            group_calibration_metrics,
            file,
            indent=2
        )

    summary["group_aware"] = {
        "training_time_seconds":
            group_time,
        "best_iteration": int(
            group_model_seed.best_iteration
        ),
        "best_validation_logloss": float(
            group_model_seed.best_score
        ),
        "classification_threshold":
            group_policy_seed[
                "classification_threshold"
            ],
        "policy_f1":
            group_policy_seed[
                "policy_f1"
            ],
        "single_mask_assignment_counts":
            assignment_counts
    }

    with open(
        seed_dir /
        "training_summary.json",
        "w"
    ) as file:
        json.dump(
            summary,
            file,
            indent=2
        )

    with open(
        completion_file,
        "w"
    ) as file:
        json.dump(
            {
                "seed": seed,
                "status":
                    "training_complete",
                "target_data_used": False
            },
            file,
            indent=2
        )

    print(
        "Group-aware model completed in",
        round(group_time, 1),
        "seconds"
    )

    print(
        f"\nSeed {seed} training and "
        "source-only policy creation complete."
    )

    del baseline_model_seed
    del baseline_calibrator_seed
    del group_model_seed
    del group_calibrator_seed

    gc.collect()

4. Run the first confirmatory seed

In [ ]:
train_confirmatory_seed(2027)

======================================================================
CONFIRMATORY SEED: 2027
======================================================================

Training ordinary baseline
[0]	validation_0-logloss:0.46597
[50]	validation_0-logloss:0.04144
[100]	validation_0-logloss:0.01470
[150]	validation_0-logloss:0.00724
[200]	validation_0-logloss:0.00462
[250]	validation_0-logloss:0.00356
[300]	validation_0-logloss:0.00303
[350]	validation_0-logloss:0.00276
[400]	validation_0-logloss:0.00261
[450]	validation_0-logloss:0.00250
[500]	validation_0-logloss:0.00242
[550]	validation_0-logloss:0.00238
[600]	validation_0-logloss:0.00235
[650]	validation_0-logloss:0.00232
[700]	validation_0-logloss:0.00229
[750]	validation_0-logloss:0.00227
[800]	validation_0-logloss:0.00226
[850]	validation_0-logloss:0.00225
[900]	validation_0-logloss:0.00224
[950]	validation_0-logloss:0.00223
[1000]	validation_0-logloss:0.00222
[1046]	validation_0-logloss:0.00222
Baseline completed in 247.9 seconds

Creating group-aware training data
Group-aware training shape: (1196086, 81)
Mask assignment counts: {'G1_Packet_Byte_Magnitude': 149302, 'G2_Temporal_Activity': 149765, 'G3_TCP_Control_Flags': 149712, 'G4_Rate_Header_Flow_Context': 149264}

Training group-aware model
[0]	validation_0-logloss:0.47370
[50]	validation_0-logloss:0.08182
[100]	validation_0-logloss:0.04344
[150]	validation_0-logloss:0.02850
[200]	validation_0-logloss:0.02180
[250]	validation_0-logloss:0.01971
[300]	validation_0-logloss:0.01867
[350]	validation_0-logloss:0.01829
[400]	validation_0-logloss:0.01834
[404]	validation_0-logloss:0.01835
Group-aware model completed in 232.8 seconds

Seed 2027 training and source-only policy creation complete.

Seed 2027 completed correctly.

Baseline training: 247.9 seconds
Group-aware training: 232.8 seconds
Total: approximately 8 minutes
Mask assignments are balanced at approximately 149,000 rows per group.
Early stopping worked for both models.
No target data was used.

First verify its saved checkpoint:

In [ ]:
seed_2027_dir = (
    replication_dir / "seed_2027"
)

required_seed_files = [
    "ordinary_baseline_xgboost.json",
    "ordinary_baseline_platt.joblib",
    "ordinary_baseline_policy.json",
    "ordinary_baseline_calibration.json",
    "group_aware_xgboost.json",
    "group_aware_platt.joblib",
    "group_aware_policy.json",
    "group_aware_calibration.json",
    "training_summary.json",
    "TRAINING_COMPLETE.json"
]

for filename in required_seed_files:
    path = seed_2027_dir / filename

    print(
        filename,
        "FOUND" if path.exists() else "MISSING",
        f"{path.stat().st_size / 1024:.1f} KiB"
        if path.exists() else ""
    )

ordinary_baseline_xgboost.json FOUND 2783.7 KiB
ordinary_baseline_platt.joblib FOUND 0.8 KiB
ordinary_baseline_policy.json FOUND 0.3 KiB
ordinary_baseline_calibration.json FOUND 0.3 KiB
group_aware_xgboost.json FOUND 1459.6 KiB
group_aware_platt.joblib FOUND 0.8 KiB
group_aware_policy.json FOUND 0.3 KiB
group_aware_calibration.json FOUND 0.3 KiB
training_summary.json FOUND 0.7 KiB
TRAINING_COMPLETE.json FOUND 0.1 KiB

If all ten files show FOUND, run the remaining four seeds:

In [ ]:
remaining_seeds = [
    2028,
    2029,
    2030,
    2031
]

for seed in remaining_seeds:
    train_confirmatory_seed(seed)

======================================================================
CONFIRMATORY SEED: 2028
======================================================================

Training ordinary baseline
[0]	validation_0-logloss:0.46538
[50]	validation_0-logloss:0.04203
[100]	validation_0-logloss:0.01458
[150]	validation_0-logloss:0.00784
[200]	validation_0-logloss:0.00467
[250]	validation_0-logloss:0.00360
[300]	validation_0-logloss:0.00308
[350]	validation_0-logloss:0.00277
[400]	validation_0-logloss:0.00260
[450]	validation_0-logloss:0.00250
[500]	validation_0-logloss:0.00242
[550]	validation_0-logloss:0.00237
[600]	validation_0-logloss:0.00233
[650]	validation_0-logloss:0.00231
[700]	validation_0-logloss:0.00229
[750]	validation_0-logloss:0.00226
[800]	validation_0-logloss:0.00225
[850]	validation_0-logloss:0.00224
[900]	validation_0-logloss:0.00223
[950]	validation_0-logloss:0.00222
[1000]	validation_0-logloss:0.00222
[1050]	validation_0-logloss:0.00221
[1100]	validation_0-logloss:0.00221
[1150]	validation_0-logloss:0.00221
[1199]	validation_0-logloss:0.00221
Baseline completed in 270.8 seconds

Creating group-aware training data
Group-aware training shape: (1196086, 81)
Mask assignment counts: {'G1_Packet_Byte_Magnitude': 148823, 'G2_Temporal_Activity': 150055, 'G3_TCP_Control_Flags': 149501, 'G4_Rate_Header_Flow_Context': 149664}

Training group-aware model
[0]	validation_0-logloss:0.47375
[50]	validation_0-logloss:0.08129
[100]	validation_0-logloss:0.04289
[150]	validation_0-logloss:0.02887
[200]	validation_0-logloss:0.02219
[250]	validation_0-logloss:0.01911
[300]	validation_0-logloss:0.01788
[350]	validation_0-logloss:0.01783
[395]	validation_0-logloss:0.01757
Group-aware model completed in 227.1 seconds

Seed 2028 training and source-only policy creation complete.

======================================================================
CONFIRMATORY SEED: 2029
======================================================================

Training ordinary baseline
[0]	validation_0-logloss:0.46600
[50]	validation_0-logloss:0.04077
[100]	validation_0-logloss:0.01397
[150]	validation_0-logloss:0.00747
[200]	validation_0-logloss:0.00482
[250]	validation_0-logloss:0.00361
[300]	validation_0-logloss:0.00304
[350]	validation_0-logloss:0.00276
[400]	validation_0-logloss:0.00261
[450]	validation_0-logloss:0.00249
[500]	validation_0-logloss:0.00243
[550]	validation_0-logloss:0.00238
[600]	validation_0-logloss:0.00234
[650]	validation_0-logloss:0.00231
[700]	validation_0-logloss:0.00229
[750]	validation_0-logloss:0.00227
[800]	validation_0-logloss:0.00226
[850]	validation_0-logloss:0.00225
[900]	validation_0-logloss:0.00224
[950]	validation_0-logloss:0.00223
[1000]	validation_0-logloss:0.00222
[1050]	validation_0-logloss:0.00222
[1066]	validation_0-logloss:0.00222
Baseline completed in 231.8 seconds

Creating group-aware training data
Group-aware training shape: (1196086, 81)
Mask assignment counts: {'G1_Packet_Byte_Magnitude': 149531, 'G2_Temporal_Activity': 149478, 'G3_TCP_Control_Flags': 149884, 'G4_Rate_Header_Flow_Context': 149150}

Training group-aware model
[0]	validation_0-logloss:0.47261
[50]	validation_0-logloss:0.08289
[100]	validation_0-logloss:0.04495
[150]	validation_0-logloss:0.02959
[200]	validation_0-logloss:0.02342
[250]	validation_0-logloss:0.02043
[300]	validation_0-logloss:0.01920
[350]	validation_0-logloss:0.01863
[400]	validation_0-logloss:0.01833
[450]	validation_0-logloss:0.01861
[452]	validation_0-logloss:0.01861
Group-aware model completed in 253.3 seconds

Seed 2029 training and source-only policy creation complete.

======================================================================
CONFIRMATORY SEED: 2030
======================================================================

Training ordinary baseline
[0]	validation_0-logloss:0.46598
[50]	validation_0-logloss:0.04150
[100]	validation_0-logloss:0.01442
[150]	validation_0-logloss:0.00786
[200]	validation_0-logloss:0.00488
[250]	validation_0-logloss:0.00378
[300]	validation_0-logloss:0.00309
[350]	validation_0-logloss:0.00279
[400]	validation_0-logloss:0.00262
[450]	validation_0-logloss:0.00252
[500]	validation_0-logloss:0.00244
[550]	validation_0-logloss:0.00239
[600]	validation_0-logloss:0.00235
[650]	validation_0-logloss:0.00233
[700]	validation_0-logloss:0.00231
[750]	validation_0-logloss:0.00230
[800]	validation_0-logloss:0.00228
[850]	validation_0-logloss:0.00227
[900]	validation_0-logloss:0.00226
[950]	validation_0-logloss:0.00225
[1000]	validation_0-logloss:0.00224
[1050]	validation_0-logloss:0.00223
[1100]	validation_0-logloss:0.00223
[1150]	validation_0-logloss:0.00223
[1199]	validation_0-logloss:0.00223
Baseline completed in 259.3 seconds

Creating group-aware training data
Group-aware training shape: (1196086, 81)
Mask assignment counts: {'G1_Packet_Byte_Magnitude': 149489, 'G2_Temporal_Activity': 149119, 'G3_TCP_Control_Flags': 149853, 'G4_Rate_Header_Flow_Context': 149582}

Training group-aware model
[0]	validation_0-logloss:0.47403
[50]	validation_0-logloss:0.08007
[100]	validation_0-logloss:0.04263
[150]	validation_0-logloss:0.02892
[200]	validation_0-logloss:0.02212
[250]	validation_0-logloss:0.01885
[300]	validation_0-logloss:0.01794
[350]	validation_0-logloss:0.01757
[367]	validation_0-logloss:0.01760
Group-aware model completed in 209.7 seconds

Seed 2030 training and source-only policy creation complete.

======================================================================
CONFIRMATORY SEED: 2031
======================================================================

Training ordinary baseline
[0]	validation_0-logloss:0.46527
[50]	validation_0-logloss:0.04190
[100]	validation_0-logloss:0.01409
[150]	validation_0-logloss:0.00757
[200]	validation_0-logloss:0.00461
[250]	validation_0-logloss:0.00354
[300]	validation_0-logloss:0.00301
[350]	validation_0-logloss:0.00275
[400]	validation_0-logloss:0.00260
[450]	validation_0-logloss:0.00249
[500]	validation_0-logloss:0.00242
[550]	validation_0-logloss:0.00238
[600]	validation_0-logloss:0.00235
[650]	validation_0-logloss:0.00233
[700]	validation_0-logloss:0.00231
[750]	validation_0-logloss:0.00229
[800]	validation_0-logloss:0.00227
[850]	validation_0-logloss:0.00226
[900]	validation_0-logloss:0.00225
[950]	validation_0-logloss:0.00224
[1000]	validation_0-logloss:0.00224
[1034]	validation_0-logloss:0.00224
Baseline completed in 226.5 seconds

Creating group-aware training data
Group-aware training shape: (1196086, 81)
Mask assignment counts: {'G1_Packet_Byte_Magnitude': 149448, 'G2_Temporal_Activity': 149728, 'G3_TCP_Control_Flags': 149402, 'G4_Rate_Header_Flow_Context': 149465}

Training group-aware model
[0]	validation_0-logloss:0.47347
[50]	validation_0-logloss:0.08316
[100]	validation_0-logloss:0.04340
[150]	validation_0-logloss:0.02973
[200]	validation_0-logloss:0.02318
[250]	validation_0-logloss:0.01991
[300]	validation_0-logloss:0.01884
[350]	validation_0-logloss:0.01846
[400]	validation_0-logloss:0.01812
[450]	validation_0-logloss:0.01860
[463]	validation_0-logloss:0.01882
Group-aware model completed in 263.2 seconds

Seed 2031 training and source-only policy creation complete.

All five confirmatory models are now trained successfully. The runs look consistent, and the mask assignments are balanced.

Seeds 2028 and 2030 reached the fixed 1,200-tree limit for the baseline. We must keep them unchanged because the protocol is frozen.

Next, verify every seed and prepare the fixed source and target evaluation arrays.

1. Verify all seed checkpoints

In [ ]:
confirmatory_seeds = [
    2027,
    2028,
    2029,
    2030,
    2031
]

required_training_files = [
    "ordinary_baseline_xgboost.json",
    "ordinary_baseline_platt.joblib",
    "ordinary_baseline_policy.json",
    "ordinary_baseline_calibration.json",
    "group_aware_xgboost.json",
    "group_aware_platt.joblib",
    "group_aware_policy.json",
    "group_aware_calibration.json",
    "training_summary.json",
    "TRAINING_COMPLETE.json"
]

seed_verification = []

for seed in confirmatory_seeds:
    seed_dir = (
        replication_dir /
        f"seed_{seed}"
    )

    missing = [
        filename
        for filename in required_training_files
        if not (
            seed_dir / filename
        ).exists()
    ]

    with open(
        seed_dir /
        "training_summary.json"
    ) as file:
        summary = json.load(file)

    seed_verification.append({
        "seed": seed,
        "missing_files": len(missing),
        "baseline_best_iteration":
            summary["ordinary_baseline"][
                "best_iteration"
            ],
        "baseline_logloss":
            summary["ordinary_baseline"][
                "best_validation_logloss"
            ],
        "group_best_iteration":
            summary["group_aware"][
                "best_iteration"
            ],
        "group_logloss":
            summary["group_aware"][
                "best_validation_logloss"
            ],
        "baseline_time_seconds":
            summary["ordinary_baseline"][
                "training_time_seconds"
            ],
        "group_time_seconds":
            summary["group_aware"][
                "training_time_seconds"
            ]
    })

    print(
        f"Seed {seed}:",
        "COMPLETE"
        if not missing
        else f"MISSING {missing}"
    )

seed_verification = pd.DataFrame(
    seed_verification
)

display(
    seed_verification.round(6)
)

Seed 2027: COMPLETE
Seed 2028: COMPLETE
Seed 2029: COMPLETE
Seed 2030: COMPLETE
Seed 2031: COMPLETE

,seed,missing_files,baseline_best_iteration,baseline_logloss,group_best_iteration,group_logloss,baseline_time_seconds,group_time_seconds
0,2027,0,996,0.002219,354,0.018228,247.905686,232.834294
1,2028,0,1191,0.002205,345,0.017529,270.794407,227.110944
2,2029,0,1016,0.002216,402,0.018317,231.795113,253.303139
3,2030,0,1174,0.002226,317,0.017565,259.326117,209.725457
4,2031,0,984,0.002238,413,0.017990,226.482059,263.166730

Every seed must show COMPLETE and missing_files = 0.

2. Save the training verification table

In [ ]:
seed_verification.to_csv(
    replication_dir /
    "five_seed_training_verification.csv",
    index=False
)

3. Clear training-only arrays

In [ ]:
objects_to_clear = [
    "X_train_fixed",
    "y_train_fixed",
    "X_validation_fixed",
    "y_validation_fixed",
    "X_calibration_fixed",
    "y_calibration_fixed",
    "X_group_validation",
    "y_group_validation",
    "X_group_calibrator",
    "y_group_calibrator",
    "X_group_policy",
    "y_group_policy",
    "train_df",
    "validation_df",
    "calibration_df"
]

for object_name in objects_to_clear:
    globals().pop(object_name, None)

gc.collect()

print("Training-only memory cleared.")

Training-only memory cleared.

4. Load the frozen evaluation datasets

In [ ]:
source_test_df = pd.read_parquet(
    checkpoint_dir /
    "source_test.parquet"
)

target_test_df = pd.read_parquet(
    checkpoint_dir /
    "target_test_sealed.parquet"
)

X_source_test_fixed = imputer.transform(
    source_test_df[predictor_columns]
).astype("float32")

y_source_test_fixed = (
    source_test_df["target"]
    .to_numpy(dtype="int8")
)

X_target_test_fixed = imputer.transform(
    target_test_df[predictor_columns]
).astype("float32")

y_target_test_fixed = (
    target_test_df["target"]
    .to_numpy(dtype="int8")
)

5. Verify evaluation data

In [ ]:
print(
    "Source test:",
    X_source_test_fixed.shape
)

print(
    "Target test:",
    X_target_test_fixed.shape
)

print(
    "Source attack rate:",
    round(
        y_source_test_fixed.mean(),
        6
    )
)

print(
    "Target attack rate:",
    round(
        y_target_test_fixed.mean(),
        6
    )
)

print(
    "Remaining source NaN:",
    np.isnan(
        X_source_test_fixed
    ).sum()
)

print(
    "Remaining target NaN:",
    np.isnan(
        X_target_test_fixed
    ).sum()
)

Source test: (150178, 77)
Target test: (999143, 77)
Source attack rate: 0.203265
Target attack rate: 0.169215
Remaining source NaN: 0
Remaining target NaN: 0

In [ ]:
from pathlib import Path

checkpoint_dir = Path(
    "/content/drive/MyDrive/research/researchdata/"
    "NIDS_Research/NIDS_Research_Checkpoints"
)

replication_dir = (
    checkpoint_dir /
    "five_seed_confirmatory_replication"
)

seeds = [2027, 2028, 2029, 2030, 2031]

training_files = [
    "ordinary_baseline_xgboost.json",
    "ordinary_baseline_platt.joblib",
    "ordinary_baseline_policy.json",
    "ordinary_baseline_calibration.json",
    "group_aware_xgboost.json",
    "group_aware_platt.joblib",
    "group_aware_policy.json",
    "group_aware_calibration.json",
    "training_summary.json",
    "TRAINING_COMPLETE.json"
]

evaluation_files = [
    "confirmatory_nonselective_results.csv",
    "confirmatory_selective_results.csv",
    "confirmatory_paired_counts.csv",
    "EVALUATION_COMPLETE.json"
]

for seed in seeds:
    seed_dir = replication_dir / f"seed_{seed}"

    missing_training = [
        filename
        for filename in training_files
        if not (seed_dir / filename).exists()
    ]

    missing_evaluation = [
        filename
        for filename in evaluation_files
        if not (seed_dir / filename).exists()
    ]

    print("\nSeed:", seed)

    print(
        "Training:",
        "COMPLETE"
        if not missing_training
        else f"MISSING {missing_training}"
    )

    print(
        "Evaluation:",
        "COMPLETE"
        if not missing_evaluation
        else f"NOT COMPLETE — missing {missing_evaluation}"
    )

Seed: 2027
Training: COMPLETE
Evaluation: NOT COMPLETE — missing ['confirmatory_nonselective_results.csv', 'confirmatory_selective_results.csv', 'confirmatory_paired_counts.csv', 'EVALUATION_COMPLETE.json']

Seed: 2028
Training: COMPLETE
Evaluation: NOT COMPLETE — missing ['confirmatory_nonselective_results.csv', 'confirmatory_selective_results.csv', 'confirmatory_paired_counts.csv', 'EVALUATION_COMPLETE.json']

Seed: 2029
Training: COMPLETE
Evaluation: NOT COMPLETE — missing ['confirmatory_nonselective_results.csv', 'confirmatory_selective_results.csv', 'confirmatory_paired_counts.csv', 'EVALUATION_COMPLETE.json']

Seed: 2030
Training: COMPLETE
Evaluation: NOT COMPLETE — missing ['confirmatory_nonselective_results.csv', 'confirmatory_selective_results.csv', 'confirmatory_paired_counts.csv', 'EVALUATION_COMPLETE.json']

Seed: 2031
Training: COMPLETE
Evaluation: NOT COMPLETE — missing ['confirmatory_nonselective_results.csv', 'confirmatory_selective_results.csv', 'confirmatory_paired_counts.csv', 'EVALUATION_COMPLETE.json']

In [ ]:
%run /content/confirmatory_five_seed_evaluation.py

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Source test: (150178, 77)
Target test: (999143, 77)
Source attack rate: 0.203265
Target attack rate: 0.169215

======================================================================
EVALUATING SEED: 2027
======================================================================
source | complete | None | 7.2 seconds
source | single | G1_Packet_Byte_Magnitude | 8.1 seconds
source | single | G2_Temporal_Activity | 5.3 seconds
source | single | G3_TCP_Control_Flags | 6.0 seconds
source | single | G4_Rate_Header_Flow_Context | 7.2 seconds
source | pairwise_unseen | G1_Packet_Byte_Magnitude+G2_Temporal_Activity | 5.5 seconds
source | pairwise_unseen | G1_Packet_Byte_Magnitude+G3_TCP_Control_Flags | 7.7 seconds
source | pairwise_unseen | G1_Packet_Byte_Magnitude+G4_Rate_Header_Flow_Context | 5.3 seconds
source | pairwise_unseen | G2_Temporal_Activity+G3_TCP_Control_Flags | 5.4 seconds
source | pairwise_unseen | G2_Temporal_Activity+G4_Rate_Header_Flow_Context | 7.8 seconds
source | pairwise_unseen | G3_TCP_Control_Flags+G4_Rate_Header_Flow_Context | 5.2 seconds
target | complete | None | 41.9 seconds
target | single | G1_Packet_Byte_Magnitude | 38.8 seconds
target | single | G2_Temporal_Activity | 41.8 seconds
target | single | G3_TCP_Control_Flags | 39.6 seconds
target | single | G4_Rate_Header_Flow_Context | 39.6 seconds
target | pairwise_unseen | G1_Packet_Byte_Magnitude+G2_Temporal_Activity | 39.7 seconds
target | pairwise_unseen | G1_Packet_Byte_Magnitude+G3_TCP_Control_Flags | 39.4 seconds
target | pairwise_unseen | G1_Packet_Byte_Magnitude+G4_Rate_Header_Flow_Context | 38.8 seconds
target | pairwise_unseen | G2_Temporal_Activity+G3_TCP_Control_Flags | 38.0 seconds
target | pairwise_unseen | G2_Temporal_Activity+G4_Rate_Header_Flow_Context | 40.9 seconds
target | pairwise_unseen | G3_TCP_Control_Flags+G4_Rate_Header_Flow_Context | 38.3 seconds
Seed 2027 evaluation completed in 507.7 seconds.

======================================================================
EVALUATING SEED: 2028
======================================================================
source | complete | None | 8.1 seconds
source | single | G1_Packet_Byte_Magnitude | 6.4 seconds
source | single | G2_Temporal_Activity | 6.8 seconds
source | single | G3_TCP_Control_Flags | 7.5 seconds
source | single | G4_Rate_Header_Flow_Context | 5.7 seconds
source | pairwise_unseen | G1_Packet_Byte_Magnitude+G2_Temporal_Activity | 8.4 seconds
source | pairwise_unseen | G1_Packet_Byte_Magnitude+G3_TCP_Control_Flags | 5.8 seconds
source | pairwise_unseen | G1_Packet_Byte_Magnitude+G4_Rate_Header_Flow_Context | 7.8 seconds
source | pairwise_unseen | G2_Temporal_Activity+G3_TCP_Control_Flags | 6.0 seconds
source | pairwise_unseen | G2_Temporal_Activity+G4_Rate_Header_Flow_Context | 6.2 seconds
source | pairwise_unseen | G3_TCP_Control_Flags+G4_Rate_Header_Flow_Context | 7.4 seconds
target | complete | None | 43.1 seconds
target | single | G1_Packet_Byte_Magnitude | 42.5 seconds
target | single | G2_Temporal_Activity | 45.8 seconds
target | single | G3_TCP_Control_Flags | 45.5 seconds
target | single | G4_Rate_Header_Flow_Context | 43.2 seconds
target | pairwise_unseen | G1_Packet_Byte_Magnitude+G2_Temporal_Activity | 43.4 seconds
target | pairwise_unseen | G1_Packet_Byte_Magnitude+G3_TCP_Control_Flags | 45.7 seconds
target | pairwise_unseen | G1_Packet_Byte_Magnitude+G4_Rate_Header_Flow_Context | 45.0 seconds
target | pairwise_unseen | G2_Temporal_Activity+G3_TCP_Control_Flags | 45.9 seconds
target | pairwise_unseen | G2_Temporal_Activity+G4_Rate_Header_Flow_Context | 42.1 seconds
target | pairwise_unseen | G3_TCP_Control_Flags+G4_Rate_Header_Flow_Context | 44.9 seconds
Seed 2028 evaluation completed in 563.2 seconds.

======================================================================
EVALUATING SEED: 2029
======================================================================
source | complete | None | 5.8 seconds
source | single | G1_Packet_Byte_Magnitude | 7.6 seconds
source | single | G2_Temporal_Activity | 5.4 seconds
source | single | G3_TCP_Control_Flags | 7.5 seconds
source | single | G4_Rate_Header_Flow_Context | 5.5 seconds
source | pairwise_unseen | G1_Packet_Byte_Magnitude+G2_Temporal_Activity | 5.5 seconds
source | pairwise_unseen | G1_Packet_Byte_Magnitude+G3_TCP_Control_Flags | 7.9 seconds
source | pairwise_unseen | G1_Packet_Byte_Magnitude+G4_Rate_Header_Flow_Context | 5.2 seconds
source | pairwise_unseen | G2_Temporal_Activity+G3_TCP_Control_Flags | 7.5 seconds
source | pairwise_unseen | G2_Temporal_Activity+G4_Rate_Header_Flow_Context | 5.6 seconds
source | pairwise_unseen | G3_TCP_Control_Flags+G4_Rate_Header_Flow_Context | 5.2 seconds
target | complete | None | 42.7 seconds
target | single | G1_Packet_Byte_Magnitude | 40.4 seconds
target | single | G2_Temporal_Activity | 42.1 seconds
target | single | G3_TCP_Control_Flags | 43.0 seconds
target | single | G4_Rate_Header_Flow_Context | 39.3 seconds
target | pairwise_unseen | G1_Packet_Byte_Magnitude+G2_Temporal_Activity | 45.2 seconds
target | pairwise_unseen | G1_Packet_Byte_Magnitude+G3_TCP_Control_Flags | 39.8 seconds
target | pairwise_unseen | G1_Packet_Byte_Magnitude+G4_Rate_Header_Flow_Context | 41.5 seconds
target | pairwise_unseen | G2_Temporal_Activity+G3_TCP_Control_Flags | 43.9 seconds
target | pairwise_unseen | G2_Temporal_Activity+G4_Rate_Header_Flow_Context | 40.3 seconds
target | pairwise_unseen | G3_TCP_Control_Flags+G4_Rate_Header_Flow_Context | 42.2 seconds
Seed 2029 evaluation completed in 529.2 seconds.

======================================================================
EVALUATING SEED: 2030
======================================================================
source | complete | None | 5.5 seconds
source | single | G1_Packet_Byte_Magnitude | 6.8 seconds
source | single | G2_Temporal_Activity | 7.1 seconds
source | single | G3_TCP_Control_Flags | 5.7 seconds
source | single | G4_Rate_Header_Flow_Context | 8.2 seconds
source | pairwise_unseen | G1_Packet_Byte_Magnitude+G2_Temporal_Activity | 5.7 seconds
source | pairwise_unseen | G1_Packet_Byte_Magnitude+G3_TCP_Control_Flags | 7.3 seconds
source | pairwise_unseen | G1_Packet_Byte_Magnitude+G4_Rate_Header_Flow_Context | 6.2 seconds
source | pairwise_unseen | G2_Temporal_Activity+G3_TCP_Control_Flags | 5.8 seconds
source | pairwise_unseen | G2_Temporal_Activity+G4_Rate_Header_Flow_Context | 8.1 seconds
source | pairwise_unseen | G3_TCP_Control_Flags+G4_Rate_Header_Flow_Context | 5.7 seconds
target | complete | None | 44.4 seconds
target | single | G1_Packet_Byte_Magnitude | 44.4 seconds
target | single | G2_Temporal_Activity | 42.5 seconds
target | single | G3_TCP_Control_Flags | 45.1 seconds
target | single | G4_Rate_Header_Flow_Context | 42.7 seconds
target | pairwise_unseen | G1_Packet_Byte_Magnitude+G2_Temporal_Activity | 42.7 seconds
target | pairwise_unseen | G1_Packet_Byte_Magnitude+G3_TCP_Control_Flags | 46.0 seconds
target | pairwise_unseen | G1_Packet_Byte_Magnitude+G4_Rate_Header_Flow_Context | 44.2 seconds
target | pairwise_unseen | G2_Temporal_Activity+G3_TCP_Control_Flags | 43.4 seconds
target | pairwise_unseen | G2_Temporal_Activity+G4_Rate_Header_Flow_Context | 42.7 seconds
target | pairwise_unseen | G3_TCP_Control_Flags+G4_Rate_Header_Flow_Context | 45.0 seconds
Seed 2030 evaluation completed in 555.2 seconds.

======================================================================
EVALUATING SEED: 2031
======================================================================
source | complete | None | 5.5 seconds
source | single | G1_Packet_Byte_Magnitude | 8.0 seconds
source | single | G2_Temporal_Activity | 5.4 seconds
source | single | G3_TCP_Control_Flags | 5.8 seconds
source | single | G4_Rate_Header_Flow_Context | 7.1 seconds
source | pairwise_unseen | G1_Packet_Byte_Magnitude+G2_Temporal_Activity | 5.3 seconds
source | pairwise_unseen | G1_Packet_Byte_Magnitude+G3_TCP_Control_Flags | 8.0 seconds
source | pairwise_unseen | G1_Packet_Byte_Magnitude+G4_Rate_Header_Flow_Context | 5.2 seconds
source | pairwise_unseen | G2_Temporal_Activity+G3_TCP_Control_Flags | 5.9 seconds
source | pairwise_unseen | G2_Temporal_Activity+G4_Rate_Header_Flow_Context | 7.4 seconds
source | pairwise_unseen | G3_TCP_Control_Flags+G4_Rate_Header_Flow_Context | 5.2 seconds
target | complete | None | 41.3 seconds
target | single | G1_Packet_Byte_Magnitude | 39.3 seconds
target | single | G2_Temporal_Activity | 42.0 seconds
target | single | G3_TCP_Control_Flags | 38.7 seconds
target | single | G4_Rate_Header_Flow_Context | 40.6 seconds
target | pairwise_unseen | G1_Packet_Byte_Magnitude+G2_Temporal_Activity | 40.0 seconds
target | pairwise_unseen | G1_Packet_Byte_Magnitude+G3_TCP_Control_Flags | 42.7 seconds
target | pairwise_unseen | G1_Packet_Byte_Magnitude+G4_Rate_Header_Flow_Context | 37.9 seconds
target | pairwise_unseen | G2_Temporal_Activity+G3_TCP_Control_Flags | 43.0 seconds
target | pairwise_unseen | G2_Temporal_Activity+G4_Rate_Header_Flow_Context | 38.7 seconds
target | pairwise_unseen | G3_TCP_Control_Flags+G4_Rate_Header_Flow_Context | 42.1 seconds
Seed 2031 evaluation completed in 515.1 seconds.

Combined outputs saved:
Non-selective rows: 220
Selective rows: 660
Paired rows: 110

Five-seed confirmatory evaluation is complete.

You can stop for today. Do not start the two-hour experiment now.

Before closing:

Download and keep
frozen_component_ablation.py.
Preferably upload it to the same Google Drive research folder.
Your previous five-seed results are already saved in Drive.

Next working session, open Colab and run:

In [ ]:
%run "/content/drive/MyDrive/research/researchdata/NIDS_Research/frozen_component_ablation.py"

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Frozen component-ablation protocol saved: /content/drive/MyDrive/research/researchdata/NIDS_Research/NIDS_Research_Checkpoints/five_seed_confirmatory_replication/component_ablation/component_ablation_protocol_frozen.json

Source-only development data
Training: (598043, 77)
Validation: (152964, 77)
Calibrator fit: (48889, 77)
Policy selection: (50195, 77)

========================================================================
TRAINING SEED 2027 | indicators_only
========================================================================
Training shape: (598043, 81)
Validation shape: (152964, 81)
Mask counts: {'complete': 598043}
[0]	validation_0-logloss:0.27213
[50]	validation_0-logloss:0.00258
[100]	validation_0-logloss:0.00218
[150]	validation_0-logloss:0.00213
[197]	validation_0-logloss:0.00214
Seed 2027 | indicators_only: model saved after 45.1 seconds.
Seed 2027 | indicators_only: source-only calibrator saved.
Seed 2027 | indicators_only: source-only policy saved; threshold=0.344387.
Seed 2027 | indicators_only: TRAINING COMPLETE.

========================================================================
TRAINING SEED 2027 | augmentation_only
========================================================================
Training shape: (1196086, 77)
Validation shape: (764820, 77)
Mask counts: {'G1_Packet_Byte_Magnitude': 149302, 'G2_Temporal_Activity': 149765, 'G3_TCP_Control_Flags': 149712, 'G4_Rate_Header_Flow_Context': 149264}
[0]	validation_0-logloss:0.31265
[50]	validation_0-logloss:0.01715
[100]	validation_0-logloss:0.01925
[122]	validation_0-logloss:0.01957
Seed 2027 | augmentation_only: model saved after 70.8 seconds.
Seed 2027 | augmentation_only: source-only calibrator saved.
Seed 2027 | augmentation_only: source-only policy saved; threshold=0.655060.
Seed 2027 | augmentation_only: TRAINING COMPLETE.

========================================================================
TRAINING SEED 2028 | indicators_only
========================================================================
Training shape: (598043, 81)
Validation shape: (152964, 81)
Mask counts: {'complete': 598043}
[0]	validation_0-logloss:0.27213
[50]	validation_0-logloss:0.00258
[100]	validation_0-logloss:0.00218
[150]	validation_0-logloss:0.00213
[197]	validation_0-logloss:0.00214
Seed 2028 | indicators_only: model saved after 48.6 seconds.
Seed 2028 | indicators_only: source-only calibrator saved.
Seed 2028 | indicators_only: source-only policy saved; threshold=0.344387.
Seed 2028 | indicators_only: TRAINING COMPLETE.

========================================================================
TRAINING SEED 2028 | augmentation_only
========================================================================
Training shape: (1196086, 77)
Validation shape: (764820, 77)
Mask counts: {'G1_Packet_Byte_Magnitude': 148823, 'G2_Temporal_Activity': 150055, 'G3_TCP_Control_Flags': 149501, 'G4_Rate_Header_Flow_Context': 149664}
[0]	validation_0-logloss:0.31258
[50]	validation_0-logloss:0.01709
[100]	validation_0-logloss:0.01817
[102]	validation_0-logloss:0.01804
Seed 2028 | augmentation_only: model saved after 61.4 seconds.
Seed 2028 | augmentation_only: source-only calibrator saved.
Seed 2028 | augmentation_only: source-only policy saved; threshold=0.578222.
Seed 2028 | augmentation_only: TRAINING COMPLETE.

========================================================================
TRAINING SEED 2029 | indicators_only
========================================================================
Training shape: (598043, 81)
Validation shape: (152964, 81)
Mask counts: {'complete': 598043}
[0]	validation_0-logloss:0.27213
[50]	validation_0-logloss:0.00258
[100]	validation_0-logloss:0.00218
[150]	validation_0-logloss:0.00213
[197]	validation_0-logloss:0.00214
Seed 2029 | indicators_only: model saved after 45.7 seconds.
Seed 2029 | indicators_only: source-only calibrator saved.
Seed 2029 | indicators_only: source-only policy saved; threshold=0.344387.
Seed 2029 | indicators_only: TRAINING COMPLETE.

========================================================================
TRAINING SEED 2029 | augmentation_only
========================================================================
Training shape: (1196086, 77)
Validation shape: (764820, 77)
Mask counts: {'G1_Packet_Byte_Magnitude': 149531, 'G2_Temporal_Activity': 149478, 'G3_TCP_Control_Flags': 149884, 'G4_Rate_Header_Flow_Context': 149150}
[0]	validation_0-logloss:0.31276
[50]	validation_0-logloss:0.01955
[100]	validation_0-logloss:0.01861
[117]	validation_0-logloss:0.01870
Seed 2029 | augmentation_only: model saved after 68.9 seconds.
Seed 2029 | augmentation_only: source-only calibrator saved.
Seed 2029 | augmentation_only: source-only policy saved; threshold=0.616834.
Seed 2029 | augmentation_only: TRAINING COMPLETE.

========================================================================
TRAINING SEED 2030 | indicators_only
========================================================================
Training shape: (598043, 81)
Validation shape: (152964, 81)
Mask counts: {'complete': 598043}
[0]	validation_0-logloss:0.27213
[50]	validation_0-logloss:0.00258
[100]	validation_0-logloss:0.00218
[150]	validation_0-logloss:0.00213
[197]	validation_0-logloss:0.00214
Seed 2030 | indicators_only: model saved after 48.1 seconds.
Seed 2030 | indicators_only: source-only calibrator saved.
Seed 2030 | indicators_only: source-only policy saved; threshold=0.344387.
Seed 2030 | indicators_only: TRAINING COMPLETE.

========================================================================
TRAINING SEED 2030 | augmentation_only
========================================================================
Training shape: (1196086, 77)
Validation shape: (764820, 77)
Mask counts: {'G1_Packet_Byte_Magnitude': 149489, 'G2_Temporal_Activity': 149119, 'G3_TCP_Control_Flags': 149853, 'G4_Rate_Header_Flow_Context': 149582}
[0]	validation_0-logloss:0.31272
[50]	validation_0-logloss:0.01733
[100]	validation_0-logloss:0.01815
[106]	validation_0-logloss:0.01802
Seed 2030 | augmentation_only: model saved after 65.1 seconds.
Seed 2030 | augmentation_only: source-only calibrator saved.
Seed 2030 | augmentation_only: source-only policy saved; threshold=0.618091.
Seed 2030 | augmentation_only: TRAINING COMPLETE.

========================================================================
TRAINING SEED 2031 | indicators_only
========================================================================
Training shape: (598043, 81)
Validation shape: (152964, 81)
Mask counts: {'complete': 598043}
[0]	validation_0-logloss:0.27213
[50]	validation_0-logloss:0.00258
[100]	validation_0-logloss:0.00218
[150]	validation_0-logloss:0.00213
[197]	validation_0-logloss:0.00214
Seed 2031 | indicators_only: model saved after 46.4 seconds.
Seed 2031 | indicators_only: source-only calibrator saved.
Seed 2031 | indicators_only: source-only policy saved; threshold=0.344387.
Seed 2031 | indicators_only: TRAINING COMPLETE.

========================================================================
TRAINING SEED 2031 | augmentation_only
========================================================================
Training shape: (1196086, 77)
Validation shape: (764820, 77)
Mask counts: {'G1_Packet_Byte_Magnitude': 149448, 'G2_Temporal_Activity': 149728, 'G3_TCP_Control_Flags': 149402, 'G4_Rate_Header_Flow_Context': 149465}
[0]	validation_0-logloss:0.31265
[50]	validation_0-logloss:0.01867
[100]	validation_0-logloss:0.01856
[114]	validation_0-logloss:0.01864
Seed 2031 | augmentation_only: model saved after 66.6 seconds.
Seed 2031 | augmentation_only: source-only calibrator saved.
Seed 2031 | augmentation_only: source-only policy saved; threshold=0.634428.
Seed 2031 | augmentation_only: TRAINING COMPLETE.

All ten ablation models and source-only policies are frozen.
Source test: (150178, 77) | attack rate: 0.203265
Target test: (999143, 77) | attack rate: 0.169215

========================================================================
EVALUATING SEED 2027 | indicators_only
========================================================================
source | complete | None | 0.9 seconds
source | single | G1_Packet_Byte_Magnitude | 0.9 seconds
source | single | G2_Temporal_Activity | 1.3 seconds
source | single | G3_TCP_Control_Flags | 1.5 seconds
source | single | G4_Rate_Header_Flow_Context | 1.4 seconds
source | pairwise_unseen | G1_Packet_Byte_Magnitude+G2_Temporal_Activity | 1.4 seconds
source | pairwise_unseen | G1_Packet_Byte_Magnitude+G3_TCP_Control_Flags | 0.9 seconds
source | pairwise_unseen | G1_Packet_Byte_Magnitude+G4_Rate_Header_Flow_Context | 0.9 seconds
source | pairwise_unseen | G2_Temporal_Activity+G3_TCP_Control_Flags | 0.9 seconds
source | pairwise_unseen | G2_Temporal_Activity+G4_Rate_Header_Flow_Context | 0.8 seconds
source | pairwise_unseen | G3_TCP_Control_Flags+G4_Rate_Header_Flow_Context | 0.8 seconds
target | complete | None | 5.3 seconds
target | single | G1_Packet_Byte_Magnitude | 7.9 seconds
target | single | G2_Temporal_Activity | 5.6 seconds
target | single | G3_TCP_Control_Flags | 7.5 seconds
target | single | G4_Rate_Header_Flow_Context | 5.0 seconds
target | pairwise_unseen | G1_Packet_Byte_Magnitude+G2_Temporal_Activity | 6.8 seconds
target | pairwise_unseen | G1_Packet_Byte_Magnitude+G3_TCP_Control_Flags | 6.9 seconds
target | pairwise_unseen | G1_Packet_Byte_Magnitude+G4_Rate_Header_Flow_Context | 5.4 seconds
target | pairwise_unseen | G2_Temporal_Activity+G3_TCP_Control_Flags | 8.1 seconds
target | pairwise_unseen | G2_Temporal_Activity+G4_Rate_Header_Flow_Context | 5.2 seconds
target | pairwise_unseen | G3_TCP_Control_Flags+G4_Rate_Header_Flow_Context | 6.4 seconds
Seed 2027 | indicators_only: evaluation completed in 81.8 seconds.

========================================================================
EVALUATING SEED 2027 | augmentation_only
========================================================================
source | complete | None | 1.0 seconds
source | single | G1_Packet_Byte_Magnitude | 0.9 seconds
source | single | G2_Temporal_Activity | 0.7 seconds
source | single | G3_TCP_Control_Flags | 0.7 seconds
source | single | G4_Rate_Header_Flow_Context | 0.6 seconds
source | pairwise_unseen | G1_Packet_Byte_Magnitude+G2_Temporal_Activity | 0.7 seconds
source | pairwise_unseen | G1_Packet_Byte_Magnitude+G3_TCP_Control_Flags | 0.7 seconds
source | pairwise_unseen | G1_Packet_Byte_Magnitude+G4_Rate_Header_Flow_Context | 0.6 seconds
source | pairwise_unseen | G2_Temporal_Activity+G3_TCP_Control_Flags | 0.7 seconds
source | pairwise_unseen | G2_Temporal_Activity+G4_Rate_Header_Flow_Context | 0.6 seconds
source | pairwise_unseen | G3_TCP_Control_Flags+G4_Rate_Header_Flow_Context | 0.7 seconds
target | complete | None | 4.1 seconds
target | single | G1_Packet_Byte_Magnitude | 5.9 seconds
target | single | G2_Temporal_Activity | 4.1 seconds
target | single | G3_TCP_Control_Flags | 4.1 seconds
target | single | G4_Rate_Header_Flow_Context | 6.0 seconds
target | pairwise_unseen | G1_Packet_Byte_Magnitude+G2_Temporal_Activity | 4.4 seconds
target | pairwise_unseen | G1_Packet_Byte_Magnitude+G3_TCP_Control_Flags | 4.3 seconds
target | pairwise_unseen | G1_Packet_Byte_Magnitude+G4_Rate_Header_Flow_Context | 5.8 seconds
target | pairwise_unseen | G2_Temporal_Activity+G3_TCP_Control_Flags | 4.4 seconds
target | pairwise_unseen | G2_Temporal_Activity+G4_Rate_Header_Flow_Context | 4.1 seconds
target | pairwise_unseen | G3_TCP_Control_Flags+G4_Rate_Header_Flow_Context | 5.3 seconds
Seed 2027 | augmentation_only: evaluation completed in 60.4 seconds.

========================================================================
EVALUATING SEED 2028 | indicators_only
========================================================================
source | complete | None | 1.4 seconds
source | single | G1_Packet_Byte_Magnitude | 0.9 seconds
source | single | G2_Temporal_Activity | 0.9 seconds
source | single | G3_TCP_Control_Flags | 0.9 seconds
source | single | G4_Rate_Header_Flow_Context | 0.8 seconds
source | pairwise_unseen | G1_Packet_Byte_Magnitude+G2_Temporal_Activity | 0.9 seconds
source | pairwise_unseen | G1_Packet_Byte_Magnitude+G3_TCP_Control_Flags | 0.9 seconds
source | pairwise_unseen | G1_Packet_Byte_Magnitude+G4_Rate_Header_Flow_Context | 0.8 seconds
source | pairwise_unseen | G2_Temporal_Activity+G3_TCP_Control_Flags | 0.9 seconds
source | pairwise_unseen | G2_Temporal_Activity+G4_Rate_Header_Flow_Context | 0.8 seconds
source | pairwise_unseen | G3_TCP_Control_Flags+G4_Rate_Header_Flow_Context | 0.8 seconds
target | complete | None | 7.5 seconds
target | single | G1_Packet_Byte_Magnitude | 5.8 seconds
target | single | G2_Temporal_Activity | 6.9 seconds
target | single | G3_TCP_Control_Flags | 5.9 seconds
target | single | G4_Rate_Header_Flow_Context | 5.0 seconds
target | pairwise_unseen | G1_Packet_Byte_Magnitude+G2_Temporal_Activity | 8.2 seconds
target | pairwise_unseen | G1_Packet_Byte_Magnitude+G3_TCP_Control_Flags | 5.9 seconds
target | pairwise_unseen | G1_Packet_Byte_Magnitude+G4_Rate_Header_Flow_Context | 7.6 seconds
target | pairwise_unseen | G2_Temporal_Activity+G3_TCP_Control_Flags | 5.7 seconds
target | pairwise_unseen | G2_Temporal_Activity+G4_Rate_Header_Flow_Context | 5.9 seconds
target | pairwise_unseen | G3_TCP_Control_Flags+G4_Rate_Header_Flow_Context | 6.2 seconds
Seed 2028 | indicators_only: evaluation completed in 80.7 seconds.

========================================================================
EVALUATING SEED 2028 | augmentation_only
========================================================================
source | complete | None | 0.6 seconds
source | single | G1_Packet_Byte_Magnitude | 0.6 seconds
source | single | G2_Temporal_Activity | 0.6 seconds
source | single | G3_TCP_Control_Flags | 0.6 seconds
source | single | G4_Rate_Header_Flow_Context | 0.6 seconds
source | pairwise_unseen | G1_Packet_Byte_Magnitude+G2_Temporal_Activity | 0.6 seconds
source | pairwise_unseen | G1_Packet_Byte_Magnitude+G3_TCP_Control_Flags | 0.6 seconds
source | pairwise_unseen | G1_Packet_Byte_Magnitude+G4_Rate_Header_Flow_Context | 0.6 seconds
source | pairwise_unseen | G2_Temporal_Activity+G3_TCP_Control_Flags | 0.6 seconds
source | pairwise_unseen | G2_Temporal_Activity+G4_Rate_Header_Flow_Context | 0.6 seconds
source | pairwise_unseen | G3_TCP_Control_Flags+G4_Rate_Header_Flow_Context | 0.6 seconds
target | complete | None | 5.5 seconds
target | single | G1_Packet_Byte_Magnitude | 3.8 seconds
target | single | G2_Temporal_Activity | 3.8 seconds
target | single | G3_TCP_Control_Flags | 4.7 seconds
target | single | G4_Rate_Header_Flow_Context | 4.3 seconds
target | pairwise_unseen | G1_Packet_Byte_Magnitude+G2_Temporal_Activity | 4.0 seconds
target | pairwise_unseen | G1_Packet_Byte_Magnitude+G3_TCP_Control_Flags | 4.0 seconds
target | pairwise_unseen | G1_Packet_Byte_Magnitude+G4_Rate_Header_Flow_Context | 5.1 seconds
target | pairwise_unseen | G2_Temporal_Activity+G3_TCP_Control_Flags | 4.0 seconds
target | pairwise_unseen | G2_Temporal_Activity+G4_Rate_Header_Flow_Context | 3.8 seconds
target | pairwise_unseen | G3_TCP_Control_Flags+G4_Rate_Header_Flow_Context | 4.9 seconds
Seed 2028 | augmentation_only: evaluation completed in 54.7 seconds.

========================================================================
EVALUATING SEED 2029 | indicators_only
========================================================================
source | complete | None | 1.4 seconds
source | single | G1_Packet_Byte_Magnitude | 1.0 seconds
source | single | G2_Temporal_Activity | 0.9 seconds
source | single | G3_TCP_Control_Flags | 0.9 seconds
source | single | G4_Rate_Header_Flow_Context | 0.8 seconds
source | pairwise_unseen | G1_Packet_Byte_Magnitude+G2_Temporal_Activity | 0.9 seconds
source | pairwise_unseen | G1_Packet_Byte_Magnitude+G3_TCP_Control_Flags | 0.9 seconds
source | pairwise_unseen | G1_Packet_Byte_Magnitude+G4_Rate_Header_Flow_Context | 0.8 seconds
source | pairwise_unseen | G2_Temporal_Activity+G3_TCP_Control_Flags | 0.9 seconds
source | pairwise_unseen | G2_Temporal_Activity+G4_Rate_Header_Flow_Context | 0.8 seconds
source | pairwise_unseen | G3_TCP_Control_Flags+G4_Rate_Header_Flow_Context | 0.8 seconds
target | complete | None | 7.4 seconds
target | single | G1_Packet_Byte_Magnitude | 5.8 seconds
target | single | G2_Temporal_Activity | 6.7 seconds
target | single | G3_TCP_Control_Flags | 6.1 seconds
target | single | G4_Rate_Header_Flow_Context | 5.0 seconds
target | pairwise_unseen | G1_Packet_Byte_Magnitude+G2_Temporal_Activity | 8.5 seconds
target | pairwise_unseen | G1_Packet_Byte_Magnitude+G3_TCP_Control_Flags | 6.0 seconds
target | pairwise_unseen | G1_Packet_Byte_Magnitude+G4_Rate_Header_Flow_Context | 7.5 seconds
target | pairwise_unseen | G2_Temporal_Activity+G3_TCP_Control_Flags | 5.7 seconds
target | pairwise_unseen | G2_Temporal_Activity+G4_Rate_Header_Flow_Context | 5.6 seconds
target | pairwise_unseen | G3_TCP_Control_Flags+G4_Rate_Header_Flow_Context | 6.5 seconds
Seed 2029 | indicators_only: evaluation completed in 81.0 seconds.

========================================================================
EVALUATING SEED 2029 | augmentation_only
========================================================================
source | complete | None | 0.6 seconds
source | single | G1_Packet_Byte_Magnitude | 0.7 seconds
source | single | G2_Temporal_Activity | 0.7 seconds
source | single | G3_TCP_Control_Flags | 0.6 seconds
source | single | G4_Rate_Header_Flow_Context | 0.6 seconds
source | pairwise_unseen | G1_Packet_Byte_Magnitude+G2_Temporal_Activity | 0.7 seconds
source | pairwise_unseen | G1_Packet_Byte_Magnitude+G3_TCP_Control_Flags | 0.7 seconds
source | pairwise_unseen | G1_Packet_Byte_Magnitude+G4_Rate_Header_Flow_Context | 0.6 seconds
source | pairwise_unseen | G2_Temporal_Activity+G3_TCP_Control_Flags | 0.7 seconds
source | pairwise_unseen | G2_Temporal_Activity+G4_Rate_Header_Flow_Context | 0.6 seconds
source | pairwise_unseen | G3_TCP_Control_Flags+G4_Rate_Header_Flow_Context | 0.7 seconds
target | complete | None | 5.9 seconds
target | single | G1_Packet_Byte_Magnitude | 4.0 seconds
target | single | G2_Temporal_Activity | 4.3 seconds
target | single | G3_TCP_Control_Flags | 7.8 seconds
target | single | G4_Rate_Header_Flow_Context | 4.1 seconds
target | pairwise_unseen | G1_Packet_Byte_Magnitude+G2_Temporal_Activity | 4.4 seconds
target | pairwise_unseen | G1_Packet_Byte_Magnitude+G3_TCP_Control_Flags | 5.8 seconds
target | pairwise_unseen | G1_Packet_Byte_Magnitude+G4_Rate_Header_Flow_Context | 4.1 seconds
target | pairwise_unseen | G2_Temporal_Activity+G3_TCP_Control_Flags | 4.3 seconds
target | pairwise_unseen | G2_Temporal_Activity+G4_Rate_Header_Flow_Context | 4.9 seconds
target | pairwise_unseen | G3_TCP_Control_Flags+G4_Rate_Header_Flow_Context | 4.9 seconds
Seed 2029 | augmentation_only: evaluation completed in 61.8 seconds.

========================================================================
EVALUATING SEED 2030 | indicators_only
========================================================================
source | complete | None | 0.9 seconds
source | single | G1_Packet_Byte_Magnitude | 0.9 seconds
source | single | G2_Temporal_Activity | 0.9 seconds
source | single | G3_TCP_Control_Flags | 0.9 seconds
source | single | G4_Rate_Header_Flow_Context | 0.8 seconds
source | pairwise_unseen | G1_Packet_Byte_Magnitude+G2_Temporal_Activity | 0.9 seconds
source | pairwise_unseen | G1_Packet_Byte_Magnitude+G3_TCP_Control_Flags | 0.9 seconds
source | pairwise_unseen | G1_Packet_Byte_Magnitude+G4_Rate_Header_Flow_Context | 0.9 seconds
source | pairwise_unseen | G2_Temporal_Activity+G3_TCP_Control_Flags | 0.9 seconds
source | pairwise_unseen | G2_Temporal_Activity+G4_Rate_Header_Flow_Context | 1.3 seconds

The verification audit is ready:

In [ ]:
%run "/content/drive/MyDrive/research/researchdata/NIDS_Research/audit_component_ablation_models.py"

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Auditing seed 2027 | ordinary_baseline
Auditing seed 2027 | full_method
Auditing seed 2027 | indicators_only
Auditing seed 2027 | augmentation_only
Auditing seed 2028 | ordinary_baseline
Auditing seed 2028 | full_method
Auditing seed 2028 | indicators_only
Auditing seed 2028 | augmentation_only
Auditing seed 2029 | ordinary_baseline
Auditing seed 2029 | full_method
Auditing seed 2029 | indicators_only
Auditing seed 2029 | augmentation_only
Auditing seed 2030 | ordinary_baseline
Auditing seed 2030 | full_method
Auditing seed 2030 | indicators_only
Auditing seed 2030 | augmentation_only
Auditing seed 2031 | ordinary_baseline
Auditing seed 2031 | full_method
Auditing seed 2031 | indicators_only
Auditing seed 2031 | augmentation_only

========================================================================
COMPONENT-ABLATION AUDIT: PASS
========================================================================
Models audited: 20 / 20
Errors: 0
Warnings: 1
WARNING: Indicators-only trees are identical across seeds. This is consistent with deterministic complete-only training and constant all-one indicator columns, but it should be disclosed.

Hash uniqueness across five seeds:
ordinary_baseline {'model_hashes': 5, 'tree_hashes': 5, 'calibrator_hashes': 5, 'policy_hashes': 5}
full_method {'model_hashes': 5, 'tree_hashes': 5, 'calibrator_hashes': 5, 'policy_hashes': 5}
indicators_only {'model_hashes': 1, 'tree_hashes': 1, 'calibrator_hashes': 5, 'policy_hashes': 5}
augmentation_only {'model_hashes': 5, 'tree_hashes': 5, 'calibrator_hashes': 5, 'policy_hashes': 5}

Saved: /content/drive/MyDrive/research/researchdata/NIDS_Research/NIDS_Research_Checkpoints/five_seed_confirmatory_replication/component_ablation/component_ablation_training_audit.csv
Saved: /content/drive/MyDrive/research/researchdata/NIDS_Research/NIDS_Research_Checkpoints/five_seed_confirmatory_replication/component_ablation/component_ablation_audit_report.json

The exact frozen parameters were recovered, and the corrected ablation script is ready:

frozen_component_ablation.py

Replace the previous script with this version, then run:

%run /content/frozen_component_ablation.py

The corrected experiment will:

use learning rate 0.05;
use max depth 6;
use minimum child weight 5;
use row and column sampling 0.8;
use regularization alpha 0.01;
save results separately under:
five_seed_confirmatory_replication/component_ablation_corrected/

Do not delete the old component_ablation directory. Estimated runtime is approximately 90–120 minutes. The script remains restartable.

After completion, send these files from the corrected directory:

component_ablation_primary_summary.csv
component_ablation_pairwise_seed_means.csv
component_ablation_selective90_seed_means.csv

In [ ]:
%run "/content/drive/MyDrive/research/researchdata/NIDS_Research/frozen_component_ablation.py"

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Frozen component-ablation protocol saved: /content/drive/MyDrive/research/researchdata/NIDS_Research/NIDS_Research_Checkpoints/five_seed_confirmatory_replication/component_ablation_corrected/component_ablation_protocol_frozen.json

Source-only development data
Training: (598043, 77)
Validation: (152964, 77)
Calibrator fit: (48889, 77)
Policy selection: (50195, 77)

========================================================================
TRAINING SEED 2027 | indicators_only
========================================================================
Training shape: (598043, 81)
Validation shape: (152964, 81)
Mask counts: {'complete': 598043}
[0]	validation_0-logloss:0.46597
[50]	validation_0-logloss:0.04157
[100]	validation_0-logloss:0.01467
[150]	validation_0-logloss:0.00787
[200]	validation_0-logloss:0.00478
[250]	validation_0-logloss:0.00373
[300]	validation_0-logloss:0.00312
[350]	validation_0-logloss:0.00280
[400]	validation_0-logloss:0.00264
[450]	validation_0-logloss:0.00251
[500]	validation_0-logloss:0.00241
[550]	validation_0-logloss:0.00237
[600]	validation_0-logloss:0.00233
[650]	validation_0-logloss:0.00230
[700]	validation_0-logloss:0.00228
[750]	validation_0-logloss:0.00227
[800]	validation_0-logloss:0.00225
[850]	validation_0-logloss:0.00225
[900]	validation_0-logloss:0.00224
[950]	validation_0-logloss:0.00222
[1000]	validation_0-logloss:0.00221
[1037]	validation_0-logloss:0.00221
Seed 2027 | indicators_only: model saved after 223.7 seconds.
Seed 2027 | indicators_only: source-only calibrator saved.
Seed 2027 | indicators_only: source-only policy saved; threshold=0.235870.
Seed 2027 | indicators_only: TRAINING COMPLETE.

========================================================================
TRAINING SEED 2027 | augmentation_only
========================================================================
Training shape: (1196086, 77)
Validation shape: (764820, 77)
Mask counts: {'G1_Packet_Byte_Magnitude': 149302, 'G2_Temporal_Activity': 149765, 'G3_TCP_Control_Flags': 149712, 'G4_Rate_Header_Flow_Context': 149264}
[0]	validation_0-logloss:0.47421
[50]	validation_0-logloss:0.08246
[100]	validation_0-logloss:0.04247
[150]	validation_0-logloss:0.02873
[200]	validation_0-logloss:0.02212
[250]	validation_0-logloss:0.01926
[300]	validation_0-logloss:0.01847
[350]	validation_0-logloss:0.01809
[400]	validation_0-logloss:0.01803
[450]	validation_0-logloss:0.01837
[461]	validation_0-logloss:0.01842
Seed 2027 | augmentation_only: model saved after 238.4 seconds.
Seed 2027 | augmentation_only: source-only calibrator saved.
Seed 2027 | augmentation_only: source-only policy saved; threshold=0.638348.
Seed 2027 | augmentation_only: TRAINING COMPLETE.

========================================================================
TRAINING SEED 2028 | indicators_only
========================================================================
Training shape: (598043, 81)
Validation shape: (152964, 81)
Mask counts: {'complete': 598043}
[0]	validation_0-logloss:0.46539
[50]	validation_0-logloss:0.04223
[100]	validation_0-logloss:0.01405
[150]	validation_0-logloss:0.00761
[200]	validation_0-logloss:0.00469
[250]	validation_0-logloss:0.00361
[300]	validation_0-logloss:0.00302
[350]	validation_0-logloss:0.00274
[400]	validation_0-logloss:0.00259
[450]	validation_0-logloss:0.00250
[500]	validation_0-logloss:0.00243
[550]	validation_0-logloss:0.00237
[600]	validation_0-logloss:0.00233
[650]	validation_0-logloss:0.00231
[700]	validation_0-logloss:0.00229
[750]	validation_0-logloss:0.00227
[800]	validation_0-logloss:0.00226
[850]	validation_0-logloss:0.00225
[900]	validation_0-logloss:0.00224
[950]	validation_0-logloss:0.00224
[1000]	validation_0-logloss:0.00223
[1050]	validation_0-logloss:0.00222
[1100]	validation_0-logloss:0.00222
[1150]	validation_0-logloss:0.00222
[1199]	validation_0-logloss:0.00221
Seed 2028 | indicators_only: model saved after 269.3 seconds.
Seed 2028 | indicators_only: source-only calibrator saved.
Seed 2028 | indicators_only: source-only policy saved; threshold=0.324288.
Seed 2028 | indicators_only: TRAINING COMPLETE.

========================================================================
TRAINING SEED 2028 | augmentation_only
========================================================================
Training shape: (1196086, 77)
Validation shape: (764820, 77)
Mask counts: {'G1_Packet_Byte_Magnitude': 148823, 'G2_Temporal_Activity': 150055, 'G3_TCP_Control_Flags': 149501, 'G4_Rate_Header_Flow_Context': 149664}
[0]	validation_0-logloss:0.47433
[50]	validation_0-logloss:0.08341
[100]	validation_0-logloss:0.04323
[150]	validation_0-logloss:0.02863
[200]	validation_0-logloss:0.02177
[250]	validation_0-logloss:0.01867
[300]	validation_0-logloss:0.01802
[350]	validation_0-logloss:0.01790
[400]	validation_0-logloss:0.01780
[438]	validation_0-logloss:0.01776
Seed 2028 | augmentation_only: model saved after 224.1 seconds.
Seed 2028 | augmentation_only: source-only calibrator saved.
Seed 2028 | augmentation_only: source-only policy saved; threshold=0.642486.
Seed 2028 | augmentation_only: TRAINING COMPLETE.

========================================================================
TRAINING SEED 2029 | indicators_only
========================================================================
Training shape: (598043, 81)
Validation shape: (152964, 81)
Mask counts: {'complete': 598043}
[0]	validation_0-logloss:0.46607
[50]	validation_0-logloss:0.04123
[100]	validation_0-logloss:0.01416
[150]	validation_0-logloss:0.00756
[200]	validation_0-logloss:0.00490
[250]	validation_0-logloss:0.00372
[300]	validation_0-logloss:0.00312
[350]	validation_0-logloss:0.00282
[400]	validation_0-logloss:0.00263
[450]	validation_0-logloss:0.00253
[500]	validation_0-logloss:0.00245
[550]	validation_0-logloss:0.00239
[600]	validation_0-logloss:0.00235
[650]	validation_0-logloss:0.00232
[700]	validation_0-logloss:0.00230
[750]	validation_0-logloss:0.00228
[800]	validation_0-logloss:0.00227
[850]	validation_0-logloss:0.00226
[900]	validation_0-logloss:0.00225
[950]	validation_0-logloss:0.00223
[1000]	validation_0-logloss:0.00223
[1050]	validation_0-logloss:0.00223
[1066]	validation_0-logloss:0.00223
Seed 2029 | indicators_only: model saved after 243.7 seconds.
Seed 2029 | indicators_only: source-only calibrator saved.
Seed 2029 | indicators_only: source-only policy saved; threshold=0.236581.
Seed 2029 | indicators_only: TRAINING COMPLETE.

========================================================================
TRAINING SEED 2029 | augmentation_only
========================================================================
Training shape: (1196086, 77)
Validation shape: (764820, 77)
Mask counts: {'G1_Packet_Byte_Magnitude': 149531, 'G2_Temporal_Activity': 149478, 'G3_TCP_Control_Flags': 149884, 'G4_Rate_Header_Flow_Context': 149150}
[0]	validation_0-logloss:0.47383
[50]	validation_0-logloss:0.08576
[100]	validation_0-logloss:0.04461
[150]	validation_0-logloss:0.02963
[200]	validation_0-logloss:0.02284
[250]	validation_0-logloss:0.01980
[300]	validation_0-logloss:0.01864
[350]	validation_0-logloss:0.01852
[368]	validation_0-logloss:0.01847
Seed 2029 | augmentation_only: model saved after 191.9 seconds.
Seed 2029 | augmentation_only: source-only calibrator saved.
Seed 2029 | augmentation_only: source-only policy saved; threshold=0.593811.
Seed 2029 | augmentation_only: TRAINING COMPLETE.

========================================================================
TRAINING SEED 2030 | indicators_only
========================================================================
Training shape: (598043, 81)
Validation shape: (152964, 81)
Mask counts: {'complete': 598043}
[0]	validation_0-logloss:0.46598
[50]	validation_0-logloss:0.04126
[100]	validation_0-logloss:0.01443
[150]	validation_0-logloss:0.00778
[200]	validation_0-logloss:0.00493
[250]	validation_0-logloss:0.00365
[300]	validation_0-logloss:0.00305
[350]	validation_0-logloss:0.00275
[400]	validation_0-logloss:0.00258
[450]	validation_0-logloss:0.00249
[500]	validation_0-logloss:0.00241
[550]	validation_0-logloss:0.00236
[600]	validation_0-logloss:0.00233
[650]	validation_0-logloss:0.00230
[700]	validation_0-logloss:0.00228
[750]	validation_0-logloss:0.00228
[800]	validation_0-logloss:0.00226
[850]	validation_0-logloss:0.00225
[900]	validation_0-logloss:0.00224
[950]	validation_0-logloss:0.00223
[1000]	validation_0-logloss:0.00221
[1050]	validation_0-logloss:0.00221
[1100]	validation_0-logloss:0.00221
[1150]	validation_0-logloss:0.00221
[1184]	validation_0-logloss:0.00221
Seed 2030 | indicators_only: model saved after 265.4 seconds.
Seed 2030 | indicators_only: source-only calibrator saved.
Seed 2030 | indicators_only: source-only policy saved; threshold=0.342566.
Seed 2030 | indicators_only: TRAINING COMPLETE.

========================================================================
TRAINING SEED 2030 | augmentation_only
========================================================================
Training shape: (1196086, 77)
Validation shape: (764820, 77)
Mask counts: {'G1_Packet_Byte_Magnitude': 149489, 'G2_Temporal_Activity': 149119, 'G3_TCP_Control_Flags': 149853, 'G4_Rate_Header_Flow_Context': 149582}
[0]	validation_0-logloss:0.47416
[50]	validation_0-logloss:0.08341
[100]	validation_0-logloss:0.04390
[150]	validation_0-logloss:0.02964
[200]	validation_0-logloss:0.02310
[250]	validation_0-logloss:0.01974
[300]	validation_0-logloss:0.01889
[350]	validation_0-logloss:0.01841
[376]	validation_0-logloss:0.01854
Seed 2030 | augmentation_only: model saved after 194.8 seconds.
Seed 2030 | augmentation_only: source-only calibrator saved.
Seed 2030 | augmentation_only: source-only policy saved; threshold=0.618416.
Seed 2030 | augmentation_only: TRAINING COMPLETE.

========================================================================
TRAINING SEED 2031 | indicators_only
========================================================================
Training shape: (598043, 81)
Validation shape: (152964, 81)
Mask counts: {'complete': 598043}
[0]	validation_0-logloss:0.46527
[50]	validation_0-logloss:0.04133
[100]	validation_0-logloss:0.01433
[150]	validation_0-logloss:0.00778
[200]	validation_0-logloss:0.00476
[250]	validation_0-logloss:0.00369
[300]	validation_0-logloss:0.00306
[350]	validation_0-logloss:0.00278
[400]	validation_0-logloss:0.00261
[450]	validation_0-logloss:0.00251
[500]	validation_0-logloss:0.00243
[550]	validation_0-logloss:0.00238
[600]	validation_0-logloss:0.00235
[650]	validation_0-logloss:0.00232
[700]	validation_0-logloss:0.00231
[750]	validation_0-logloss:0.00228
[800]	validation_0-logloss:0.00227
[850]	validation_0-logloss:0.00225
[900]	validation_0-logloss:0.00224
[950]	validation_0-logloss:0.00223
[1000]	validation_0-logloss:0.00223
[1050]	validation_0-logloss:0.00222
[1100]	validation_0-logloss:0.00221
[1150]	validation_0-logloss:0.00222
[1154]	validation_0-logloss:0.00222
Seed 2031 | indicators_only: model saved after 257.9 seconds.
Seed 2031 | indicators_only: source-only calibrator saved.
Seed 2031 | indicators_only: source-only policy saved; threshold=0.324144.
Seed 2031 | indicators_only: TRAINING COMPLETE.

========================================================================
TRAINING SEED 2031 | augmentation_only
========================================================================
Training shape: (1196086, 77)
Validation shape: (764820, 77)
Mask counts: {'G1_Packet_Byte_Magnitude': 149448, 'G2_Temporal_Activity': 149728, 'G3_TCP_Control_Flags': 149402, 'G4_Rate_Header_Flow_Context': 149465}
[0]	validation_0-logloss:0.47431
[50]	validation_0-logloss:0.08489
[100]	validation_0-logloss:0.04414
[150]	validation_0-logloss:0.02955
[200]	validation_0-logloss:0.02230
[250]	validation_0-logloss:0.01930
[300]	validation_0-logloss:0.01872
[350]	validation_0-logloss:0.01832
[400]	validation_0-logloss:0.01835
[436]	validation_0-logloss:0.01840
Seed 2031 | augmentation_only: model saved after 221.5 seconds.
Seed 2031 | augmentation_only: source-only calibrator saved.
Seed 2031 | augmentation_only: source-only policy saved; threshold=0.619845.
Seed 2031 | augmentation_only: TRAINING COMPLETE.

All ten ablation models and source-only policies are frozen.
Source test: (150178, 77) | attack rate: 0.203265
Target test: (999143, 77) | attack rate: 0.169215

========================================================================
EVALUATING SEED 2027 | indicators_only
========================================================================
source | complete | None | 3.3 seconds
source | single | G1_Packet_Byte_Magnitude | 3.3 seconds
source | single | G2_Temporal_Activity | 3.8 seconds
source | single | G3_TCP_Control_Flags | 5.0 seconds
source | single | G4_Rate_Header_Flow_Context | 3.2 seconds
source | pairwise_unseen | G1_Packet_Byte_Magnitude+G2_Temporal_Activity | 3.3 seconds
source | pairwise_unseen | G1_Packet_Byte_Magnitude+G3_TCP_Control_Flags | 3.5 seconds
source | pairwise_unseen | G1_Packet_Byte_Magnitude+G4_Rate_Header_Flow_Context | 5.2 seconds
source | pairwise_unseen | G2_Temporal_Activity+G3_TCP_Control_Flags | 3.3 seconds
source | pairwise_unseen | G2_Temporal_Activity+G4_Rate_Header_Flow_Context | 3.2 seconds
source | pairwise_unseen | G3_TCP_Control_Flags+G4_Rate_Header_Flow_Context | 3.2 seconds
target | complete | None | 25.8 seconds
target | single | G1_Packet_Byte_Magnitude | 25.0 seconds
target | single | G2_Temporal_Activity | 24.3 seconds
target | single | G3_TCP_Control_Flags | 26.0 seconds
target | single | G4_Rate_Header_Flow_Context | 23.2 seconds
target | pairwise_unseen | G1_Packet_Byte_Magnitude+G2_Temporal_Activity | 26.6 seconds
target | pairwise_unseen | G1_Packet_Byte_Magnitude+G3_TCP_Control_Flags | 24.8 seconds
target | pairwise_unseen | G1_Packet_Byte_Magnitude+G4_Rate_Header_Flow_Context | 24.2 seconds
target | pairwise_unseen | G2_Temporal_Activity+G3_TCP_Control_Flags | 26.4 seconds
target | pairwise_unseen | G2_Temporal_Activity+G4_Rate_Header_Flow_Context | 23.4 seconds
target | pairwise_unseen | G3_TCP_Control_Flags+G4_Rate_Header_Flow_Context | 25.8 seconds
Seed 2027 | indicators_only: evaluation completed in 315.9 seconds.

========================================================================
EVALUATING SEED 2027 | augmentation_only
========================================================================
source | complete | None | 1.6 seconds
source | single | G1_Packet_Byte_Magnitude | 1.6 seconds
source | single | G2_Temporal_Activity | 1.6 seconds
source | single | G3_TCP_Control_Flags | 1.6 seconds
source | single | G4_Rate_Header_Flow_Context | 1.8 seconds
source | pairwise_unseen | G1_Packet_Byte_Magnitude+G2_Temporal_Activity | 2.7 seconds
source | pairwise_unseen | G1_Packet_Byte_Magnitude+G3_TCP_Control_Flags | 2.6 seconds
source | pairwise_unseen | G1_Packet_Byte_Magnitude+G4_Rate_Header_Flow_Context | 1.6 seconds
source | pairwise_unseen | G2_Temporal_Activity+G3_TCP_Control_Flags | 1.6 seconds
source | pairwise_unseen | G2_Temporal_Activity+G4_Rate_Header_Flow_Context | 1.6 seconds
source | pairwise_unseen | G3_TCP_Control_Flags+G4_Rate_Header_Flow_Context | 1.6 seconds
target | complete | None | 12.7 seconds
target | single | G1_Packet_Byte_Magnitude | 12.7 seconds
target | single | G2_Temporal_Activity | 11.3 seconds
target | single | G3_TCP_Control_Flags | 11.6 seconds
target | single | G4_Rate_Header_Flow_Context | 12.6 seconds
target | pairwise_unseen | G1_Packet_Byte_Magnitude+G2_Temporal_Activity | 13.2 seconds
target | pairwise_unseen | G1_Packet_Byte_Magnitude+G3_TCP_Control_Flags | 12.5 seconds
target | pairwise_unseen | G1_Packet_Byte_Magnitude+G4_Rate_Header_Flow_Context | 10.2 seconds
target | pairwise_unseen | G2_Temporal_Activity+G3_TCP_Control_Flags | 12.7 seconds
target | pairwise_unseen | G2_Temporal_Activity+G4_Rate_Header_Flow_Context | 12.8 seconds
target | pairwise_unseen | G3_TCP_Control_Flags+G4_Rate_Header_Flow_Context | 12.7 seconds
Seed 2027 | augmentation_only: evaluation completed in 155.1 seconds.

========================================================================
EVALUATING SEED 2028 | indicators_only
========================================================================
source | complete | None | 3.8 seconds
source | single | G1_Packet_Byte_Magnitude | 3.8 seconds
source | single | G2_Temporal_Activity | 5.9 seconds
source | single | G3_TCP_Control_Flags | 3.9 seconds
source | single | G4_Rate_Header_Flow_Context | 3.7 seconds
source | pairwise_unseen | G1_Packet_Byte_Magnitude+G2_Temporal_Activity | 4.3 seconds
source | pairwise_unseen | G1_Packet_Byte_Magnitude+G3_TCP_Control_Flags | 5.6 seconds
source | pairwise_unseen | G1_Packet_Byte_Magnitude+G4_Rate_Header_Flow_Context | 3.7 seconds
source | pairwise_unseen | G2_Temporal_Activity+G3_TCP_Control_Flags | 3.8 seconds
source | pairwise_unseen | G2_Temporal_Activity+G4_Rate_Header_Flow_Context | 5.1 seconds
source | pairwise_unseen | G3_TCP_Control_Flags+G4_Rate_Header_Flow_Context | 4.6 seconds
target | complete | None | 28.8 seconds
target | single | G1_Packet_Byte_Magnitude | 27.8 seconds
target | single | G2_Temporal_Activity | 28.4 seconds
target | single | G3_TCP_Control_Flags | 29.6 seconds
target | single | G4_Rate_Header_Flow_Context | 29.0 seconds
target | pairwise_unseen | G1_Packet_Byte_Magnitude+G2_Temporal_Activity | 30.0 seconds
target | pairwise_unseen | G1_Packet_Byte_Magnitude+G3_TCP_Control_Flags | 29.4 seconds
target | pairwise_unseen | G1_Packet_Byte_Magnitude+G4_Rate_Header_Flow_Context | 27.7 seconds
target | pairwise_unseen | G2_Temporal_Activity+G3_TCP_Control_Flags | 28.0 seconds
target | pairwise_unseen | G2_Temporal_Activity+G4_Rate_Header_Flow_Context | 28.9 seconds
target | pairwise_unseen | G3_TCP_Control_Flags+G4_Rate_Header_Flow_Context | 29.1 seconds
Seed 2028 | indicators_only: evaluation completed in 364.7 seconds.

========================================================================
EVALUATING SEED 2028 | augmentation_only
========================================================================
source | complete | None | 1.5 seconds
source | single | G1_Packet_Byte_Magnitude | 1.6 seconds
source | single | G2_Temporal_Activity | 1.5 seconds
source | single | G3_TCP_Control_Flags | 1.9 seconds
source | single | G4_Rate_Header_Flow_Context | 2.5 seconds
source | pairwise_unseen | G1_Packet_Byte_Magnitude+G2_Temporal_Activity | 2.4 seconds
source | pairwise_unseen | G1_Packet_Byte_Magnitude+G3_TCP_Control_Flags | 1.6 seconds
source | pairwise_unseen | G1_Packet_Byte_Magnitude+G4_Rate_Header_Flow_Context | 1.5 seconds
source | pairwise_unseen | G2_Temporal_Activity+G3_TCP_Control_Flags | 1.6 seconds
source | pairwise_unseen | G2_Temporal_Activity+G4_Rate_Header_Flow_Context | 2.0 seconds
source | pairwise_unseen | G3_TCP_Control_Flags+G4_Rate_Header_Flow_Context | 1.5 seconds
target | complete | None | 12.2 seconds
target | single | G1_Packet_Byte_Magnitude | 12.4 seconds
target | single | G2_Temporal_Activity | 10.9 seconds
target | single | G3_TCP_Control_Flags | 10.9 seconds
target | single | G4_Rate_Header_Flow_Context | 12.2 seconds
target | pairwise_unseen | G1_Packet_Byte_Magnitude+G2_Temporal_Activity | 12.6 seconds
target | pairwise_unseen | G1_Packet_Byte_Magnitude+G3_TCP_Control_Flags | 11.1 seconds
target | pairwise_unseen | G1_Packet_Byte_Magnitude+G4_Rate_Header_Flow_Context | 10.3 seconds
target | pairwise_unseen | G2_Temporal_Activity+G3_TCP_Control_Flags | 12.6 seconds
target | pairwise_unseen | G2_Temporal_Activity+G4_Rate_Header_Flow_Context | 12.2 seconds
target | pairwise_unseen | G3_TCP_Control_Flags+G4_Rate_Header_Flow_Context | 10.6 seconds
Seed 2028 | augmentation_only: evaluation completed in 147.6 seconds.

========================================================================
EVALUATING SEED 2029 | indicators_only

%run /content/verify_corrected_ablation_manifests.py

In [ ]:
%run "/content/verify_corrected_ablation_manifests_v2.py"

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

Corrected component-ablation provenance audit
================================================================
Audit version: 2.0
Audited folder: /content/drive/MyDrive/research/researchdata/NIDS_Research/NIDS_Research_Checkpoints/five_seed_confirmatory_replication/component_ablation_corrected
Status: PASS
Authoritative protocol mismatches: 0
Component protocol mismatches: 0
Models with missing files: 0
Models with parameter mismatches: 0
component_ablation_nonselective_all.csv: 440 / 440 rows
component_ablation_selective_all.csv: 1320 / 1320 rows

Saved:
/content/drive/MyDrive/research/researchdata/NIDS_Research/NIDS_Research_Checkpoints/five_seed_confirmatory_replication/component_ablation_corrected/corrected_ablation_manifest_audit.csv
/content/drive/MyDrive/research/researchdata/NIDS_Research/NIDS_Research_Checkpoints/five_seed_confirmatory_replication/component_ablation_corrected/corrected_ablation_manifest_audit.json

In [ ]:
%run "/content/drive/MyDrive/research/researchdata/NIDS_Research/prepare_random_forest_replication.py"

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Verifying the seven frozen authoritative files...
Inspecting all five frozen Parquet partitions...

Random Forest replication preparation
====================================================================
Status: PASS
Protocol: NEW_PROTOCOL_FROZEN
Seeds: [2027, 2028, 2029, 2030, 2031]
Predictors: 77
Semantic groups: 4
Frozen files verified: 7 / 7
Parquet partitions verified: 5 / 5
Model: RandomForestClassifier
Trees: 300
Maximum depth: 20
Target use: evaluation only

Protocol saved: /content/drive/MyDrive/research/researchdata/NIDS_Research/NIDS_Research_Checkpoints/five_seed_confirmatory_replication/random_forest_model_family_replication/random_forest_protocol_frozen.json
Audit saved: /content/drive/MyDrive/research/researchdata/NIDS_Research/NIDS_Research_Checkpoints/five_seed_confirmatory_replication/random_forest_model_family_replication/random_forest_pretraining_audit.json

PRETRAINING_PROTOCOL_COMPLETE

%run "/content/drive/MyDrive/research/researchdata/NIDS_Research/train_random_forest_five_seed.py"

In [ ]:
%run "/content/drive/MyDrive/research/researchdata/NIDS_Research/train_random_forest_five_seed.py"

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Source training: (598043, 77)
Source validation: (152964, 77)
Source calibration: (99084, 77)
Calibrator-fit rows: 49542
Policy-selection rows: 49542
Predictors: 77
Semantic groups: 4

========================================================================
RANDOM FOREST CONFIRMATORY SEED: 2027
========================================================================
Ordinary baseline: training trees 1-50...

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Ordinary baseline: 50/300 trees saved in 83.5 seconds.
Ordinary baseline: training trees 51-100...

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Ordinary baseline: 100/300 trees saved in 76.5 seconds.
Ordinary baseline: training trees 101-150...

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Ordinary baseline: 150/300 trees saved in 73.7 seconds.
Ordinary baseline: training trees 151-200...

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Ordinary baseline: 200/300 trees saved in 74.3 seconds.
Ordinary baseline: training trees 201-250...

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Ordinary baseline: 250/300 trees saved in 74.0 seconds.
Ordinary baseline: training trees 251-300...

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Ordinary baseline: 300/300 trees saved in 76.6 seconds.
Ordinary baseline training complete.
Creating group-aware training data...
Group-aware training shape: (1196086, 81)
Mask assignment counts: {'G1_Packet_Byte_Magnitude': 149302, 'G2_Temporal_Activity': 149765, 'G3_TCP_Control_Flags': 149712, 'G4_Rate_Header_Flow_Context': 149264}
Group-aware model: training trees 1-50...

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Group-aware model: 50/300 trees saved in 200.7 seconds.
Group-aware model: training trees 51-100...

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Group-aware model: 100/300 trees saved in 203.9 seconds.
Group-aware model: training trees 101-150...

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Group-aware model: 150/300 trees saved in 189.2 seconds.
Group-aware model: training trees 151-200...

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Group-aware model: 200/300 trees saved in 201.1 seconds.
Group-aware model: training trees 201-250...

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Group-aware model: 250/300 trees saved in 197.9 seconds.
Group-aware model: training trees 251-300...

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Group-aware model: 300/300 trees saved in 210.4 seconds.
Group-aware training complete.
Seed 2027 training and source-only policy creation complete.

========================================================================
RANDOM FOREST CONFIRMATORY SEED: 2028
========================================================================
Ordinary baseline: training trees 1-50...

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Ordinary baseline: 50/300 trees saved in 81.5 seconds.
Ordinary baseline: training trees 51-100...

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Ordinary baseline: 100/300 trees saved in 76.7 seconds.
Ordinary baseline: training trees 101-150...

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Ordinary baseline: 150/300 trees saved in 74.5 seconds.
Ordinary baseline: training trees 151-200...

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Ordinary baseline: 200/300 trees saved in 78.9 seconds.
Ordinary baseline: training trees 201-250...

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Ordinary baseline: 250/300 trees saved in 76.2 seconds.
Ordinary baseline: training trees 251-300...

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Ordinary baseline: 300/300 trees saved in 74.1 seconds.
Ordinary baseline training complete.
Creating group-aware training data...
Group-aware training shape: (1196086, 81)
Mask assignment counts: {'G1_Packet_Byte_Magnitude': 148823, 'G2_Temporal_Activity': 150055, 'G3_TCP_Control_Flags': 149501, 'G4_Rate_Header_Flow_Context': 149664}
Group-aware model: training trees 1-50...

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Group-aware model: 50/300 trees saved in 203.2 seconds.
Group-aware model: training trees 51-100...

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Group-aware model: 100/300 trees saved in 193.8 seconds.
Group-aware model: training trees 101-150...

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Group-aware model: 150/300 trees saved in 195.0 seconds.
Group-aware model: training trees 151-200...

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Group-aware model: 200/300 trees saved in 203.2 seconds.
Group-aware model: training trees 201-250...

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Group-aware model: 250/300 trees saved in 212.7 seconds.
Group-aware model: training trees 251-300...

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Group-aware model: 300/300 trees saved in 215.5 seconds.
Group-aware training complete.
Seed 2028 training and source-only policy creation complete.

========================================================================
RANDOM FOREST CONFIRMATORY SEED: 2029
========================================================================
Ordinary baseline: training trees 1-50...

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Ordinary baseline: 50/300 trees saved in 77.5 seconds.
Ordinary baseline: training trees 51-100...

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Ordinary baseline: 100/300 trees saved in 76.0 seconds.
Ordinary baseline: training trees 101-150...

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Ordinary baseline: 150/300 trees saved in 74.3 seconds.
Ordinary baseline: training trees 151-200...

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Ordinary baseline: 200/300 trees saved in 74.6 seconds.
Ordinary baseline: training trees 201-250...

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Ordinary baseline: 250/300 trees saved in 75.8 seconds.
Ordinary baseline: training trees 251-300...

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Ordinary baseline: 300/300 trees saved in 75.0 seconds.
Ordinary baseline training complete.
Creating group-aware training data...
Group-aware training shape: (1196086, 81)
Mask assignment counts: {'G1_Packet_Byte_Magnitude': 149531, 'G2_Temporal_Activity': 149478, 'G3_TCP_Control_Flags': 149884, 'G4_Rate_Header_Flow_Context': 149150}
Group-aware model: training trees 1-50...

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Group-aware model: 50/300 trees saved in 191.4 seconds.
Group-aware model: training trees 51-100...

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Group-aware model: 100/300 trees saved in 200.4 seconds.
Group-aware model: training trees 101-150...

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Group-aware model: 150/300 trees saved in 196.3 seconds.
Group-aware model: training trees 151-200...

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Group-aware model: 200/300 trees saved in 203.8 seconds.
Group-aware model: training trees 201-250...

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Group-aware model: 250/300 trees saved in 212.8 seconds.
Group-aware model: training trees 251-300...

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Group-aware model: 300/300 trees saved in 207.4 seconds.
Group-aware training complete.
Seed 2029 training and source-only policy creation complete.

========================================================================
RANDOM FOREST CONFIRMATORY SEED: 2030
========================================================================
Ordinary baseline: training trees 1-50...

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Ordinary baseline: 50/300 trees saved in 77.7 seconds.
Ordinary baseline: training trees 51-100...

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Ordinary baseline: 100/300 trees saved in 71.9 seconds.
Ordinary baseline: training trees 101-150...

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Ordinary baseline: 150/300 trees saved in 74.0 seconds.
Ordinary baseline: training trees 151-200...

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Ordinary baseline: 200/300 trees saved in 80.3 seconds.
Ordinary baseline: training trees 201-250...

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Ordinary baseline: 250/300 trees saved in 79.9 seconds.
Ordinary baseline: training trees 251-300...

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Ordinary baseline: 300/300 trees saved in 79.7 seconds.
Ordinary baseline training complete.
Creating group-aware training data...
Group-aware training shape: (1196086, 81)
Mask assignment counts: {'G1_Packet_Byte_Magnitude': 149489, 'G2_Temporal_Activity': 149119, 'G3_TCP_Control_Flags': 149853, 'G4_Rate_Header_Flow_Context': 149582}
Group-aware model: training trees 1-50...

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Group-aware model: 50/300 trees saved in 193.9 seconds.
Group-aware model: training trees 51-100...

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Group-aware model: 100/300 trees saved in 197.0 seconds.
Group-aware model: training trees 101-150...

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Group-aware model: 150/300 trees saved in 205.2 seconds.
Group-aware model: training trees 151-200...

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Group-aware model: 200/300 trees saved in 201.7 seconds.
Group-aware model: training trees 201-250...

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Group-aware model: 250/300 trees saved in 211.1 seconds.
Group-aware model: training trees 251-300...

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Group-aware model: 300/300 trees saved in 209.6 seconds.
Group-aware training complete.
Seed 2030 training and source-only policy creation complete.

========================================================================
RANDOM FOREST CONFIRMATORY SEED: 2031
========================================================================
Ordinary baseline: training trees 1-50...

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Ordinary baseline: 50/300 trees saved in 73.3 seconds.
Ordinary baseline: training trees 51-100...

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Ordinary baseline: 100/300 trees saved in 70.3 seconds.
Ordinary baseline: training trees 101-150...

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Ordinary baseline: 150/300 trees saved in 67.8 seconds.
Ordinary baseline: training trees 151-200...

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Ordinary baseline: 200/300 trees saved in 71.3 seconds.
Ordinary baseline: training trees 201-250...

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Ordinary baseline: 250/300 trees saved in 67.0 seconds.
Ordinary baseline: training trees 251-300...

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Ordinary baseline: 300/300 trees saved in 73.8 seconds.
Ordinary baseline training complete.
Creating group-aware training data...
Group-aware training shape: (1196086, 81)
Mask assignment counts: {'G1_Packet_Byte_Magnitude': 149448, 'G2_Temporal_Activity': 149728, 'G3_TCP_Control_Flags': 149402, 'G4_Rate_Header_Flow_Context': 149465}
Group-aware model: training trees 1-50...

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Group-aware model: 50/300 trees saved in 185.4 seconds.
Group-aware model: training trees 51-100...

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Group-aware model: 100/300 trees saved in 189.0 seconds.
Group-aware model: training trees 101-150...

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Group-aware model: 150/300 trees saved in 191.1 seconds.
Group-aware model: training trees 151-200...

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Group-aware model: 200/300 trees saved in 203.8 seconds.
Group-aware model: training trees 201-250...

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Group-aware model: 250/300 trees saved in 205.6 seconds.
Group-aware model: training trees 251-300...

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(

Group-aware model: 300/300 trees saved in 207.9 seconds.
Group-aware training complete.
Seed 2031 training and source-only policy creation complete.

All five Random Forest seeds have completed training.
RANDOM_FOREST_FIVE_SEED_TRAINING_COMPLETE

The Random Forest training is successfully completed and valid. No retraining is required.

Verified:

Five seeds completed: 2027–2031
Ordinary models: five × 300 trees
Group-aware models: five × 300 trees
Ordinary input: 77 features
Group-aware input: 81 features
Group-aware training rows: 1,196,086 per seed
Calibration and policy selection used source data only
No errors or failed seeds

The balanced_subsample warning is harmless here because the training data remained unchanged during every warm-start checkpoint.

Next: evaluation

Download:

evaluate_random_forest_five_seed.py

Place it in:

/content/drive/MyDrive/research/researchdata/NIDS_Research/

Run:

%run "/content/drive/MyDrive/research/researchdata/NIDS_Research/evaluate_random_forest_five_see

In [2]:
%run "/content/drive/MyDrive/research/researchdata/NIDS_Research/evaluate_random_forest_five_seed.py"

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Source test: (150178, 77)
Target test: (999143, 77)
Source attack rate: 0.203265
Target attack rate: 0.169215
Target use: final evaluation only

========================================================================
EVALUATING RANDOM FOREST SEED: 2027
Completed conditions restored: 0 / 22
========================================================================
source | complete | None | 8.0 seconds | saved
source | single | G1_Packet_Byte_Magnitude | 6.0 seconds | saved
source | single | G2_Temporal_Activity | 8.2 seconds | saved
source | single | G3_TCP_Control_Flags | 6.5 seconds | saved
source | single | G4_Rate_Header_Flow_Context | 8.7 seconds | saved
source | pairwise_unseen | G1_Packet_Byte_Magnitude+G2_Temporal_Activity | 5.1 seconds | saved
source | pairwise_unseen | G1_Packet_Byte_Magnitude+G3_TCP_Control_Flags | 7.1 seconds | saved
source | pairwise_unseen | G1_Packet_Byte_Magnitude+G4_Rate_Header_Flow_Context | 6.9 seconds | saved
source | pairwise_unseen | G2_Temporal_Activity+G3_TCP_Control_Flags | 6.7 seconds | saved
source | pairwise_unseen | G2_Temporal_Activity+G4_Rate_Header_Flow_Context | 7.3 seconds | saved
source | pairwise_unseen | G3_TCP_Control_Flags+G4_Rate_Header_Flow_Context | 6.1 seconds | saved
target | complete | None | 47.5 seconds | saved
target | single | G1_Packet_Byte_Magnitude | 44.8 seconds | saved
target | single | G2_Temporal_Activity | 45.2 seconds | saved
target | single | G3_TCP_Control_Flags | 47.1 seconds | saved
target | single | G4_Rate_Header_Flow_Context | 47.4 seconds | saved
target | pairwise_unseen | G1_Packet_Byte_Magnitude+G2_Temporal_Activity | 38.2 seconds | saved
target | pairwise_unseen | G1_Packet_Byte_Magnitude+G3_TCP_Control_Flags | 42.8 seconds | saved
target | pairwise_unseen | G1_Packet_Byte_Magnitude+G4_Rate_Header_Flow_Context | 43.5 seconds | saved
target | pairwise_unseen | G2_Temporal_Activity+G3_TCP_Control_Flags | 42.1 seconds | saved
target | pairwise_unseen | G2_Temporal_Activity+G4_Rate_Header_Flow_Context | 42.5 seconds | saved
target | pairwise_unseen | G3_TCP_Control_Flags+G4_Rate_Header_Flow_Context | 46.7 seconds | saved
Seed 2027 evaluation completed in 564.6 seconds.

========================================================================
EVALUATING RANDOM FOREST SEED: 2028
Completed conditions restored: 0 / 22
========================================================================
source | complete | None | 7.1 seconds | saved
source | single | G1_Packet_Byte_Magnitude | 7.4 seconds | saved
source | single | G2_Temporal_Activity | 6.0 seconds | saved
source | single | G3_TCP_Control_Flags | 8.6 seconds | saved
source | single | G4_Rate_Header_Flow_Context | 6.2 seconds | saved
source | pairwise_unseen | G1_Packet_Byte_Magnitude+G2_Temporal_Activity | 7.5 seconds | saved
source | pairwise_unseen | G1_Packet_Byte_Magnitude+G3_TCP_Control_Flags | 5.5 seconds | saved
source | pairwise_unseen | G1_Packet_Byte_Magnitude+G4_Rate_Header_Flow_Context | 5.8 seconds | saved
source | pairwise_unseen | G2_Temporal_Activity+G3_TCP_Control_Flags | 7.2 seconds | saved
source | pairwise_unseen | G2_Temporal_Activity+G4_Rate_Header_Flow_Context | 5.5 seconds | saved
source | pairwise_unseen | G3_TCP_Control_Flags+G4_Rate_Header_Flow_Context | 8.3 seconds | saved
target | complete | None | 46.2 seconds | saved
target | single | G1_Packet_Byte_Magnitude | 41.2 seconds | saved
target | single | G2_Temporal_Activity | 44.6 seconds | saved
target | single | G3_TCP_Control_Flags | 48.9 seconds | saved
target | single | G4_Rate_Header_Flow_Context | 51.2 seconds | saved
target | pairwise_unseen | G1_Packet_Byte_Magnitude+G2_Temporal_Activity | 41.1 seconds | saved
target | pairwise_unseen | G1_Packet_Byte_Magnitude+G3_TCP_Control_Flags | 45.0 seconds | saved
target | pairwise_unseen | G1_Packet_Byte_Magnitude+G4_Rate_Header_Flow_Context | 44.4 seconds | saved
target | pairwise_unseen | G2_Temporal_Activity+G3_TCP_Control_Flags | 44.9 seconds | saved
target | pairwise_unseen | G2_Temporal_Activity+G4_Rate_Header_Flow_Context | 44.3 seconds | saved
target | pairwise_unseen | G3_TCP_Control_Flags+G4_Rate_Header_Flow_Context | 49.9 seconds | saved
Seed 2028 evaluation completed in 577.1 seconds.

========================================================================
EVALUATING RANDOM FOREST SEED: 2029
Completed conditions restored: 0 / 22
========================================================================
source | complete | None | 6.9 seconds | saved
source | single | G1_Packet_Byte_Magnitude | 8.3 seconds | saved
source | single | G2_Temporal_Activity | 6.2 seconds | saved
source | single | G3_TCP_Control_Flags | 9.0 seconds | saved
source | single | G4_Rate_Header_Flow_Context | 6.6 seconds | saved
source | pairwise_unseen | G1_Packet_Byte_Magnitude+G2_Temporal_Activity | 7.9 seconds | saved
source | pairwise_unseen | G1_Packet_Byte_Magnitude+G3_TCP_Control_Flags | 5.9 seconds | saved
source | pairwise_unseen | G1_Packet_Byte_Magnitude+G4_Rate_Header_Flow_Context | 7.2 seconds | saved
source | pairwise_unseen | G2_Temporal_Activity+G3_TCP_Control_Flags | 7.1 seconds | saved
source | pairwise_unseen | G2_Temporal_Activity+G4_Rate_Header_Flow_Context | 6.4 seconds | saved
source | pairwise_unseen | G3_TCP_Control_Flags+G4_Rate_Header_Flow_Context | 7.8 seconds | saved
target | complete | None | 49.6 seconds | saved
target | single | G1_Packet_Byte_Magnitude | 45.5 seconds | saved
target | single | G2_Temporal_Activity | 46.6 seconds | saved
target | single | G3_TCP_Control_Flags | 49.7 seconds | saved
target | single | G4_Rate_Header_Flow_Context | 50.0 seconds | saved
target | pairwise_unseen | G1_Packet_Byte_Magnitude+G2_Temporal_Activity | 41.0 seconds | saved
target | pairwise_unseen | G1_Packet_Byte_Magnitude+G3_TCP_Control_Flags | 41.0 seconds | saved
target | pairwise_unseen | G1_Packet_Byte_Magnitude+G4_Rate_Header_Flow_Context | 43.2 seconds | saved
target | pairwise_unseen | G2_Temporal_Activity+G3_TCP_Control_Flags | 43.2 seconds | saved
target | pairwise_unseen | G2_Temporal_Activity+G4_Rate_Header_Flow_Context | 40.6 seconds | saved
target | pairwise_unseen | G3_TCP_Control_Flags+G4_Rate_Header_Flow_Context | 46.4 seconds | saved
Seed 2029 evaluation completed in 576.1 seconds.

========================================================================
EVALUATING RANDOM FOREST SEED: 2030
Completed conditions restored: 0 / 22
========================================================================
source | complete | None | 7.1 seconds | saved
source | single | G1_Packet_Byte_Magnitude | 6.6 seconds | saved
source | single | G2_Temporal_Activity | 7.4 seconds | saved
source | single | G3_TCP_Control_Flags | 6.2 seconds | saved
source | single | G4_Rate_Header_Flow_Context | 8.3 seconds | saved
source | pairwise_unseen | G1_Packet_Byte_Magnitude+G2_Temporal_Activity | 5.1 seconds | saved
source | pairwise_unseen | G1_Packet_Byte_Magnitude+G3_TCP_Control_Flags | 7.6 seconds | saved
source | pairwise_unseen | G1_Packet_Byte_Magnitude+G4_Rate_Header_Flow_Context | 5.7 seconds | saved
source | pairwise_unseen | G2_Temporal_Activity+G3_TCP_Control_Flags | 6.0 seconds | saved
source | pairwise_unseen | G2_Temporal_Activity+G4_Rate_Header_Flow_Context | 7.3 seconds | saved
source | pairwise_unseen | G3_TCP_Control_Flags+G4_Rate_Header_Flow_Context | 5.9 seconds | saved
target | complete | None | 45.4 seconds | saved
target | single | G1_Packet_Byte_Magnitude | 43.1 seconds | saved
target | single | G2_Temporal_Activity | 41.6 seconds | saved
target | single | G3_TCP_Control_Flags | 45.2 seconds | saved
target | single | G4_Rate_Header_Flow_Context | 46.8 seconds | saved
target | pairwise_unseen | G1_Packet_Byte_Magnitude+G2_Temporal_Activity | 40.7 seconds | saved
target | pairwise_unseen | G1_Packet_Byte_Magnitude+G3_TCP_Control_Flags | 41.1 seconds | saved
target | pairwise_unseen | G1_Packet_Byte_Magnitude+G4_Rate_Header_Flow_Context | 41.7 seconds | saved
target | pairwise_unseen | G2_Temporal_Activity+G3_TCP_Control_Flags | 43.0 seconds | saved
target | pairwise_unseen | G2_Temporal_Activity+G4_Rate_Header_Flow_Context | 40.1 seconds | saved
target | pairwise_unseen | G3_TCP_Control_Flags+G4_Rate_Header_Flow_Context | 45.8 seconds | saved
Seed 2030 evaluation completed in 547.7 seconds.

========================================================================
EVALUATING RANDOM FOREST SEED: 2031
Completed conditions restored: 0 / 22
========================================================================
source | complete | None | 7.3 seconds | saved
source | single | G1_Packet_Byte_Magnitude | 6.1 seconds | saved
source | single | G2_Temporal_Activity | 7.4 seconds | saved
source | single | G3_TCP_Control_Flags | 6.3 seconds | saved
source | single | G4_Rate_Header_Flow_Context | 8.3 seconds | saved
source | pairwise_unseen | G1_Packet_Byte_Magnitude+G2_Temporal_Activity | 5.1 seconds | saved
source | pairwise_unseen | G1_Packet_Byte_Magnitude+G3_TCP_Control_Flags | 7.7 seconds | saved
source | pairwise_unseen | G1_Packet_Byte_Magnitude+G4_Rate_Header_Flow_Context | 5.7 seconds | saved
source | pairwise_unseen | G2_Temporal_Activity+G3_TCP_Control_Flags | 6.5 seconds | saved
source | pairwise_unseen | G2_Temporal_Activity+G4_Rate_Header_Flow_Context | 7.1 seconds | saved
source | pairwise_unseen | G3_TCP_Control_Flags+G4_Rate_Header_Flow_Context | 6.0 seconds | saved
target | complete | None | 46.1 seconds | saved
target | single | G1_Packet_Byte_Magnitude | 43.9 seconds | saved
target | single | G2_Temporal_Activity | 43.8 seconds | saved
target | single | G3_TCP_Control_Flags | 45.7 seconds | saved
target | single | G4_Rate_Header_Flow_Context | 47.4 seconds | saved
target | pairwise_unseen | G1_Packet_Byte_Magnitude+G2_Temporal_Activity | 38.4 seconds | saved
target | pairwise_unseen | G1_Packet_Byte_Magnitude+G3_TCP_Control_Flags | 43.2 seconds | saved
target | pairwise_unseen | G1_Packet_Byte_Magnitude+G4_Rate_Header_Flow_Context | 40.3 seconds | saved
target | pairwise_unseen | G2_Temporal_Activity+G3_TCP_Control_Flags | 42.4 seconds | saved
target | pairwise_unseen | G2_Temporal_Activity+G4_Rate_Header_Flow_Context | 42.8 seconds | saved
target | pairwise_unseen | G3_TCP_Control_Flags+G4_Rate_Header_Flow_Context | 45.7 seconds | saved
Seed 2031 evaluation completed in 553.3 seconds.

Combined Random Forest outputs saved:
Non-selective rows: 220
Selective rows: 660
Paired rows: 110

Random Forest five-seed evaluation is complete.
RANDOM_FOREST_FIVE_SEED_EVALUATION_COMPLETE